AOT-Technologies/forms-flow-ai

forms-flow-web/src/apiManager/services/processServices.js
forms-flow-web/src/components/Application/ViewApplication.js
forms-flow-web/src/components/Draft/Edit.js
forms-flow-web/src/components/Draft/ViewDraft.js
forms-flow-web/src/components/Form/Item/Edit.js
forms-flow-web/src/components/Form/Item/SaveAsNewVersionConfirmationModal.js
forms-flow-web/src/components/Form/Item/View.js
forms-flow-web/src/components/Form/Stepper.js
forms-flow-web/src/components/Form/Steps/PreviewStepper.js
forms-flow-web/src/components/Form/Steps/SaveNext.js
forms-flow-web/src/components/Modeler/Edit.js
forms-flow-web/src/components/Modeler/Editors/BpmnEditor/index.js
forms-flow-web/src/components/Modeler/Editors/DmnEditor/index.js
forms-flow-web/src/components/Modeler/constants/bpmnTable.js
forms-flow-web/src/components/Modeler/constants/dmnTable.js
forms-flow-web/src/components/ServiceFlow/constants/taskConstants.js
forms-flow-web/src/components/ServiceFlow/details/TaskHeaderListView.js
forms-flow-web/src/components/ServiceFlow/list/ServiceTaskListView.js
forms-flow-web/src/components/ServiceFlow/list/search/TaskFilterListViewComponent.js
forms-flow-web/src/components/ServiceFlow/list/search/TaskSearchBarListView.js
forms-flow-web/src/components/ServiceFlow/list/sort/CreateNewFilter.js
forms-flow-web/src/components/ServiceFlow/list/sort/TaskAttributeComponent.js
forms-flow-web/src/modules/bpmTaskReducer.js

JIRA: 
Fixes some bugs in bpm abstraction

Filter bug fixes

---

forms-flow-api/src/formsflow_api/models/filter.py
forms-flow-api/src/formsflow_api/services/filter.py

JIRA: 
https://aottech.atlassian.net/browse/FWF-2727
- Users with an admin+ reviewer role can create filters;  view, edit & delete all filters.
- Users with only reviewer role: create filter, View filter created by them/ assigned to them, edit & delete - only created by them
- Add editPermission in the user filter list response.

Task filter backend access control changes

---

forms-flow-web/src/components/Application/ApplicationTable.js
forms-flow-web/src/components/Draft/DraftOperations.js
forms-flow-web/src/components/Draft/DraftTable.js
forms-flow-web/src/components/Form/Create.js
forms-flow-web/src/components/Form/constants/FormTable.js

JIRA: 
1.Added internationalisation changes

Internationalisation changes

---

forms-flow-api/src/formsflow_api/schemas/filter.py
forms-flow-api/src/formsflow_api/services/filter.py
forms-flow-api/tests/unit/api/test_filter.py
forms-flow-api/tests/utilities/base_test.py

JIRA: 
https://aottech.atlassian.net/browse/FWF-2753
https://aottech.atlassian.net/browse/FWF-2754
Webapi changes to support current user & current roles based tasks

Webapi changes for current user & roles based tasks

---

forms-flow-web-root-config/Dockerfile
forms-flow-web-root-config/package-lock.json
forms-flow-web-root-config/package.json
forms-flow-web/Dockerfile
forms-flow-web/package-lock.json
forms-flow-web/package.json

Web vulnerability fix

---

forms-flow-api/src/formsflow_api/resources/form_process_mapper.py

JIRA: 
Form creation/update throws "Error response received from server" instead of throwing validation errors.  
Forwarding the error message instead of the full exception object resolves the issue.

Resolve the problem of missing validation errors during form creation/update.

---

forms-flow-web/src/components/Application/ApplicationFilter.js
forms-flow-web/src/components/Application/ApplicationTable.js
forms-flow-web/src/components/Dashboard/Dashboard.js
forms-flow-web/src/components/Draft/DraftFilter.js
forms-flow-web/src/components/Draft/DraftTable.js
forms-flow-web/src/components/Form/constants/FormTable.js

JIRA: 
Internationalisation updates for new UI changes

Internationalisation updates for new UI changes

---

forms-flow-web/src/containers/Head.js

event capture removed

---

forms-flow-web/src/components/Application/ApplicationHistory.js
forms-flow-web/src/components/Application/Details/index.js
forms-flow-web/src/components/Application/ViewApplication.js
forms-flow-web/src/components/Dashboard/CardFormCounter.js
forms-flow-web/src/components/Dashboard/Dashboard.js
forms-flow-web/src/components/Draft/Details/index.js
forms-flow-web/src/components/Draft/Edit.js
forms-flow-web/src/components/Draft/ViewDraft.js
forms-flow-web/src/components/Form/Item/Submission/List.js
forms-flow-web/src/components/Form/Item/View.js
forms-flow-web/src/components/Form/List.js
forms-flow-web/src/components/Form/Stepper.js
forms-flow-web/src/components/Insights/Insights.js
forms-flow-web/src/components/Modeler/Main.js
forms-flow-web/src/containers/Head.js

JIRA: 
https://aottech.atlassian.net/jira/software/c/projects/FWF/issues/FWF-2772
* Fixed space  issues with icons

Fixed space issues

---

forms-flow-web/src/components/Form/Steps/PreviewStepper.js
forms-flow-web/src/components/Form/Steps/TaskvariableCreate.js
forms-flow-web/src/components/Form/constants/FormTable.js
forms-flow-web/src/components/Modeler/Editors/BpmnEditor/index.js
forms-flow-web/src/components/Modeler/constants/bpmnTable.js
forms-flow-web/src/components/Modeler/constants/dmnTable.js

fixed drop down issue in form table and process tab pagination issues

---

forms-flow-web/src/components/Application/ApplicationFilter.js
forms-flow-web/src/components/Application/ApplicationTable.js
forms-flow-web/src/components/Draft/Edit.js
forms-flow-web/src/components/Form/Item/Edit.js
forms-flow-web/src/components/Form/Item/View.js
forms-flow-web/src/components/Form/constants/FormTable.js
forms-flow-web/src/components/Modeler/constants/bpmnTable.js
forms-flow-web/src/components/Modeler/constants/dmnTable.js

JIRA: 
Issue Type:  https://aottech.atlassian.net/browse/FWF-2762
1.Added dropdown for submission status 
2. Translation changes
3. Submission table header changes

dropdown  for status & translation changes

---

forms-flow-web/src/components/ServiceFlow/list/search/TaskFilterListViewComponent.js

JIRA: 
application id search issue for filter is fixed

issue with application id search fix

---

forms-flow-web/src/components/Draft/Edit.js
forms-flow-web/src/components/Draft/List.js
forms-flow-web/src/components/Form/Item/Submission/List.js
forms-flow-web/src/components/Form/List.js
forms-flow-web/src/containers/Confirm.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-2778
* Updated delete button & messages

Updated delete message and button

---

forms-flow-web/src/components/Application/ApplicationFilter.js
forms-flow-web/src/components/Application/ApplicationTable.js
forms-flow-web/src/components/Draft/Edit.js
forms-flow-web/src/components/Draft/List.js
forms-flow-web/src/components/Form/Item/Edit.js
forms-flow-web/src/components/Form/Item/Submission/List.js
forms-flow-web/src/components/Form/Item/View.js
forms-flow-web/src/components/Form/List.js
forms-flow-web/src/components/Form/Steps/PreviewStepper.js
forms-flow-web/src/components/Form/Steps/TaskvariableCreate.js
forms-flow-web/src/components/Form/constants/FormTable.js
forms-flow-web/src/components/Modeler/Editors/BpmnEditor/index.js
forms-flow-web/src/components/Modeler/constants/bpmnTable.js
forms-flow-web/src/components/Modeler/constants/dmnTable.js
forms-flow-web/src/containers/Confirm.js

JIRA: 
Latest develop to bpm-abstraction branch

latest develop to bpm-abstraction branch

---

forms-flow-web/src/components/Form/constants/ClientTable.js

client list rework

---

forms-flow-web/src/components/ServiceFlow/list/sort/CreateNewFilter.js

JIRA: 
changes labels for current user task in task filter

changed labels for current user task

---

forms-flow-api/src/formsflow_api/resources/roles.py

JIRA: 
Make roles endpoint accessible to reviewers to be used in the task filter.

Make roles endpoint accessible to reviewers.

---

forms-flow-web/src/components/Form/constants/ClientTable.js
forms-flow-web/src/components/NotFound/pagenotfound.scss

fixed error page

---

forms-flow-web/src/components/ServiceFlow/ServiceFlow.scss
forms-flow-web/src/components/ServiceFlow/details/TaskHeaderListView.js
forms-flow-web/src/components/ServiceFlow/list/sort/CreateNewFilter.js
forms-flow-web/src/components/ServiceFlow/list/sort/TaskAttributeComponent.js

JIRA:  https://aottech.atlassian.net/browse/FWF-2790 
https://aottech.atlassian.net/browse/FWF-2789
Issue Type:  
1. Added space duedate or folllowupdate remove btn 
2. fixed datepicker issues 
3. Fixed assignee claiming or unclaiming issue

List view fixes

---

forms-flow-web/src/components/Form/List.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-2785
* Added form type (form/draft) in delete message
* Internationalization changes: https://github.com/AOT-Technologies/forms-flow-ai-micro-front-ends/pull/98

Added form type while deleting

---

forms-flow-bpm/Dockerfile-ARM64

Updating Docker file for ARM64 architecture

---

forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/AdminRestResource.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/impl/AdminRestResourceImpl.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/service/AdminRestService.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/service/impl/AdminRestServiceImpl.java

JIRA: 
* updated admin rest api implementation

updated admin REST API Implementation

---

forms-flow-api/src/formsflow_api/services/filter.py

JIRA: 
Include applicationId, and formName as default variables in the list of variables in the filter list endpoint.

Include default variables in the list of variables in the filter list endpoint.

---

forms-flow-web/src/components/Form/Item/View.js
forms-flow-web/src/components/Form/constants/ClientTable.js

Duplicate toast fix

---

forms-flow-web/src/components/ServiceFlow/index.js

JIRA: 
redirect issue in multi tenant for task is fixed

tenant redirect url in task fixed

---

forms-flow-api/src/formsflow_api/models/filter.py

JIRA: 
Update filter list endpoint to include default filter when tenant key is None

Update filter list endpoint for None tenant key

---

forms-flow-web/src/components/ServiceFlow/index.js
forms-flow-web/src/components/ServiceFlow/list/sort/CreateNewFilter.js

JIRA: 
removed specific user from create filter RBAC

Task filter new changes

---

forms-flow-web/src/components/ServiceFlow/ServiceFlow.scss
forms-flow-web/src/containers/TaskHead.js
forms-flow-web/src/styles.scss

task header rework

---

forms-flow-web/src/components/Form/List.js

1. form type or resource type deleted successfully

fixed form and resource delete message

---

forms-flow-web/src/components/ServiceFlow/list/search/TaskFilterListViewComponent.js
forms-flow-web/src/components/ServiceFlow/list/sort/TaskSortSelectedList.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-2798
* Updated pending translations in task page
*  micro-front-end PR: https://github.com/AOT-Technologies/forms-flow-ai-micro-front-ends/pull/105

Updated task page translation

---

forms-flow-web/src/components/Application/ApplicationTable.js

JIRA: https://aottech.atlassian.net/browse/FWF-2814
#Screen shot

"Edit form" added in application table

---

forms-flow-web/src/components/Modeler/constants/bpmnTable.js
forms-flow-web/src/components/Modeler/constants/dmnTable.js
forms-flow-web/src/components/ServiceFlow/NoTaskSelected/index.js

JIRA: 
*  Pagination text change
*  tasks page svg issue fixed

pagination label and svg fixes

---

forms-flow-web/src/apiManager/services/applicationServices.js
forms-flow-web/src/apiManager/services/draftService.js
forms-flow-web/src/components/Application/ApplicationFilter.js
forms-flow-web/src/components/Application/ApplicationTable.js
forms-flow-web/src/components/Application/List.js
forms-flow-web/src/components/Draft/DraftFilter.js
forms-flow-web/src/components/Draft/DraftTable.js
forms-flow-web/src/components/Draft/List.js

1. filter's ui change with button style on draft and submssions
2. loader added for pagination also in draft and application
3. loading fixed for api errors
4. close filter when action triggered
5. pagination error fixed for no data

Fixed draft and submission tab issues

---

forms-flow-web/src/components/ServiceFlow/list/ServiceTaskListView.js

Pagination typo fix

---

forms-flow-web/src/components/Application/ApplicationTable.js
forms-flow-web/src/components/Draft/DraftTable.js
forms-flow-web/src/components/ServiceFlow/details/AddGroupModal.js
forms-flow-web/src/components/ServiceFlow/details/TaskHeader.js
forms-flow-web/src/components/ServiceFlow/details/TaskHeaderListView.js

translation&tooltip fixes

---

forms-flow-web/src/components/ServiceFlow/index.js
forms-flow-web/src/components/ServiceFlow/list/ServiceTaskListView.js
forms-flow-web/src/components/ServiceFlow/list/sort/CreateNewFilter.js

Fixed task variables label

---

.github/workflows/forms-flow-bpm-cd.yml
.github/workflows/forms-flow-web-cd.yml

Target url change

---

forms-flow-web/src/components/Form/Item/index.js

JIRA: https://aottech.atlassian.net/browse/FWF-2732
Changes
1. Form submission authorization API call changed when a reviewer access the submission

Fixed view submission for reviewer

---

forms-flow-web/src/components/Application/ApplicationFilter.js
forms-flow-web/src/components/Draft/DraftFilter.js
forms-flow-web/src/components/ServiceFlow/list/search/TaskFilterListViewComponent.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-2830
https://aottech.atlassian.net/browse/FWF-2824
Accessibility fix in submission page and  button change in task list view search

Accessibility fix in submission page and  button change in task list view search

---

forms-flow-web/src/components/Form/Steps/TaskvariableCreate.js
forms-flow-web/src/components/Form/Steps/ViewAndEditTaskvariable.js
forms-flow-web/src/components/Form/constants/FormTable.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-2832
updates in accessibility of forms page in designer

updates in accessibility of forms page in designer

---

forms-flow-web/src/components/Application/ApplicationFilter.js
forms-flow-web/src/components/ServiceFlow/list/sort/CreateNewFilter.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-2783
Internationalization updates: https://github.com/AOT-Technologies/forms-flow-ai-micro-front-ends/pull/121
* Show results button disabled before typing any search values
*  Added "Select a status" label instead of blank space in submission status drop down

Submission filter bugs fixed

---

forms-flow-web/src/components/ServiceFlow/list/ServiceTaskList.js
forms-flow-web/src/containers/TaskHead.js

1. fixed No task matching filters found on the initial case
2. fixed task details show while view change. example card view to list view 
JIRA: https://aottech.atlassian.net/browse/FWF-2827
JIRA : https://aottech.atlassian.net/browse/FWF-2787

Fixed no task pages issue

---

forms-flow-data-analysis-api/docker-compose.yml
forms-flow-data-analysis-api/sample.env
forms-flow-data-analysis-api/src/api/__init__.py
forms-flow-data-analysis-api/src/api/resources/sentiment_analysis.py
forms-flow-data-analysis-api/src/api/utils/file_log_handler.py
forms-flow-data-analysis-api/src/api/utils/logging.py
forms-flow-data-analysis-api/tests/unit/utils/test_file_log_handler.py

JIRA: 
https://aottech.atlassian.net/browse/FWF-2837
File logs added to data analysis API for ELK support

Added file log to data analysis api for ELK support

---

forms-flow-web/src/components/Application/ApplicationFilter.js
forms-flow-web/src/components/Draft/DraftFilter.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-2857
* Removed first value in select and  added a placeholder instead
* Show results button disabled initially in drafts' filter

Submissions and drafts filter issues fixed

---

forms-flow-web/src/components/Application/ApplicationTable.js
forms-flow-web/src/components/Draft/DraftTable.js
forms-flow-web/src/modules/draftReducer.js

JIRA: https://aottech.atlassian.net/browse/FWF-2858
https://github.com/AOT-Technologies/forms-flow-ai/assets/83585487/a5ee63cc-d6bb-4408-b9fd-e47e81573d32

Application Filter - Search key retrieval.

---

forms-flow-web/src/apiManager/services/processServices.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-2744

formatted search text

---

forms-flow-web/src/components/ServiceFlow/list/search/TaskFilterListViewComponent.js

JIRA: 
* Updated to "Select a user" placeholder

Updated task filter placeholder

---

forms-flow-api/tests/docker/docker-compose.yml

JIRA: 
Update in the docker-compose.yml file for webapi tests.  Reference of bpm api-spec to point to the 'develop' branch.

Update in the docker-compose.yml file for webapi tests to reference the 'develop' branch.

---

forms-flow-api/migrations/versions/91f9cd061108_add_default_filter.py
forms-flow-api/src/formsflow_api/services/filter.py
forms-flow-api/src/migration_scripts/camunda_filter_migration.py

JIRA: 
fixed followup date uncheck issue while creating new filters, fixed from backend

follow update uncheck fixed

---

forms-flow-web/package-lock.json
forms-flow-web/package.json
forms-flow-web/src/components/Application/ApplicationHistory.js
forms-flow-web/src/components/Application/ApplicationTable.js
forms-flow-web/src/components/Application/Details/index.js
forms-flow-web/src/components/Dashboard/StatusChart.js
forms-flow-web/src/components/Draft/Details/index.js
forms-flow-web/src/components/Draft/DraftTable.js
forms-flow-web/src/components/Draft/Edit.js
forms-flow-web/src/components/Form/Item/Edit.js
forms-flow-web/src/components/Form/Item/Preview.js
forms-flow-web/src/components/Form/Item/Submission/Item/Edit.js
forms-flow-web/src/components/Form/Item/Submission/Item/View.js
forms-flow-web/src/components/Form/Item/View.js
forms-flow-web/src/components/Form/constants/ClientTable.js
forms-flow-web/src/components/Form/constants/FormTable.js
forms-flow-web/src/components/Insights/Insights.js
forms-flow-web/src/components/Modeler/constants/bpmnTable.js
forms-flow-web/src/components/Modeler/constants/dmnTable.js
forms-flow-web/src/components/ServiceFlow/details/AddGroupModal.js
forms-flow-web/src/components/ServiceFlow/details/ServiceTaskDetails.js
forms-flow-web/src/components/ServiceFlow/list/ServiceTaskListViewDetails.js

JIRA: https://aottech.atlassian.net/browse/FWF-2877
1. Removed react-overlay-loading package and its code
2. Added react-overlay-loading-ts package which currently support 17.xx react and also we can upgrade into 18 react version later

Changed react overlay loading package to react-overlay-loading-ts  

---

forms-flow-web/src/components/Application/ApplicationFilter.js
forms-flow-web/src/components/Application/ApplicationTable.js

JIRA: https://aottech.atlassian.net/browse/FWF-2852
1.data-testid added for submission table and filter component

data-testid added form submission table

---

forms-flow-web/src/components/ServiceFlow/details/ServiceTaskDetails.js

JIRA: 
1. fixed overlay spinner false

fixed task details form overlay loading

---

forms-flow-web/src/components/Form/Create.js
forms-flow-web/src/components/Form/FileUpload/SelectFormForDownload.js
forms-flow-web/src/components/Form/Item/Edit.js
forms-flow-web/src/components/Form/Steps/PreviewStepper.js
forms-flow-web/src/components/Form/Steps/TaskvariableCreate.js
forms-flow-web/src/components/Form/Steps/ViewAndEditTaskvariable.js
forms-flow-web/src/components/Form/constants/FormTable.js
forms-flow-web/src/components/ServiceFlow/list/ServiceTaskList.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-2879
changes in form menu ,create form and edit form pages with new bootstrap

changes in form menu ,create form and edit form pages with new bootstrap

---

forms-flow-web/src/components/Application/ApplicationTable.js

Fixed data-testid in submission table

---

.github/workflows/forms-flow-api-ci.yml
.github/workflows/forms-flow-data-analysis-api-ci.yml
.github/workflows/forms-flow-documents-ci.yml
forms-flow-api/Dockerfile
forms-flow-api/requirements.txt
forms-flow-api/src/formsflow_api/services/external/keycloak.py
forms-flow-api/src/formsflow_api/services/factory/keycloak_client_service.py
forms-flow-api/src/formsflow_api/services/factory/keycloak_group_service.py
forms-flow-data-analysis-api/Dockerfile
forms-flow-documents/Dockerfile
forms-flow-documents/requirements.txt
forms-flow-documents/src/formsflow_documents/services/pdf.py
jobs/sentiment-analysis/Dockerfile

JIRA: 
https://aottech.atlassian.net/browse/FWF-2615
Upgrade Python to the latest stable version
- Upgraded Python to 3.12.1 in web API and documents API.
- Upgraded Python to 3.11.7 in data-analysis API(Pytorch is not available for python3.12.1. )

Upgrade python to latest stable version

---

forms-flow-web/src/components/Application/ApplicationFilter.js
forms-flow-web/src/components/Application/ViewApplication.js
forms-flow-web/src/components/Application/historyTable.js
forms-flow-web/src/components/Form/ExportAsPdf/button.jsx

JIRA: https:/2./aottech.atlassian.net/browse/FWF-2855
1.Updated data-testid for submission filter component 
2.added data-testid for submissions details page

data-testid added for submission-details

---

forms-flow-web/src/components/Draft/Edit.js
forms-flow-web/src/components/Draft/ViewDraft.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-2854
Added data test ID for draft detail

Added data test id for draft detail

---

forms-flow-web/src/components/Draft/DraftFilter.js
forms-flow-web/src/components/Draft/DraftOperations.js
forms-flow-web/src/components/Draft/DraftTable.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-2853
Added data test ID for draft table & draft filter

Added data test id for draft table & draft filter

---

forms-flow-web/src/components/Modeler/Main.js
forms-flow-web/src/components/Modeler/constants/dmnTable.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-2891
* "Workflow" label changed to "DMN" for DMN

Button labels changed for DMN

---

forms-flow-web/src/components/Application/ApplicationFilter.js
forms-flow-web/src/components/Application/ApplicationTable.js
forms-flow-web/src/components/Form/Item/CreateTemplateConfirmModal.js
forms-flow-web/src/components/Form/Item/FormHistoryModal.js
forms-flow-web/src/components/Form/Item/SaveAsNewVersionConfirmationModal.js
forms-flow-web/src/components/Form/Steps/PreviewStepper.js
forms-flow-web/src/components/Form/constants/ClientTable.js
forms-flow-web/src/components/Form/constants/FormTable.js
forms-flow-web/src/components/Modeler/constants/bpmnTable.js
forms-flow-web/src/components/Modeler/constants/dmnTable.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-2879
https://aottech.atlassian.net/browse/FWF-2880
https://aottech.atlassian.net/browse/FWF-2884
bootstrap fixes for form ,submissions and process tabs pages

bootstrap fixes for form ,submissions and process tabs pages

---

forms-flow-web/src/containers/Confirm.js

JIRA: 
Added data test id for delete modal

Added data test id for delete modal

---

forms-flow-web/src/components/Dashboard/Dashboard.js
forms-flow-web/src/components/Dashboard/dashboard.scss

JIRA: 
https://aottech.atlassian.net/browse/FWF-2881

Bootstrap upgrade changes on dashboard

---

forms-flow-web/src/components/ServiceFlow/details/TaskHeader.js
forms-flow-web/src/components/ServiceFlow/list/TaskVariable.js
forms-flow-web/src/components/ServiceFlow/list/search/TaskFilterListViewComponent.js
forms-flow-web/src/components/ServiceFlow/list/sort/TaskAttributeComponent.js

JIRA: https://aottech.atlassian.net/browse/FWF-2904
Bootstrap fixes in task  page

Bootstrap fixes in task and admin tab pages

---

deployment/docker/sample.env
forms-flow-api/sample.env

redis url added sample.env

---

forms-flow-web/src/components/Form/List.js
forms-flow-web/src/containers/Head.js

data testid added on HEAD component

---

forms-flow-web/src/components/Form/Item/CreateTemplateConfirmModal.js
forms-flow-web/src/components/Form/Item/FormHistoryModal.js
forms-flow-web/src/components/Form/Item/Preview.js
forms-flow-web/src/components/Form/Steps/PreviewStepper.js
forms-flow-web/src/components/Form/Steps/SaveNext.js
forms-flow-web/src/components/Form/Steps/TaskvariableCreate.js
forms-flow-web/src/components/Form/Steps/ViewAndEditTaskvariable.js
forms-flow-web/src/components/Form/Steps/WorkFlow.js

JIRA: https://aottech.atlassian.net/browse/FWF-2916
1.Data-testid added for form preview pages
2.fixed badge alignment

data-testid added for form-preview pages

---

forms-flow-web/src/components/Form/Create.js
forms-flow-web/src/components/Form/Item/Edit.js
forms-flow-web/src/components/Form/Steps/SaveNext.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-2879
pending ui issues fix in forms

pending ui issues fix in forms

---

deployment/docker/docker-compose.yml
forms-flow-forms/docker-compose.yml
forms-flow-web/src/components/Form/Item/Preview.js

changed formio image version and added form intraction in view edit window for designer

changed formio image version and added form interaction in view edit window for designer

---

forms-flow-api/requirements.txt
forms-flow-api/requirements/prod.txt

- Dependency update to default branch

Reverting the utils dependency to default branch

---

forms-flow-web/src/styles.scss

Removed Hardcoded colors and added color variables from global scss
File name styles.scss

Removed Colors and added color variables in styles.scss file

---

forms-flow-web/src/styles.scss

Reverts AOT-Technologies/forms-flow-ai#1842

Revert "Removed Colors and added color variables in styles.scss file"

---

forms-flow-web/src/components/Draft/Edit.js
forms-flow-web/src/components/Form/Item/View.js

JIRA: 
1. removed exitType default value because the default value is UNMOUNT so the toast will work

fixed submission saved toast issue in draft

---

forms-flow-web/src/components/Form/Item/Preview.js

submit button showing but disabled on form interaction view of designer

---

forms-flow-bpm/forms-flow-bpm-camunda/pom.xml
forms-flow-bpm/forms-flow-bpm-camunda/src/main/java/org/camunda/bpm/extension/keycloak/sso/KeycloakCockpitPlugin.java
forms-flow-bpm/forms-flow-bpm-camunda/src/main/java/org/camunda/bpm/extension/keycloak/sso/OAuth2LoginSecurityConfig.java
forms-flow-bpm/forms-flow-bpm-camunda/src/main/resources/META-INF/resources/webjars/camunda/app/admin/scripts/config.js
forms-flow-bpm/forms-flow-bpm-camunda/src/main/resources/META-INF/resources/webjars/camunda/app/cockpit/scripts/config.js
forms-flow-bpm/forms-flow-bpm-camunda/src/main/resources/META-INF/resources/webjars/camunda/app/tasklist/scripts/config.js
forms-flow-bpm/forms-flow-bpm-camunda/src/main/resources/META-INF/resources/webjars/camunda/app/welcome/scripts/config.js
forms-flow-bpm/forms-flow-bpm-camunda/src/main/resources/application.yaml

JIRA: 
https://aottech.atlassian.net/browse/FWF-2780

[2780] added JWT validation to Camunda admin console

---

forms-flow-web/src/components/Application/ApplicationTable.js
forms-flow-web/src/components/Draft/DraftTable.js
forms-flow-web/src/components/Form/Item/SaveAsNewVersionConfirmationModal.js
forms-flow-web/src/components/Form/Item/View.js
forms-flow-web/src/components/Form/Stepper.js
forms-flow-web/src/components/Form/constants/ClientTable.js
forms-flow-web/src/components/Form/constants/FormTable.js
forms-flow-web/src/containers/Confirm.js

JIRA: https://aottech.atlassian.net/browse/FWF-2849
1.data-testid added for sort icons and save as new version modal

pending  data-testid added

---

forms-flow-web/src/components/BPMN/bpm.scss

Added Color Variables in bpm.scss file

Color variable added in bpm.scss

---

forms-flow-web/src/containers/styles.scss

Removed hardcoded colors and added color variables instead from styles.scc of container.

Removed hardcoded colors and added color variables instead.

---

forms-flow-web/src/components/Form/Steps/steps.scss

JIRA:  https://aottech.atlassian.net/browse/FWF-2573
Added color variables from global.scss file and removed all hardcoded colors

Added Color Variables to the steps.scss file removing the hardcoded colors. 

---

forms-flow-web/src/styles.scss

JIRA:  https://aottech.atlassian.net/browse/FWF-2573
variables updated with styles.scss file

Colo variables update in styles scss file

---

forms-flow-web/src/components/ServiceFlow/details/TaskDetail.scss
forms-flow-web/src/components/ServiceFlow/details/UserSelectionDebounce.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-2834
Assignee Filter radio issue fixed

Assignee Filter radio issue fixed

---

forms-flow-web/src/components/Nodata/nodata.scss

removed unwanted import of theme file.

---

forms-flow-web/src/assets/styles/base.scss

Color variables added to the base.scss file from global scss file from micro front-end.

Added Color variables to base.scss file removing the hardcoded colors

---

forms-flow-web/src/components/Modeler/Editors/Editor.scss

Removed Hardcoded colors form editor.scss file and added the variables form global.scss

---

forms-flow-web/src/components/Form/constants/FormTable.js
forms-flow-web/src/components/Modeler/Editors/BpmnEditor/index.js
forms-flow-web/src/components/Modeler/Editors/DmnEditor/index.js
forms-flow-web/src/components/Modeler/Main.js
forms-flow-web/src/components/Modeler/constants/bpmnTable.js
forms-flow-web/src/components/Modeler/constants/dmnTable.js

JIRA: https://aottech.atlassian.net/browse/FWF-2959
1.data-testid added for process tab 
2.typo fix in data-testid

data-testid added for process tab

---

forms-flow-web/src/components/NotFound/pagenotfound.scss

Removed HC form pageNotFound.scss and added CSS color Variables instead

Removed HC form pageNotFound.scss and added CSS color Variables instead

---

forms-flow-web/src/components/Dashboard/dashboard.scss

JIRA:  https://aottech.atlassian.net/browse/FWF-2573 
Removed HC form Dashboard.scss and added CSS color Variables

Removed HC form Dashboard.scss and added CSS color Variables

---

forms-flow-web/src/components/Insights/Insights.scss

Removed HC color form insight.scss file and added variables form micro frontend's global.scss file.

Removed HC color form insight.scss file and added variables form micro frontend's global.scss file. 

---

forms-flow-web/src/components/Modeler/Modeler.scss

Removed HC colors and added color variables from global.scss file in Modeler.scss file.

Removed HC colors and added color variables from global.scss file in Modeler.scss file.

---

forms-flow-web/src/components/Form/stepper.scss

JIRA:  https://aottech.atlassian.net/browse/FWF-2573
Removed HC colors and added color variables from global.scss file in stepper.scss file.

Removed HC colors and added color variables from global.scss file in stepper.scss file.

---

forms-flow-web/src/assets/styles/layouts.scss

JIRA:  https://aottech.atlassian.net/browse/FWF-2573 
Removed HC colors and added color Variables

Removed HC color and added color Variables

---

forms-flow-web/src/components/ServiceFlow/ServiceFlow.scss
forms-flow-web/src/components/ServiceFlow/details/ServiceTaskDetails.js
forms-flow-web/src/components/ServiceFlow/details/TaskHeaderListView.js
forms-flow-web/src/components/ServiceFlow/details/UserSelectionDebounce.js
forms-flow-web/src/components/ServiceFlow/list/ServiceTaskList.js
forms-flow-web/src/components/ServiceFlow/list/ServiceTaskListView.js
forms-flow-web/src/components/ServiceFlow/list/ServiceTaskListViewDetails.js
forms-flow-web/src/components/ServiceFlow/list/sort/TaskSortSelectedList.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-2978
https://aottech.atlassian.net/browse/FWF-2836
1.tooltip changes and removed unwanted styles

tooltip changes and removed unwanted styles

---

forms-flow-web/src/components/ServiceFlow/ServiceFlow.scss
forms-flow-web/src/components/ServiceFlow/list/ServiceTaskListView.js

JIRA: https://aottech.atlassian.net/browse/FWF-2835
1.fixed ui issue on removing task attributes from listview
2.removed inline style

fixed UI issue on removing attributes

---

forms-flow-web/src/components/Application/Application.scss

Removed RC color and added CSS Color variable in Application.scss file

Removed RC color and added CSS Color variable in Application.scss file

---

forms-flow-api/src/formsflow_api/services/filter.py

JIRA: 
https://aottech.atlassian.net/browse/FWF-2989
Fixed - No default filters are showing on the task page if the 'All task' filter common to all tenants is deleted.

Multitenant default filter fix

---

forms-flow-web/src/components/ServiceFlow/ServiceFlow.scss

Removed HC colors form serviceFlow.scss file and added css color variables from global.scss file consisted in Micro front ends theme.

Removed HC colors form serviceFlow.scss file and added css color variables from global.scss file consisted in Micro front ends theme.

---

forms-flow-web/src/components/ServiceFlow/list/search/TaskSearchBarListView.scss

JIRA: 
https://aottech.atlassian.net/browse/FWF-2990
task page calendar ui break fixed

task page calendar ui break fixed

---

forms-flow-web/src/components/ServiceFlow/details/TaskDetail.scss

JIRA:  https://aottech.atlassian.net/browse/FWF-2573
Removed RC color and added CSS Color variable in taskDetails.scss file

Removed RC color and added CSS Color variable in taskDetails.scss file

---

forms-flow-web/src/components/ServiceFlow/details/TaskHeader.js

JIRA: 
1. if condition removed on task update stages. and calling manually task list and task details API to update the data

Socket call ignored on task update

---

forms-flow-web/src/components/ServiceFlow/list/ServiceTaskList.js

JIRA: 
removed unwanted task filter api call from master branch

unwanted api call removed from task loading in master branch

---

.github/workflows/forms-flow-data-analysis-api-cd.yml
forms-flow-web/src/apiManager/services/processServices.js

fixed the process page pagination issue
updated github acttion for snyk report

updated pagination fix for process page

---

CHANGELOG.md

JIRA: https://aottech.atlassian.net/browse/FWF-3027

Changelog for v5.3.1 release

---

forms-flow-web/src/components/ServiceFlow/ServiceFlow.scss
forms-flow-web/src/components/ServiceFlow/details/TaskHeaderListView.js
forms-flow-web/src/components/ServiceFlow/filter/ServiceTaskFilterListDropDown.js
forms-flow-web/src/components/ServiceFlow/list/ServiceTaskListView.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-2992
https://aottech.atlassian.net/browse/FWF-2995
* Task filter scroll issue fixed
* Task list view font-weight issue fixed

Task list UI fixes

---

forms-flow-api-utils/src/formsflow_api_utils/services/external/formio.py
forms-flow-api-utils/src/formsflow_api_utils/utils/__init__.py
forms-flow-api-utils/src/formsflow_api_utils/utils/formio.py
forms-flow-api/src/formsflow_api/resources/__init__.py
forms-flow-api/src/formsflow_api/resources/ipaas.py

Adding support to get form by form_id

---

deployment/docker/docker-compose.yml

JIRA: 
Change the formio image to v5.3.0.

Change formio image to v5.3.0

---

forms-flow-data-analysis-api/model_training/requirements.txt
forms-flow-data-analysis-api/requirements.txt
jobs/sentiment-analysis/requirements.txt

JIRA: 
Vulnerability fix data analysis

Vulnerabilityfix data analysis

---

forms-flow-web/src/components/ServiceFlow/list/ServiceTaskListView.js

JIRA: 
view details click issue fixed

view details issue fixed

---

forms-flow-web/src/components/ServiceFlow/details/TaskHeaderListView.js
forms-flow-web/src/components/ServiceFlow/list/ServiceTaskListViewDetails.js

JIRA:  https://aottech.atlassian.net/browse/FWF-2985
1.Fixed loading in view details on listview

fixed loading in view details - list view

---

forms-flow-api-utils/src/formsflow_api_utils/exceptions/__init__.py

JIRA: 
Validation error messages are not displayed properly

Webapi utils: Validation error handler message display issue fix

---

forms-flow-web/src/components/ServiceFlow/list/ServiceTaskListViewDetails.js

JIRA: 
* Fixed incorrect URL in the multi tenant instance on clicking 'back to task' from List view
Issue:
Fix:

Fixed incorrect URL in the multi tenant instance on clicking 'back to task' from List view

---

forms-flow-web/src/components/ServiceFlow/list/ServiceTaskList.js
forms-flow-web/src/components/ServiceFlow/list/TaskVariable.js

JIRA: https://aottech.atlassian.net/browse/FWF-2991, https://aottech.atlassian.net/browse/FWF-3042

Taskpage fix

---

.github/workflows/forms-flow-api-ci.yml
forms-flow-api/src/formsflow_api/resources/user.py
forms-flow-api/src/formsflow_api/services/factory/keycloak_admin.py
forms-flow-api/src/formsflow_api/services/factory/keycloak_client_service.py
forms-flow-api/src/formsflow_api/services/factory/keycloak_factory.py
forms-flow-api/src/formsflow_api/services/factory/keycloak_group_service.py
forms-flow-api/src/formsflow_api/services/user.py

JIRA: 
https://aottech.atlassian.net/browse/FWF-2972
Admin -  user search by role is support added in webapi

Webapi : Admin - User search by role fix

---

.github/workflows/forms-flow-api-ci.yml
forms-flow-api/src/formsflow_api/services/filter.py

JIRA: 
Rename application Id to Submission ID in default variables

Webapi: Rename application Id to Submission ID.

---

forms-flow-web/src/components/ServiceFlow/list/search/TaskFilterViewComponent.js

JIRA: https://aottech.atlassian.net/browse/FWF-2991?focusedCommentId=22951

Renamed application id to submission in task search

---

forms-flow-web/src/components/ServiceFlow/list/sort/CreateNewFilter.js

JIRA: https://aottech.atlassian.net/browse/FWF-3060
In MT, the create filter and updater filter will append the tenant name along with the candidate group to fetch data from bpm.
and the append tenant name will be screened in UI.
Create filter: 
Update Filter:
result from bpm:

Candidate Group criteria issue resolved in task filter.

---

forms-flow-web/src/components/Form/Item/Submission/Item/View.js

Removed main-header class form submission view

---

forms-flow-api/src/formsflow_api/constants/__init__.py
forms-flow-api/src/formsflow_api/models/application.py
forms-flow-api/src/formsflow_api/models/base_model.py
forms-flow-api/src/formsflow_api/models/draft.py
forms-flow-api/src/formsflow_api/services/application.py
forms-flow-api/src/formsflow_api/services/draft.py

- Added flush support to Base model
- Changed exception handling on application and draft submission
- Added transaction rollback and commit based on outcome

Adding transaction management to application and draft submission

---

forms-flow-web/src/apiManager/services/bpmFormServices.js
forms-flow-web/src/components/ServiceFlow/list/sort/CreateNewFilter.js
forms-flow-web/src/components/ServiceFlow/list/sort/TaskAttributeComponent.js

JIRA: https://aottech.atlassian.net/browse/FWF-3103
- Added form select option in the 'Create New Filter' feature.
- When selecting a form, it will now fetch the task variables and display them inside the task attributes.
- Resolved the 'Display authorized tasks based on user roles' edit state issue.

❇️ Added form select option in create new filter

---

forms-flow-api/src/formsflow_api/services/application.py
forms-flow-api/src/formsflow_api/services/draft.py

JIRA: https://aottech.atlassian.net/browse/FWF-3006
- Move start_task to async to fix issue with diamond dependency

Moving BPM start_task to async

---

forms-flow-web/src/components/ServiceFlow/list/ServiceTaskListView.js

JIRA: https://aottech.atlassian.net/browse/FWF-3079
1.labels are highlighted in listview

labels of taskvariables highlighted in listview

---

forms-flow-web/src/components/ServiceFlow/list/search/TaskFilterViewComponent.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-3049
task search datepicker input field value  issue fixed

task search datepicker input field value  issue fix

---

forms-flow-web/src/components/Form/Steps/WorkFlow.js

Fixed show text text field after clicked select all field in task variables

---

forms-flow-web/src/apiManager/services/formatterService.js
forms-flow-web/src/components/ServiceFlow/list/sort/CreateNewFilter.js

JIRA: https://aottech.atlassian.net/browse/FWF-3098
Changed process definition key to Workflow in task filter and added a dropdown list for the same.

Added Dropdown for workflow in task filter

---

forms-flow-web/src/components/Form/Steps/WorkFlow.js

JIRA: https://aottech.atlassian.net/browse/FWF-3133
1. fixed retaining selected workflow when task variable changes

Fixed workflow retaining after changing task variable

---

forms-flow-web/src/components/ServiceFlow/list/sort/CreateNewFilter.js

JIRA: 
1. set default value of `includeAssignedTasks` true  when the condition is true `isTasksForCurrentUserGroupsEnabled || candidateGroup`

set default value true to includeAssingnedTask

---

forms-flow-api/src/formsflow_api/constants/__init__.py
forms-flow-api/src/formsflow_api/resources/user.py
forms-flow-api/src/formsflow_api/schemas/__init__.py
forms-flow-api/src/formsflow_api/schemas/user.py
forms-flow-api/src/formsflow_api/services/factory/keycloak_admin.py
forms-flow-api/src/formsflow_api/services/factory/keycloak_client_service.py
forms-flow-api/src/formsflow_api/services/factory/keycloak_group_service.py

JIRA: 
https://aottech.atlassian.net/browse/FWF-3075
Webapi Endpoint to add user to tenant

Webapi Endpoint to add user to tenant

---

forms-flow-web/src/components/ServiceFlow/list/sort/CreateNewFilter.js

JIRA: 
* https://aottech.atlassian.net/browse/FWF-3100?focusedCommentId=23348
Trimmed '/' from candidate group value
* https://aottech.atlassian.net/browse/FWF-3011
Instead of first name and last name, username added as assignee select option

Select value changes for candidate group and assignee

---

forms-flow-web/src/components/ServiceFlow/list/sort/CreateNewFilter.js

JIRA: https://aottech.atlassian.net/browse/FWF-3146
* "Candidate Group" label and placeholder changed to:  
User Group or
User Role (if multitenant environment)
Internationalization changes: https://github.com/AOT-Technologies/forms-flow-ai-micro-front-ends/pull/157/commits/ad10ced09824f4ac9860152f2f153de1f07ec418

Candidate group label and placeholder changed

---

forms-flow-web/src/components/ServiceFlow/list/sort/CreateNewFilter.js

JIRA: https://aottech.atlassian.net/browse/FWF-3154
1.Label changed for editing filter 
2.Typo fix for the title of filter name

Label change for editing filter

---

forms-flow-web-root-config/Dockerfile
forms-flow-web-root-config/package-lock.json

JIRA: https://aottech.atlassian.net/browse/FWF-3140

⬆️  Upgraded node version in formsflow-web-root-config

---

forms-flow-bpm/forms-flow-bpm-camunda/src/main/resources/application.yaml

Remove duplicate httpRelativePath in bpm application yaml file

---

forms-flow-web-root-config/Dockerfile
forms-flow-web/Dockerfile

JIRA: 
https://aottech.atlassian.net/browse/FWF-3149

added nginx new version to fix vulnerabilities

---

forms-flow-web/src/apiManager/services/applicationServices.js
forms-flow-web/src/apiManager/services/draftService.js

JIRA: https://aottech.atlassian.net/browse/FWF-3155
1.Fixed count and pagination

Fixed count and pagination issue in submission

---

forms-flow-web/src/components/ServiceFlow/list/sort/CreateNewFilter.js

JIRA: https://aottech.atlassian.net/browse/FWF-3165
* User roles not listing in multitenant environment issue fixed

user roles not listing fixed in multitenancy

---

forms-flow-web/src/components/Form/Steps/ViewAndEditTaskvariable.js
forms-flow-web/src/components/Form/Steps/WorkFlow.js
forms-flow-web/src/components/Form/Steps/steps.scss

task variable selection rework

---

forms-flow-web/src/components/ServiceFlow/ServiceFlow.scss
forms-flow-web/src/components/ServiceFlow/filter/ServiceTaskFilterListDropDown.js
forms-flow-web/src/components/ServiceFlow/list/sort/CreateNewFilter.js

JIRA: https://aottech.atlassian.net/browse/FWF-3028
task filter dropdown issue fixed

task filter dropdown issue fixed

---

forms-flow-web/src/components/Form/Steps/WorkFlow.js

Removed console.log

---

.github/workflows/forms-flow-api-cd.yml
.github/workflows/forms-flow-bpm-cd.yml
.github/workflows/forms-flow-documents-cd.yml
.github/workflows/forms-flow-root-config-cd.yml
.github/workflows/qa-deployment.yml

Update Deployment CD

---

forms-flow-web/src/components/ServiceFlow/list/sort/CreateNewFilter.js

JIRA: https://aottech.atlassian.net/browse/FWF-3043
task filter alert issue fix

task filter alert issue fix

---

forms-flow-data-analysis-api/docker-compose.yml
forms-flow-data-analysis-api/requirements.txt
forms-flow-data-analysis-api/sample.env
forms-flow-data-analysis-api/src/api/__init__.py
forms-flow-data-analysis-api/src/api/config.py
forms-flow-data-analysis-api/src/api/utils/file_log_handler.py
jobs/sentiment-analysis/requirements.txt

JIRA: 
- Ignore file log on data analysis
**Github vulnerability fix** 
- Jinja vulnerable to HTML attribute injection when passing user input as keys to xmlattr filter
Package- jinja2
Affected versions< 3.1.3
Patched version - 3.1.3
- no Fix version available for Minerva timing attack on P-256 in python-ecdsa

Github vulnerability fix and Ignore file log on data analysis

---

forms-flow-web/src/components/Application/ApplicationFilter.js

https://aottech.atlassian.net/browse/FWF-3129
JIRA: 
1.Aligned input fields in application filter

aligned input fields in applicationfilter

---

forms-flow-web/src/components/Application/ApplicationFilter.js
forms-flow-web/src/components/Draft/DraftFilter.js
forms-flow-web/src/components/ServiceFlow/list/search/TaskFilterViewComponent.js
forms-flow-web/src/components/ServiceFlow/list/search/TaskSearchBarListView.scss

JIRA: 
1.Added translation in search in task page 
2.Fixed alignment issues in draft & application

Fixed alignment issues in draft & application filter

---

forms-flow-web/src/components/Insights/Insights.js

JIRA: https://aottech.atlassian.net/browse/FWF-3183
Viewport height is adjusted for insight dashboard
old:
updated:

Viewport adjustments in Insight dashboard

---

forms-flow-web/src/apiManager/services/bpmFormServices.js
forms-flow-web/src/apiManager/services/processServices.js
forms-flow-web/src/components/Form/Steps/WorkFlow.js
forms-flow-web/src/components/ServiceFlow/list/sort/CreateNewFilter.js
forms-flow-web/src/components/ServiceFlow/list/sort/TaskAttributeComponent.js

2. application id removed from task variable
JIRA: 

1 .Task variable fixed for published forms and reworked some function

---

forms-flow-web/src/components/ServiceFlow/filter/ServiceTaskFilterListDropDown.js

JIRA: https://aottech.atlassian.net/browse/FWF-3171
1.Fixed pagination issue

fixed pagination issue when changing the filter in task page

---

forms-flow-web/src/components/ServiceFlow/list/search/TaskFilterViewComponent.js
forms-flow-web/src/modules/bpmTaskReducer.js

JIRA: https://aottech.atlassian.net/browse/FWF-3189
1.Fixed search results retaining issue when switching the task filter

Fixed search results issue when switching the taskfilter

---

forms-flow-api/src/formsflow_api/models/draft.py
forms-flow-api/src/formsflow_api/services/draft.py

JIRA: 
https://aottech.atlassian.net/browse/FWF-3182
- When calling the patch endpoint, the draft data is not being saved in the database.

Fix draft data not saved while update

---

forms-flow-api/requirements.txt
forms-flow-api/requirements/prod.txt
forms-flow-documents/requirements.txt
forms-flow-documents/requirements/prod.txt
forms-flow-web/src/components/ServiceFlow/details/ServiceTaskDetails.js
forms-flow-web/src/components/ServiceFlow/details/TaskHeaderListView.js
forms-flow-web/src/components/ServiceFlow/list/ServiceTaskList.js
forms-flow-web/src/components/ServiceFlow/list/ServiceTaskListViewDetails.js

Updated requirement txt and changed tooltip

---

forms-flow-web/src/components/Form/Steps/WorkFlow.js

translation fix added

---

forms-flow-web/src/components/Dashboard/Dashboard.js
forms-flow-web/src/components/Form/Steps/ViewAndEditTaskvariable.js

translation added

---

forms-flow-api/requirements.txt
forms-flow-api/requirements/prod.txt
forms-flow-documents/requirements.txt
forms-flow-documents/requirements/prod.txt

JIRA: 
Update requirements file

Update requirements file

---

forms-flow-web/src/components/ServiceFlow/list/search/TaskSearchBarView.js

JIRA: https://aottech.atlassian.net/browse/FWF-3186

filters removed for tasks count zero

---

forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/ProcessInstanceRestResource.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/impl/ProcessInstanceRestResourceImpl.java
forms-flow-web/src/components/ServiceFlow/details/TaskHeader.js

update process-instance and taskheader

---

forms-flow-web/src/components/Draft/Details/DraftDetails.js

JIRA: https://aottech.atlassian.net/browse/FWF-3207
modified date issue in draft

modified date issue in draft

---

forms-flow-api/requirements.txt
forms-flow-api/requirements/prod.txt
forms-flow-documents/requirements.txt
forms-flow-documents/requirements/prod.txt

JIRA: 
- Change in webapi & documents API requirements file to point to the release branch

Change in webapi & documents api requirements file to point to the release branch 5.3.1

---

forms-flow-api/requirements.txt
forms-flow-api/requirements/prod.txt
forms-flow-documents/requirements.txt
forms-flow-documents/requirements/prod.txt

JIRA: 
Change in webapi & documents api requirements file to point to the release branch

Change in webapi & documents api requirements file to point to the release 5.3.0 branch 

---

forms-flow-api/requirements.txt
forms-flow-api/requirements/prod.txt
forms-flow-documents/requirements.txt
forms-flow-documents/requirements/prod.txt

JIRA: 
Change in webapi & documents api requirements file to point to the release 5.2.2 branch

Change in webapi & documents api requirements file to point to the release 5.2.2 branch

---

forms-flow-api/requirements.txt
forms-flow-api/requirements/prod.txt
forms-flow-documents/requirements.txt
forms-flow-documents/requirements/prod.txt

JIRA: 
Change in webapi & documents api requirements file to point to the release 5.1.1 branch

Change in webapi & documents api requirements file to point to the release 5.1.1 branch

---

forms-flow-api/requirements.txt
forms-flow-api/requirements/prod.txt
forms-flow-documents/requirements.txt
forms-flow-documents/requirements/prod.txt
forms-flow-web/src/components/ServiceFlow/list/sort/CreateNewFilter.js

JIRA: 
Update requirements to point to the release branch & Fix workflow listing in creating filter in multitenancy

Update requirements to point to the release branch & Fix workflow listing in create filter in multitenancy

---

forms-flow-idm/realm-exports/Client based auth.json
forms-flow-idm/realm-exports/Group based auth.json

Updating idm realm exports to add formsflow-admin

---

forms-flow-api/requirements.txt
forms-flow-api/requirements/prod.txt
forms-flow-documents/requirements.txt
forms-flow-documents/requirements/prod.txt

JIRA: 
Change in webapi & documents api requirements file to point to the release 5.2.1 branch

Change in webapi & documents api requirements file to point to the release 5.2.1 branch

---

forms-flow-web/src/components/ServiceFlow/list/ServiceTaskListView.js

JIRA: https://aottech.atlassian.net/browse/FWF-3175
https://aottech.atlassian.net/browse/FWF-3194
1. Fixed task variable with long label 
2.  Inline css removed 
3. Fixed spacing issue between task variables

💄 fixed task variable  with long label

---

forms-flow-web/src/components/ServiceFlow/index.js

JIRA: https://aottech.atlassian.net/browse/FWF-3205
1.Fixed expand all or collapse all button issue when all tasks are expanded or collapsed individually

🐛 fixed expand all btn issue

---

forms-flow-web/src/components/ServiceFlow/list/ServiceTaskListView.js

JIRA: https://aottech.atlassian.net/browse/FWF-3175
1.Task variable label fix

🎨 task-variable label fix

---

deployment/docker/docker-compose.yml
forms-flow-forms/docker-compose.yml

[Changed] formio version from 6.0.0 to 6.1.0-alpha

---

forms-flow-api/requirements.txt

JIRA: 
The utils reference in the requirements.txt file has been updated to point to the develop branch.

The utils reference in the requirements.txt file has been updated to point to the develop branch.

---

forms-flow-web/src/components/ServiceFlow/list/sort/CreateNewFilter.js

JIRA: https://aottech.atlassian.net/browse/FWF-3170
1. groups and tasktitle removed from initial values

🐛  Fixed task variable displaying issue in list view

---

forms-flow-data-analysis-api/Dockerfile
forms-flow-data-analysis-api/entrypoint
forms-flow-data-analysis-api/entrypoint.sh

JIRA: 
- entrypoint file name changed with extension '.sh' to entrypoint.sh
- Made corresponding changes in the Dockerfile
- Installed in local system and tested it

Made changes in entrypoint and Dockerfile of Data Analysis API

---

forms-flow-web/src/components/Modeler/Modeler.scss

color issue fixed in form

---

forms-flow-web/src/components/Form/Item/Edit.js
forms-flow-web/src/components/Form/constants/ClientTable.js
forms-flow-web/src/components/Form/constants/FormTable.js
forms-flow-web/src/components/Modeler/constants/bpmnTable.js
forms-flow-web/src/components/Modeler/constants/dmnTable.js
forms-flow-web/src/components/ServiceFlow/list/search/TaskFilterViewComponent.js
forms-flow-web/src/components/ServiceFlow/list/sort/CreateNewFilter.js

JIRA: https://aottech.atlassian.net/browse/FWF-3289
1. Accessibility changes -label added for form fields
2. removed unused attributes

:accessibility: added  <label> element for form fields

---

forms-flow-api/src/formsflow_api/constants/__init__.py
forms-flow-api/src/formsflow_api/models/theme.py
forms-flow-api/src/formsflow_api/services/theme.py

JIRA: 
fixed create error in theme customization

fixed create issue in custom theme

---

forms-flow-web/src/styles.scss

JIRA: 
Design system update:
* Added missed color variables

FWF-3218: [Feature] Added missed color variables to style.css

---

forms-flow-web/src/styles.scss

JIRA: https://aottech.atlassian.net/browse/FWF-3216
https://aottech.atlassian.net/browse/FWF-3231
1.redundant style classes removed from style.scss

FWF-3216:[Bugfix] redundant style classes removed from style.scss

---

forms-flow-web/src/components/Modeler/Modeler.scss
forms-flow-web/src/variables.scss

JIRA: https://aottech.atlassian.net/browse/FWF-3334
* Added css issue fixes

FWF-3334: [Bugfix] Fixed css issues

---

forms-flow-web/src/components/Modeler/Editors/Editor.scss

- Changed background color
- Updated highlight foreground color to white.
JIRA: https://aottech.atlassian.net/browse/FWF-3347

FWF-3347: [Bugfix] Process-diagram highlight

---

forms-flow-web/src/components/AccessDenied/index.js

svg not correctly rendered issue fix

created Svg as component to fix the render issue

---

forms-flow-web/src/components/ServiceFlow/ServiceFlow.scss
forms-flow-web/src/components/ServiceFlow/filter/ServiceTaskFilterListDropDown.js
forms-flow-web/src/components/ServiceFlow/list/sort/CreateNewFilter.js
forms-flow-web/src/components/ServiceFlow/list/sort/TaskAttributeComponent.js
forms-flow-web/src/containers/TaskHead.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-3307
filter is selectable for view which was not created by them and it is in disabled mode

disabled filter for non reviewers

---

forms-flow-web/src/components/PrivateRoute.jsx

added bug fix for admin to other pages issue fix

added kcinstance fix

---

forms-flow-web/src/components/ServiceFlow/NoTaskSelected/index.js
forms-flow-web/src/components/ServiceFlow/ServiceFlow.scss
forms-flow-web/src/containers/Head.js

JIRA: https://aottech.atlassian.net/browse/FWF-3288
1.Fixed heading hierarchy for accessibility

:accessibility:  FWF-3288: [Bugfix] Fixed Heading hierarchy

---

forms-flow-web/src/containers/styles.scss

FWF-3349:[Bugfix] unwanted style removed

---

forms-flow-web/src/components/PrivateRoute.jsx

FWF:3310 [feature] fixed language change

---

forms-flow-idm/keycloak/themes/formsflow/login/register.ftl

JIRA: https://aottech.atlassian.net/browse/FWF-3315
Added tenantKey attribute so that the admin can see the registered users in admin page

FWF-3315: [Bugfix] fixed Admin users cannot see the registered users issue

---

forms-flow-web/src/components/ServiceFlow/filter/ServiceTaskFilterListDropDown.js
forms-flow-web/src/components/ServiceFlow/list/sort/CreateNewFilter.js
forms-flow-web/src/containers/TaskHead.js

initial creation of filter viewmode set to false

fix for setting viewmode false initial creating filter

---

forms-flow-web/src/components/ServiceFlow/list/sort/CreateNewFilter.js

[🐛BUG] Removed edit filter label from view mode

---

forms-flow-web/src/components/Form/Steps/WorkFlow.js

JIRA: https://aottech.atlassian.net/browse/FWF-3358

FWF3358: [Bugfix] Color difference in form create page

---

forms-flow-web/src/components/Form/Steps/WorkFlow.js

JIRA: 
bug fix for list data in processlist

added bugfix for process list

---

forms-flow-api/requirements.txt
forms-flow-api/requirements/prod.txt

JIRA: 
1. changed utils link form Abil's branch to AOT's develop

FWF:3361 changed utils link to develop branch

---

forms-flow-web/src/containers/Head.js

JIRA: https://aottech.atlassian.net/browse/FWF-3288

FWF:3288/[BUGFIX] Fixed heading hierachy issue

---

forms-flow-api/src/formsflow_api/schemas/roles.py
forms-flow-api/src/formsflow_api/services/factory/keycloak_client_service.py
forms-flow-api/src/formsflow_api/services/factory/keycloak_group_service.py
forms-flow-api/tests/unit/api/test_roles.py

JIRA: 
https://aottech.atlassian.net/browse/FWF-3325
Post endpoint changes to save group role mapping
multitenant

❇️ FWF-3325: [Feature] Save group role mapping

---

CHANGELOG.md

[Sync 🔗] Sync/master to develop 6.0.2

---

forms-flow-web/src/components/Form/FileUpload/SelectFormForDownload.js
forms-flow-web/src/components/Form/Item/Submission/List.js
forms-flow-web/src/containers/Head.js
forms-flow-web/src/containers/styles.scss

JIRA: https://aottech.atlassian.net/browse/FWF-3217
1. Removed unused and redundant classes 
2. Update bootstrap classes

Fwf-3217: [bugfix] Removed unused and redundant classes

---

forms-flow-web/src/components/Form/Item/Preview.js
forms-flow-web/src/components/Form/Item/deviceView.js
forms-flow-web/src/components/Form/Item/styles.css

JIRA: https://aottech.atlassian.net/browse/FWF-3338
Issue Type: FEATURE (POC)

FWF-3338: [Feature] Multi-device preview.

---

.github/workflows/forms-flow-idm.yml
forms-flow-idm/keycloak/Dockerfile

JIRA: https://aottech.atlassian.net/browse/FWF-3372
1. Deleted Old Dockerfile
2. Added CD for pushing package image

✨  FWF:3372 [Feature] Added keycloak data package

---

forms-flow-web/src/components/ServiceFlow/list/sort/CreateNewFilter.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-3387

Added disable feature for  specific user in filter

---

forms-flow-bpm/forms-flow-bpm-camunda/src/main/java/org/camunda/bpm/extension/keycloak/rest/KeycloakAuthenticationFilter.java
forms-flow-bpm/forms-flow-bpm-camunda/src/main/resources/application.yaml

JIRA: 
https://aottech.atlassian.net/browse/FWF-3363
BPM - Added tenantKey to logs

❇️ FWF-3363: [Feature] BPM: Added tenantKey to logs

---

forms-flow-web/src/components/ServiceFlow/list/sort/CreateNewFilter.js

JIRA: https://aottech.atlassian.net/browse/FWF-3418

FWF-3418: [Bugfix] - Added Custom class for alert.

---

forms-flow-web/src/components/Dashboard/Dashboard.js
forms-flow-web/src/components/Modeler/constants/bpmnTable.js
forms-flow-web/src/components/Modeler/constants/dmnTable.js

JIRA: https://aottech.atlassian.net/browse/FWF-3287
https://aottech.atlassian.net/browse/FWF-3289
1. Added accessible names for pagination 
2. Added label for search field in metrics

:accessibility: FWF-3287:[Bugfix] added accessibile name for pagination

---

.github/workflows/forms-flow-idm.yml
forms-flow-idm/keycloak/Dockerfile
forms-flow-idm/keycloak/docker-compose.yml
forms-flow-idm/keycloak/start-keycloak.sh

✨ Package Keylock custom data 

---

forms-flow-web/src/components/Form/FileUpload/fileUploadModal.js
forms-flow-web/src/components/Form/List.js
forms-flow-web/src/components/Form/List.scss
forms-flow-web/src/containers/MessageModal.js

-Cannot delete the form which has an existing submission,
-Cannot upload a form that already exists or soft-deleted
JIRA: https://aottech.atlassian.net/browse/FWF-3383
Deleting forms having existing submissions.

FWF-3383:[Bugfix] - Delete form and remove path collision

---

deployment/docker/docker-compose.yml
deployment/docker/sample.env
forms-flow-bpm/forms-flow-bpm-camunda/pom.xml
forms-flow-bpm/forms-flow-bpm-camunda/src/main/java/org/camunda/bpm/extension/commons/utils/VaultConfig.java
forms-flow-bpm/forms-flow-bpm-camunda/src/main/resources/application.yaml
forms-flow-bpm/sample.env

JIRA: 
https://aottech.atlassian.net/browse/FWF-3370
BPM  changes to support credentials from external cred manager
Tested by adding the config to a Listener

❇️ FWF-3370: [Feature] BPM  changes to support credentials from external cred manager

---

forms-flow-web/src/components/Form/FileUpload/fileUploadModal.js
forms-flow-web/src/components/Form/List.js

JIRA: https://aottech.atlassian.net/browse/FWF-3383

FWF-3383:[Bugfix]- Name must be unique Validation.

---

forms-flow-api-utils/src/formsflow_api_utils/utils/auth.py
forms-flow-api-utils/src/formsflow_api_utils/utils/permisions.py
forms-flow-api/requirements.txt
forms-flow-api/requirements/prod.txt

❇️ Feature/fwf 3327 auth role checking function modified

---

forms-flow-web/src/components/Form/constants/ClientTable.js
forms-flow-web/src/components/Form/constants/FormTable.js
forms-flow-web/src/components/Modeler/constants/bpmnTable.js

JIRA: https://aottech.atlassian.net/browse/FWF-3422

FWF-3422:[Bugfix]-Visible FF update for input tag.

---

CHANGELOG.md
deployment/docker/sample.env
forms-flow-bpm/forms-flow-bpm-camunda/src/main/java/org/camunda/bpm/extension/commons/utils/VaultConfig.java

JIRA: 
Added a conditional property to VaultConfig so that it is only loaded if 'spring.cloud.vault.enabled' is set to true.

FWF-3370: [Feature] Added conditional property to Vault Config

---

forms-flow-web/src/components/ServiceFlow/list/sort/CreateNewFilter.js
forms-flow-web/src/containers/TaskHead.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-3438
https://jam.dev/c/832d7b7e-e644-4631-8081-e9ece4a91bc6

fixed the initial count and also fixed deletion of filter issue

---

forms-flow-idm/keycloak/themes/formsflow/login/resources/css/login.css

JIRA: https://aottech.atlassian.net/browse/FWF-3447
keycloak login page mobile responsiveness fixed
>

FWF-3447: [Bugfix] keycloak login page mobile responsiveness fixed

---

forms-flow-web/src/components/ServiceFlow/list/sort/CreateNewFilter.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-3438

added fix for default filter count

---

forms-flow-web/src/components/AccessDenied/index.js

JIRA: https://aottech.atlassian.net/browse/FWF-3357?focusedCommentId=24763
* Issue:
* Fix:

FWF-3357: [Bugfix] Resolved redirect to default page issue in multitenancy

---

forms-flow-web/src/components/MultiTenant/LandingPage.js
forms-flow-web/src/components/PrivateRoute.jsx

Modified validate tenant key response 

---

forms-flow-api-utils/src/formsflow_api_utils/utils/caching.py
forms-flow-api/requirements.txt
forms-flow-api/requirements/prod.txt
forms-flow-api/sample.env

JIRA: 
- Updated connection string for redis

Updated the Redis connection string in forms-flow-api-utils for access in both cluster mode and single node.

---

forms-flow-documents/docker-compose.yml

1. Updated Forms-flow-documents docker-compose.yml

Update forms-flow-documents docker-compose.yml

---

.github/workflows/forms-flow-api-cd.yml
.github/workflows/forms-flow-bpm-cd.yml
.github/workflows/forms-flow-data-analysis-api-cd.yml
.github/workflows/forms-flow-documents-cd.yml
.github/workflows/forms-flow-root-config-cd.yml
.github/workflows/forms-flow-web-cd.yml
VERSION
deployment/docker/docker-compose.yml
forms-flow-web-root-config/docker-compose.yml
forms-flow-web-root-config/src/index.ejs

Updating image tag and microfrontend version to try out RBAC changes

---

forms-flow-api-utils/src/formsflow_api_utils/services/__init__.py
forms-flow-api-utils/src/formsflow_api_utils/services/external/__init__.py
forms-flow-api-utils/src/formsflow_api_utils/services/external/custom_submission.py

Added custom submission fetching in utils

---

.github/workflows/forms-flow-api-cd.yml
forms-flow-api-utils/src/formsflow_api_utils/utils/__init__.py
forms-flow-api-utils/src/formsflow_api_utils/utils/auth.py
forms-flow-api-utils/src/formsflow_api_utils/utils/permisions.py
forms-flow-api-utils/src/formsflow_api_utils/utils/user_context.py
forms-flow-api-utils/src/formsflow_api_utils/utils/util.py
forms-flow-api/requirements.txt
forms-flow-api/requirements/prod.txt
forms-flow-api/src/formsflow_api/app.py
forms-flow-api/src/formsflow_api/config.py
forms-flow-api/src/formsflow_api/resources/application.py
forms-flow-api/src/formsflow_api/resources/application_history.py
forms-flow-api/src/formsflow_api/resources/authorization.py
forms-flow-api/src/formsflow_api/resources/dashboards.py
forms-flow-api/src/formsflow_api/resources/draft.py
forms-flow-api/src/formsflow_api/resources/filter.py
forms-flow-api/src/formsflow_api/resources/form_process_mapper.py
forms-flow-api/src/formsflow_api/resources/formio.py
forms-flow-api/src/formsflow_api/resources/metrics.py
forms-flow-api/src/formsflow_api/resources/process.py
forms-flow-api/src/formsflow_api/resources/roles.py
forms-flow-api/src/formsflow_api/resources/theme.py
forms-flow-api/src/formsflow_api/resources/user.py
forms-flow-api/src/formsflow_api/services/application.py
forms-flow-api/src/formsflow_api/services/draft.py
forms-flow-api/src/formsflow_api/services/factory/keycloak_group_service.py

JIRA: 
1.  Updated router-level permissions.
2. Modified Formio roles mapping.
3. Reverted authentication changes to the previous mechanism.

❇️ [webapi] Router level authorization check  and adding permission matrix changes 

---

forms-flow-web/src/components/ServiceFlow/list/sort/CreateNewFilter.js

JIRA: https://aottech.atlassian.net/browse/FWF-3450

FWF-3450:[Feature]- Displayed Name of the creator in task filter.

---

forms-flow-api-utils/src/formsflow_api_utils/utils/pdf.py

JIRA: 
Added user details to local storage for EPD

API utils changes for EPD

---

.github/workflows/forms-flow-api-ci.yml
forms-flow-api/requirements.txt
forms-flow-api/requirements/prod.txt
forms-flow-api/src/formsflow_api/resources/process.py
forms-flow-api/src/formsflow_api/services/application.py
forms-flow-api/src/formsflow_api/services/filter.py
forms-flow-api/tests/unit/api/test_application.py
forms-flow-api/tests/unit/api/test_authorization.py
forms-flow-api/tests/unit/api/test_draft.py
forms-flow-api/tests/unit/api/test_filter.py
forms-flow-api/tests/unit/api/test_form_process_mapper.py
forms-flow-api/tests/unit/api/test_formio.py
forms-flow-api/tests/unit/api/test_process.py
forms-flow-api/tests/unit/api/test_roles.py
forms-flow-api/tests/unit/api/test_theme.py
forms-flow-api/tests/unit/api/test_user.py
forms-flow-api/tests/utilities/base_test.py

Feature/FWF:3478 changed testcase based on matrix permission

---

forms-flow-api-utils/src/formsflow_api_utils/utils/__init__.py
forms-flow-api-utils/src/formsflow_api_utils/utils/permisions.py
forms-flow-api-utils/src/formsflow_api_utils/utils/util.py
forms-flow-api/src/formsflow_api/resources/application.py
forms-flow-api/src/formsflow_api/resources/application_history.py
forms-flow-api/src/formsflow_api/resources/authorization.py
forms-flow-api/src/formsflow_api/resources/dashboards.py
forms-flow-api/src/formsflow_api/resources/draft.py
forms-flow-api/src/formsflow_api/resources/filter.py
forms-flow-api/src/formsflow_api/resources/form_process_mapper.py
forms-flow-api/src/formsflow_api/resources/formio.py
forms-flow-api/src/formsflow_api/resources/metrics.py
forms-flow-api/src/formsflow_api/resources/process.py
forms-flow-api/src/formsflow_api/resources/roles.py
forms-flow-api/src/formsflow_api/resources/theme.py
forms-flow-api/src/formsflow_api/resources/user.py
forms-flow-api/src/formsflow_api/services/application.py
forms-flow-api/src/formsflow_api/services/filter.py
forms-flow-api/tests/unit/api/test_application.py
forms-flow-api/tests/unit/api/test_authorization.py
forms-flow-api/tests/unit/api/test_draft.py
forms-flow-api/tests/unit/api/test_filter.py
forms-flow-api/tests/unit/api/test_form_process_mapper.py
forms-flow-api/tests/unit/api/test_formio.py
forms-flow-api/tests/unit/api/test_process.py
forms-flow-api/tests/unit/api/test_roles.py
forms-flow-api/tests/unit/api/test_theme.py
forms-flow-api/tests/unit/api/test_user.py
forms-flow-api/tests/utilities/base_test.py

Reworked structure

---

forms-flow-web/src/components/ServiceFlow/list/sort/CreateNewFilter.js

JIRA: https://aottech.atlassian.net/browse/FWF-3457
1. Fixed filter getting changed when edit and save one

FWF-3457:[BUGFIX]Fixed filter getting reset issue

---

forms-flow-web/src/components/PrivateRoute.jsx

FWF-3326: [Bugfix] Code formatted

---

forms-flow-api/src/formsflow_api/resources/roles.py
forms-flow-api/src/formsflow_api/resources/user.py
forms-flow-api/src/formsflow_api/services/factory/__init__.py
forms-flow-api/tests/unit/api/test_anonymous_application.py
forms-flow-api/tests/unit/api/test_application.py
forms-flow-api/tests/unit/api/test_application_history.py
forms-flow-api/tests/unit/api/test_authorization.py
forms-flow-api/tests/unit/api/test_checkpoint.py
forms-flow-api/tests/unit/api/test_dashboards.py
forms-flow-api/tests/unit/api/test_draft.py
forms-flow-api/tests/unit/api/test_filter.py
forms-flow-api/tests/unit/api/test_form_process_mapper.py
forms-flow-api/tests/unit/api/test_formio.py
forms-flow-api/tests/unit/api/test_keycloak_groups.py
forms-flow-api/tests/unit/api/test_metrics.py
forms-flow-api/tests/unit/api/test_process.py
forms-flow-api/tests/unit/api/test_roles.py
forms-flow-api/tests/unit/api/test_theme.py
forms-flow-api/tests/unit/api/test_user.py
forms-flow-api/tests/unit/models/test_application.py
forms-flow-api/tests/unit/models/test_application_audit.py
forms-flow-api/tests/unit/models/test_form_process_mapper.py
forms-flow-api/tests/unit/models/test_formprocessmapper.py
forms-flow-api/tests/unit/services/test_application.py
forms-flow-api/tests/unit/services/test_application_history.py
forms-flow-api/tests/unit/services/test_form_process_mapper.py
forms-flow-api/tests/unit/utils/test_logging.py
forms-flow-api/tests/utilities/base_test.py
forms-flow-api/tests/utils/test_logging.py

Changed user role mapping to group mapping

---

forms-flow-api/src/formsflow_api/constants/__init__.py
forms-flow-api/src/formsflow_api/services/factory/keycloak_group_service.py

JIRA: 
https://aottech.atlassian.net/browse/FWF-3403
Error handling when role mapping fails when group creation

Feature/fwf 3403 Error handling role mapping fails when group creation

---

forms-flow-web/src/components/PrivateRoute.jsx
forms-flow-web/src/modules/userDetailReducer.js

JIRA: https://aottech.atlassian.net/browse/FWF-3414

FWF-3414 [bugfix] fixed default language selection

---

forms-flow-web/src/components/Form/constants/FormTable.js

JIRA: https://aottech.atlassian.net/browse/FWF-3502
1. restricted designer action instead of view the data

FWF:3502 [bugfix] Fixed view design permission in form table

---

forms-flow-api/src/formsflow_api/resources/authorization.py

JIRA:  https://aottech.atlassian.net/browse/FWF-3499

FWF:3499 [bugfix] fixed form submission in permission matrix

---

forms-flow-api/src/formsflow_api/resources/user.py

JIRA: https://aottech.atlassian.net/browse/FWF-3509
1. Removed role checking in this /locale endpoint because all users need to update their locale

FWF:3509 [bugfix] fixed /locale authorization

---

forms-flow-web/src/components/BaseRouting.jsx
forms-flow-web/src/components/Form/List.js
forms-flow-web/src/components/Form/List.scss
forms-flow-web/src/components/Form/constants/FormTable.js

Designer-form tabel basic design

FWF-3459:[Feature]-designer-tabel design

---

forms-flow-api-utils/src/formsflow_api_utils/services/external/formio.py

JIRA: 
Added formio get form by id endpoint to api utils for EPD

Added formio get form by id endpoint to api utils for EPD

---

forms-flow-api/src/formsflow_api/resources/application.py
forms-flow-api/src/formsflow_api/resources/dashboards.py
forms-flow-api/src/formsflow_api/resources/user.py
forms-flow-api/tests/docker/realms/forms-flow-ai-realm.json
forms-flow-api/tests/unit/api/test_anonymous_application.py
forms-flow-api/tests/unit/api/test_application.py
forms-flow-api/tests/unit/api/test_application_history.py
forms-flow-api/tests/unit/api/test_authorization.py
forms-flow-api/tests/unit/api/test_dashboards.py
forms-flow-api/tests/unit/api/test_draft.py
forms-flow-api/tests/unit/api/test_filter.py
forms-flow-api/tests/unit/api/test_form_embed.py
forms-flow-api/tests/unit/api/test_form_process_mapper.py
forms-flow-api/tests/unit/api/test_formio.py
forms-flow-api/tests/unit/api/test_metrics.py
forms-flow-api/tests/unit/api/test_user.py

JIRA: 
https://aottech.atlassian.net/browse/FWF-3472
Test case updates  permission matrix

FWF-3472: [Feature] Test case updates permission matrix

---

forms-flow-api/src/formsflow_api/services/factory/keycloak_group_service.py
forms-flow-idm/realm-exports/Multi tenant realm.json

JIRA: 
https://aottech.atlassian.net/browse/FWF-3458
- List only tenant groups
- Added camunda-admin group to service-account user in the multitenant realm

🐛 Bugfix/fwf 3458 List tenant groups

---

forms-flow-web/src/components/ServiceFlow/list/sort/CreateNewFilter.js

JIRA: https://aottech.atlassian.net/browse/FWF-3450

FWF-3450:[Feature]-replaced the position of created by

---

forms-flow-api/src/formsflow_api/resources/authorization.py
forms-flow-api/src/formsflow_api/resources/form_process_mapper.py

Fixed designer view

---

forms-flow-api-utils/src/formsflow_api_utils/utils/auth.py
forms-flow-api/src/formsflow_api/resources/form_process_mapper.py
forms-flow-api/src/formsflow_api/services/factory/keycloak_group_service.py

Fixed designer view and added new function in utils

---

forms-flow-web/src/components/Form/Item/View.js
forms-flow-web/src/helper/helper.js

JIRA: https://aottech.atlassian.net/browse/FWF-3255
1.Fixed showing form not published issue

FWF-3255:[BUGFIX] Fixed showing form not published issue

---

forms-flow-api/requirements.txt
forms-flow-api/requirements/prod.txt
forms-flow-api/src/formsflow_api/resources/application.py

JIRA: 
draft submission fix trial

updated auth method for submission

---

forms-flow-web/src/components/ServiceFlow/list/sort/CreateNewFilter.js

JIRA: https://aottech.atlassian.net/browse/FWF-3523

FWF-3523 [bugfix] fixed Redirecting to task page

---

.github/workflows/forms-flow-api-cd.yml
.github/workflows/forms-flow-api-ci.yml
.github/workflows/forms-flow-bpm-cd.yml
.github/workflows/forms-flow-data-analysis-api-cd.yml
.github/workflows/forms-flow-documents-cd.yml
.github/workflows/forms-flow-root-config-cd.yml
.github/workflows/forms-flow-web-cd.yml
VERSION
deployment/docker/docker-compose.yml
deployment/docker/sample.env
forms-flow-api-utils/setup.py
forms-flow-api/requirements.txt
forms-flow-api/requirements/prod.txt
forms-flow-api/setup.cfg
forms-flow-bpm/forms-flow-bpm-camunda/pom.xml
forms-flow-bpm/forms-flow-bpm-utils/pom.xml
forms-flow-bpm/pom-default.xml
forms-flow-bpm/pom.xml
forms-flow-documents/setup.cfg
forms-flow-forms/docker-compose.yml
forms-flow-web-root-config/docker-compose.yml
forms-flow-web-root-config/sample.env
forms-flow-web-root-config/src/index.ejs
forms-flow-web/package.json
jobs/sentiment-analysis/setup.cfg

Modified version from 6.1.0-alpha to 7.0.0-alpha

---

forms-flow-web/src/apiManager/services/bpmTaskServices.js

Fixed bug in user assigne list in task header

---

forms-flow-documents/src/formsflow_documents/resources/pdf.py
forms-flow-documents/tests/utilities/base_test.py

JIRA: 
https://aottech.atlassian.net/browse/FWF-3539
Export pdf permission matrix changes

FWF-3539: [Bugfix] Export pdf permission matrix changes

---

forms-flow-idm/keycloak/imports/formsflow-ai-realm.json

JIRA: 
https://aottech.atlassian.net/browse/FWF-3541
- Added description to default groups
- Added view_tasks, manage_tasks, view_filters permissions to approver and clerk

FWF-3541: [Feature] Default group import changes

---

forms-flow-web/src/components/Form/FormOperations/FormOperations.js
forms-flow-web/src/components/Form/Item/Submission/List.js
forms-flow-web/src/components/Form/Steps/PreviewStepper.js

JIRA: https://aottech.atlassian.net/browse/FWF-3537

FWF-3537 [bugfix] tenant key fix in RBAC setting

---

forms-flow-api/src/formsflow_api/services/external/keycloak.py
forms-flow-api/src/formsflow_api/services/factory/keycloak_client_service.py
forms-flow-api/src/formsflow_api/services/factory/keycloak_group_service.py

JIRA: https://aottech.atlassian.net/browse/FWF-3546

FWF-3546 [bugfix] fixed groups listing in dashboard based on the permission

---

forms-flow-api/src/formsflow_api/services/factory/keycloak_group_service.py

JIRA: 
https://aottech.atlassian.net/browse/FWF-3562
Fixed user list displays other tenant roles
`Issue`
Fixed

🐛 FWF-3562: [BugFix] Fixed user list display other tenant roles

---

forms-flow-web/src/components/ServiceFlow/list/sort/CreateNewFilter.js
forms-flow-web/src/helper/helper.js

https://aottech.atlassian.net/browse/FWF-3536
JIRA: 

updated the multi-tenancy  condition

---

forms-flow-api/src/formsflow_api/services/factory/keycloak_group_service.py

JIRA: 
Fix users list endpoint not showing all users
`Issue`
`Fix`

🐛 FWF-3563: [BugFix] Fix users list endpoint not showing all users

---

forms-flow-web-root-config/docker-compose.yml
forms-flow-web-root-config/sample.env

JIRA: 
keycloak upgrade testing

test for keycloak upgrade

---

forms-flow-web/src/components/ServiceFlow/filter/ServiceTaskFilterListDropDown.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-3548

updated role based condition for filters

---

forms-flow-idm/keycloak/docker-compose.yml

JIRA: 
https://aottech.atlassian.net/browse/FWF-3519

⬆️ upgraded keycloak version to 25.x.x

---

forms-flow-web/src/components/Application/List.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-3577

added draft enable for create submission user

---

forms-flow-web/src/components/Form/index.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-3587

updated permission for main route

---

forms-flow-web/src/components/PrivateRoute.jsx

JIRA: 
https://aottech.atlassian.net/browse/FWF-3579

dashboard seperete route

---

forms-flow-web-root-config/docker-compose.yml
forms-flow-web-root-config/sample.env

JIRA: 
Changed service URL in webroot config

[Bugfix]: Changed service url in webroot config

---

forms-flow-api/src/formsflow_api/resources/roles.py

JIRA: 
https://aottech.atlassian.net/browse/FWF-3600
Fixed roles API fail with view_designs permission

FWF-3600: [Bugfix] Fix roles api fail with view_designs permission

---

forms-flow-idm/keycloak/docker-compose.yml

upgraded keycloak 24.0.5

---

forms-flow-api/src/formsflow_api/services/form_process_mapper.py
forms-flow-api/tests/unit/api/test_form_process_mapper.py

…lows
JIRA: 
https://aottech.atlassian.net/browse/FWF-3488
Commented out call to capture subforms, subworkflows & dmns

FWF-3488: [Modified] Commented out call to capture subforms, subworkflows & dmns

---

forms-flow-web/src/components/Form/constants/FormTable.js

JIRA: https://aottech.atlassian.net/browse/FWF-3459

FWF-3459:[Feature]-Expand Description in Designer Listing Page

---

forms-flow-bpm/forms-flow-bpm-camunda/pom.xml
forms-flow-bpm/forms-flow-bpm-camunda/src/main/java/org/camunda/bpm/extension/keycloak/sso/KeycloakAuthenticationProvider.java
forms-flow-bpm/forms-flow-bpm-camunda/src/main/java/org/camunda/bpm/extension/keycloak/sso/OAuth2LoginSecurityConfig.java
forms-flow-bpm/forms-flow-bpm-camunda/src/main/resources/META-INF/resources/webjars/camunda/app/admin/scripts/config.js
forms-flow-bpm/forms-flow-bpm-camunda/src/main/resources/META-INF/resources/webjars/camunda/app/cockpit/scripts/config.js
forms-flow-bpm/forms-flow-bpm-camunda/src/main/resources/META-INF/resources/webjars/camunda/app/tasklist/scripts/config.js
forms-flow-bpm/pom.xml

JIRA: https://aottech.atlassian.net/browse/FWF-3599
- Commented out JWT Auth code to force server side auth
- Updated code to work with keycloak 25

Updating camunda and camundaKeycloak version

---

forms-flow-web/src/components/PrivateRoute.jsx

https://aottech.atlassian.net/browse/FWF-3587
JIRA: 

fix main route for view submision

---

forms-flow-api-utils/src/formsflow_api_utils/utils/enums.py
forms-flow-api-utils/src/formsflow_api_utils/utils/util.py
forms-flow-api/src/formsflow_api/models/form_process_mapper.py
forms-flow-api/src/formsflow_api/resources/form_process_mapper.py
forms-flow-api/src/formsflow_api/schemas/form_process_mapper.py
forms-flow-api/src/formsflow_api/services/form_process_mapper.py
forms-flow-api/tests/unit/api/test_form_process_mapper.py
forms-flow-api/tests/unit/services/test_form_process_mapper.py
forms-flow-web/src/apiManager/services/bpmFormServices.js

JIRA: https://aottech.atlassian.net/browse/FWF-3582
1. Added search parameter instead formName and this will search the token in formName and description 
2. Added sorting for 
- title
- visibility
- status
- last modified date
`http://{your_ip_address}/form?pageNo=1&limit=5&sortBy=modified,status,formName&sortOrder=asc,desc,asc&search=test`

FWF 3582 [Feature] Added search paramer and removed formName to search form and upgraded sorting parameter with multiple values

---

forms-flow-idm/keycloak/docker-compose.yml

JIRA: 
https://aottech.atlassian.net/browse/FWF-3519

updated keycloak version to 25.0.4

---

forms-flow-api-utils/src/formsflow_api_utils/services/external/formio.py

JIRA: 
https://aottech.atlassian.net/browse/FWF-3621
Added new formio search endpoint to api utils

FWF-3621: [Added] Added new formio search endpoint to api utils

---

forms-flow-web/src/components/PrivateRoute.jsx

JIRA: https://aottech.atlassian.net/browse/FWF-3612
1.Updated path for BASE_ROUTE with permissions

FWF:3612 [Bugfix] Fixed Access denied issue

---

forms-flow-web/src/components/Modals/ConfirmModal.js

JIRA: https://aottech.atlassian.net/browse/FWF-3611
pull request

FWF-3611:[Feature]-Reusable Confirm Modal

---

.github/workflows/forms-flow-bpm-cd.yml
.github/workflows/forms-flow-web-cd.yml

JIRA: 
Issue Type: [BUG/ FEATURE](https://aottech.atlassian.net/browse/FWF-3592)

ZAP changes for report generation

---

forms-flow-web/src/components/CustomComponents/Search.js

JIRA: https://aottech.atlassian.net/browse/FWF-3534

FWF-3534: [Feature] Updated search with added icons

---

forms-flow-web/src/components/CustomComponents/FormInput.js

JIRA: https://aottech.atlassian.net/browse/FWF-3555
1.Added input text box 
Input box with Icon
Inputbox with errortext
Input box filled

FWF:3555[Feature] Create custom inputbox

---

forms-flow-api/src/formsflow_api/models/form_process_mapper.py
forms-flow-api/src/formsflow_api/resources/form_process_mapper.py

JIRA: https://aottech.atlassian.net/browse/FWF-3582
1. Removed unwanted space form the search list

Removed empty space from for search

---

forms-flow-web/package-lock.json
forms-flow-web/package.json
forms-flow-web/src/_tests_/test-redux-states/redux-state-sample.js
forms-flow-web/src/components/Application/ViewApplication.js
forms-flow-web/src/components/Draft/Edit.js
forms-flow-web/src/components/Draft/EditDraft.js
forms-flow-web/src/components/Draft/ViewDraft.js
forms-flow-web/src/components/Form/Create.js
forms-flow-web/src/components/Form/Item/Edit.js
forms-flow-web/src/components/Form/Item/Preview.js
forms-flow-web/src/components/Form/Item/Submission/Item/Edit.js
forms-flow-web/src/components/Form/Item/Submission/Item/View.js
forms-flow-web/src/components/Form/Item/Submission/Item/index.js
forms-flow-web/src/components/Form/Item/Submission/List.js
forms-flow-web/src/components/Form/Item/View.js
forms-flow-web/src/components/Form/Item/index.js
forms-flow-web/src/components/Form/List.js
forms-flow-web/src/components/Form/Stepper.js
forms-flow-web/src/components/Form/Steps/WorkFlow.js
forms-flow-web/src/components/PublicRoute.jsx
forms-flow-web/src/components/ServiceFlow/details/ServiceTaskDetails.js
forms-flow-web/src/components/ServiceFlow/list/ServiceTaskListViewDetails.js
forms-flow-web/src/constants/applicationComponent.js
forms-flow-web/src/modules/index.js
forms-flow-web/src/single-spa-index.js

JIRA: https://aottech.atlassian.net/browse/FWF-3425 
Replaced "formiojs" with "@arun-s-aot/formiojs",
Replaced "react-formio" with "@arun-s-aot/formio-react"
Removed "formsflow-formio-custom-elements" package for the tim being as there is conflict in formiojs versions.
Video link : https://jam.dev/c/e9804b4c-3b81-4144-8f4f-732b0124a323 
For now removed  "formsflow-formio-custom-elements"  from package list and commented import of "formsflow-formio-custom-elements/dist/customformio-ex" from single-spa-index as there is version conflict. Need to include it onn a later stage . 
Packages used : 
https://www.npmjs.com/package/@arun-s-aot/formio-react
https://www.npmjs.com/package/@arun-s-aot/formiojs

FWF-3425 [Feature] Conditional chain updated implementation

---

forms-flow-api/src/formsflow_api/models/form_process_mapper.py
forms-flow-api/src/formsflow_api/resources/form_process_mapper.py
forms-flow-api/src/formsflow_api/schemas/import_support.py
forms-flow-api/src/formsflow_api/services/form_process_mapper.py
forms-flow-api/src/formsflow_api/services/import_support.py
forms-flow-api/tests/unit/api/test_import_support.py

JIRA: 
- Import form in edit import
- Form Validation in edit import
- Moved code from the from-process-mapper resource file to service for reuse.
- If the selected workflow version is not specified, update the version based on process status.
- Fetched version for form

FWF-3490: [Featue] Added edit import

---

forms-flow-api/src/formsflow_api/models/process.py
forms-flow-api/src/formsflow_api/resources/process.py
forms-flow-api/src/formsflow_api/schemas/__init__.py
forms-flow-api/src/formsflow_api/schemas/process_history_logs.py
forms-flow-api/src/formsflow_api/services/process.py
forms-flow-api/tests/unit/api/test_process.py

JIRA: 
https://aottech.atlassian.net/browse/FWF-3580
[
{
"id": "3",
"processName": "test1",
"createdBy": "formsflow-designer",
"created": "2024-09-11 04:24:37.210723",
"majorVersion": 3,
"minorVersion": 0
},
{
"id": "2",
"processName": "test1",
"createdBy": "formsflow-designer",
"created": "2024-09-11 04:24:28.593201",
"majorVersion": 2,
"minorVersion": 0
},
{
"id": "1",
"processName": "test1",
"createdBy": "formsflow-designer",
"created": "2024-09-11 04:24:05.186678",
"majorVersion": 1,
"minorVersion": 0
}
]

Api to get process versions

---

forms-flow-web/package-lock.json
forms-flow-web/package.json
forms-flow-web/src/_tests_/test-redux-states/redux-state-sample.js
forms-flow-web/src/components/Application/ViewApplication.js
forms-flow-web/src/components/Draft/Edit.js
forms-flow-web/src/components/Draft/EditDraft.js
forms-flow-web/src/components/Draft/ViewDraft.js
forms-flow-web/src/components/Form/Create.js
forms-flow-web/src/components/Form/Item/Edit.js
forms-flow-web/src/components/Form/Item/Preview.js
forms-flow-web/src/components/Form/Item/Submission/Item/Edit.js
forms-flow-web/src/components/Form/Item/Submission/Item/View.js
forms-flow-web/src/components/Form/Item/Submission/Item/index.js
forms-flow-web/src/components/Form/Item/Submission/List.js
forms-flow-web/src/components/Form/Item/View.js
forms-flow-web/src/components/Form/Item/index.js
forms-flow-web/src/components/Form/List.js
forms-flow-web/src/components/Form/Stepper.js
forms-flow-web/src/components/Form/Steps/WorkFlow.js
forms-flow-web/src/components/PublicRoute.jsx
forms-flow-web/src/components/ServiceFlow/details/ServiceTaskDetails.js
forms-flow-web/src/components/ServiceFlow/list/ServiceTaskListViewDetails.js
forms-flow-web/src/constants/applicationComponent.js
forms-flow-web/src/modules/index.js
forms-flow-web/src/single-spa-index.js

JIRA: https://aottech.atlassian.net/browse/FWF-3658
Move formiojs, reactformio package to organization npm account

FWF-3658 [Feature] : Move formiojs, reactformio package to organization npm account 

---

forms-flow-api/src/formsflow_api/schemas/form_history_logs.py
forms-flow-api/tests/unit/api/test_form_process_mapper.py

JIRA: 
https://aottech.atlassian.net/browse/FWF-3656
[
{
"id": "6",
"formId": "66e946c1092e00ed89da89da",
"createdBy": "formsflow-designer",
"created": "2024-09-17 09:07:33.580831",
"changeLog": {
"cloned_form_id": "66e946d5092e00ed89da8a28",
"new_version": false
},
"majorVersion": 1,
"minorVersion": 3,
"version": "1.3",
"isMajor": false
},
{
"id": "5",
"formId": "66e946c1092e00ed89da89da",
"createdBy": "formsflow-designer",
"created": "2024-09-17 09:07:30.426834",
"changeLog": {
"cloned_form_id": "66e946d2092e00ed89da8a15",
"new_version": false
},
"majorVersion": 1,
"minorVersion": 2,
"version": "1.2",
"isMajor": false
},
{
"id": "4",
"formId": "66e946c1092e00ed89da89da",
"createdBy": "formsflow-designer",
"created": "2024-09-17 09:07:27.230971",
"changeLog": { …

added isMajor field

---

.github/workflows/forms-flow-api-ci.yml
.github/workflows/forms-flow-documents-ci.yml

JIRA: 
Updated python versions in api ci

 Updated python versions in api ci

---

forms-flow-api/src/formsflow_api/constants/__init__.py
forms-flow-api/src/formsflow_api/models/application.py
forms-flow-api/src/formsflow_api/models/authorization.py
forms-flow-api/src/formsflow_api/models/draft.py
forms-flow-api/src/formsflow_api/models/filter.py
forms-flow-api/src/formsflow_api/models/form_history_logs.py
forms-flow-api/src/formsflow_api/models/form_process_mapper.py
forms-flow-api/src/formsflow_api/models/process.py
forms-flow-api/src/formsflow_api/resources/form_process_mapper.py
forms-flow-api/src/formsflow_api/resources/process.py
forms-flow-api/src/formsflow_api/schemas/__init__.py
forms-flow-api/src/formsflow_api/schemas/form_history_logs.py
forms-flow-api/src/formsflow_api/schemas/process_history_logs.py
forms-flow-api/src/formsflow_api/services/application.py
forms-flow-api/src/formsflow_api/services/external/base_bpm.py
forms-flow-api/src/formsflow_api/services/external/keycloak.py
forms-flow-api/src/formsflow_api/services/factory/keycloak_admin.py
forms-flow-api/src/formsflow_api/services/factory/keycloak_group_service.py
forms-flow-api/src/formsflow_api/services/form_history_logs.py
forms-flow-api/src/formsflow_api/services/form_process_mapper.py
forms-flow-api/src/formsflow_api/services/import_support.py
forms-flow-api/src/formsflow_api/services/process.py
forms-flow-api/tests/unit/api/test_anonymous_application.py
forms-flow-api/tests/unit/api/test_form_process_mapper.py
forms-flow-api/tests/unit/api/test_process.py

JIRA: 
https://aottech.atlassian.net/browse/FWF-3688
https://aottech.atlassian.net/browse/FWF-3687
1. Changes to process history endpoint
- Add pagination to the process history API endpoint
- Added field processType, isMajor in response
2. Added pagination to the form history  endpoint
3. Pylint fixes

FWF-3687: [Feature] Updates on process & form history endpoints

---

.github/workflows/zap-scan.yml

This workflow automates building and deploying artifacts to S3, performing a ZAP security scan, creating Jira issues on vulnerability detection, and notifying the team via Google Chat.
- Integrated build and deployment steps
- Implemented ZAP security scanning with S3 upload
- Added Jira issue creation on scan failures
- Included team notification on critical issues

Added ZAP and JIRA Integration Git action

---

forms-flow-api/src/formsflow_api/resources/process.py
forms-flow-api/src/formsflow_api/services/import_support.py
forms-flow-api/src/formsflow_api/services/process.py
forms-flow-api/tests/unit/api/test_import_support.py

JIRA: 
https://aottech.atlassian.net/browse/FWF-3705
- Updated import success response with formId
- Changed process details using process_key instead of id
Pylint Fix available in this PR: https://github.com/AOT-Technologies/forms-flow-ai/pull/2236

FWF-3705: [Modified] Changed process details using process_key instead of id

---

forms-flow-web/package-lock.json
forms-flow-web/package.json

JIRA: https://aottech.atlassian.net/browse/FWF-3685
Issue with dropdown value persisitnng in logic tab of formiocomponent
Filtered the components in 'form component' section in settings modal

FWF-3685 [Bugfix] : Issue fix for conditional chains bugs reported

---

forms-flow-web/src/components/CustomComponents/settingsModal.js
forms-flow-web/src/components/Form/Item/Edit.js

JIRA: 
* Added RBAC changes
* Wizard changes
* Anonymous changes

FWF - 3542 Added settings functionalities

---

forms-flow-api/src/formsflow_api/services/form_process_mapper.py

JIRA: 
Included form major, minor versions to form by formid api response

[Feature]: Included form major, minor versions to form by formid api response

---

forms-flow-api/requirements.txt
forms-flow-api/requirements/prod.txt
forms-flow-api/src/formsflow_api/models/form_process_mapper.py

JIRA: 
Fix the form loading issue for the user with create submission permission
- add_sort_filter is moved to utils but its reference found to cls
Issue
After Fix

FWF-3751: [Bugfix] Fix form loading issue for user with create submission

---

forms-flow-web/src/apiManager/services/processServices.js
forms-flow-web/src/components/Form/Item/Edit.js

JIRA: 
* Fixed formId undefined issue
* Fixed anonymous null issue

FWF-3542: [BugFix] Fixed formId and anonymous issues on settings save

---

forms-flow-web/src/apiManager/endpoints/index.js
forms-flow-web/src/apiManager/services/FormServices.js
forms-flow-web/src/components/Form/Item/Edit.js

JIRA: https://aottech.atlassian.net/browse/FWF-3739
Save layout, Publish API integration

FWF-3739: [Feature] - Save and Publish Layout

---

forms-flow-api/src/formsflow_api/resources/form_process_mapper.py
forms-flow-api/src/formsflow_api/services/form_process_mapper.py

JIRA: 
Added form version to mapper update api response

Added form version to mapper update api response

---

forms-flow-web/src/components/Form/Item/Edit.js
forms-flow-web/src/components/Form/List.js

Issue with description not saving in form build and form duplication fixed. Error with form-design PUT fixed
JIRA: 
Issue with description not saving in form build and form duplication fixed. 
Error with form-design PUT fixed

[Bugfix] : Issue with description not saving in form build and form duplication fixed. Error with form-design PUT fixed

---

forms-flow-web/src/components/Form/Item/Edit.js

updated payload of name

---

forms-flow-web/src/components/CustomComponents/settingsModal.js

JIRA: 
* Added minRows in settings' text area

FWF-3542: [BugFix] Added minRows in settings' text area

---

forms-flow-web/src/components/Form/Item/Edit.js

[FWF-3757: Added form title change after update, fixed pathname and anonymous url issues]

---

forms-flow-documents/requirements.txt

JIRA: 
https://aottech.atlassian.net/browse/FWF-3764
Added missing package to documents API requirements

FWF-3764: [Bugfix] Fix documents api restart issue

---

forms-flow-api/src/formsflow_api/models/process.py
forms-flow-api/src/formsflow_api/schemas/process_history_logs.py
forms-flow-api/src/formsflow_api/services/process.py

JIRA: 
https://aottech.atlassian.net/browse/FWF-3766
https://aottech.atlassian.net/browse/FWF-3768
1. added published on Process history 
2. fixed process listing bug

FWF-3766 and FWF-3768 added published on process History and fixed processListing

---

forms-flow-web/src/helper/processHelper.js

JIRA: https://aottech.atlassian.net/browse/FWF-3770

Fixed compare two xml data

---

.github/workflows/forms-flow-web-ci.yml

Reverts AOT-Technologies/forms-flow-ai#2286

Revert "Update forms-flow-web-ci.yml"

---

forms-flow-web/src/components/Form/Item/Edit.js
forms-flow-web/src/components/Modals/NewVersionModal.js

JIRA: https://aottech.atlassian.net/browse/FWF-3739
Save and publish

FWF-3739:[Feature]- Save and publish. with confirmation modals.

---

forms-flow-api/src/formsflow_api/constants/__init__.py
forms-flow-api/src/formsflow_api/models/form_history_logs.py
forms-flow-api/src/formsflow_api/models/process.py
forms-flow-api/src/formsflow_api/resources/process.py
forms-flow-api/src/formsflow_api/schemas/form_history_logs.py
forms-flow-api/src/formsflow_api/services/form_history_logs.py
forms-flow-api/src/formsflow_api/services/process.py
forms-flow-api/tests/unit/api/test_process.py

JIRA: 
https://aottech.atlassian.net/browse/FWF-3767
https://aottech.atlassian.net/browse/FWF-3842
https://aottech.atlassian.net/browse/FWF-3838
- Added 'published on' field in Form History
- API changes to get process by ID to support revert from process history
- Updated `process/<process-key>` API to `process/<process-id>`
- Added new API `/process/key/<process-key>` to get process by process key.
- Fixed process listing with multiple items on the latest version
- Added validation to prevent updating a process with processId which is published.

[Feature] Added published on form history, Changes in process API

---

forms-flow-web/src/components/Form/EditForm/FormEdit.js

JIRA: 
1. Added a ref to handle the initial animation

Bugfix: fixed animation render in intial stage on form edit tab

---

forms-flow-web/src/apiManager/endpoints/index.js

JIRA: 
updated the api service call

updated api service

---

forms-flow-api/src/formsflow_api/models/process.py

JIRA: 
Update  latest_version_by_key method to get latest row

Update  latest_version_by_key method to get latest row

---

forms-flow-web/src/components/Modals/ExportDiagrams.js

JIRA: 
sonarcube fix for export diagram

updated the sonarcube fix for export diagram

---

forms-flow-web/src/components/Form/EditForm/FlowEdit.js
forms-flow-web/src/components/Form/EditForm/FormEdit.js
forms-flow-web/src/components/Modeler/constants/bpmnModelerConstants.js
forms-flow-web/src/helper/processHelper.js

JIRA: 
1. code optimized: validateProcess moved to process Helper file
2. fixed the flow save function after unpublish
3. disable the save flow button is the form is published

 Bugfixed: flow save after unpublish and linterrors not catching properly

---

forms-flow-web/src/apiManager/services/FormServices.js
forms-flow-web/src/components/CustomComponents/MultiSelect.js
forms-flow-web/src/components/Form/EditForm/FormSettings.js

JIRA: 
Added validations for form name and path, removed placeholder

FWF-3757: [Feature] Added validations for form name and path in settings, removed placeholder

---

forms-flow-api-utils/src/formsflow_api_utils/exceptions/__init__.py
forms-flow-api/requirements.txt
forms-flow-api/requirements/prod.txt
forms-flow-api/src/formsflow_api/constants/__init__.py
forms-flow-api/src/formsflow_api/models/process.py
forms-flow-api/src/formsflow_api/services/form_process_mapper.py
forms-flow-api/src/formsflow_api/services/import_support.py
forms-flow-api/src/formsflow_api/services/process.py
forms-flow-api/tests/unit/api/test_form_process_mapper.py

JIRA: 
https://aottech.atlassian.net/browse/FWF-3843
https://aottech.atlassian.net/browse/FWF-3769
- Added form name, path, and title validation
- Fixed issues in capturing process version
- Code refactoring

Bugfix: Added Form validation & changes on capturing process version 

---

forms-flow-web/src/components/Form/EditForm/FlowEdit.js
forms-flow-web/src/components/Form/List.js

JIRA: https://aottech.atlassian.net/browse/FWF-3820
1. removed default component from form creation 
2. optimized code

FWF[3820] bugifx : submit button added in default form creation

---

.github/workflows/pr-notification.yml

Updated PR notification to google chat

---

forms-flow-web/src/components/CustomComponents/MultiSelect.js

Added common parent class for multi-select

---

forms-flow-web/src/components/Form/EditForm/FormSettings.js
forms-flow-web/src/components/Form/List.js
forms-flow-web/src/components/Modals/ActionModal.js
forms-flow-web/src/components/Modals/ImportModal.js
forms-flow-web/src/components/Modeler/DecisionTable.js
forms-flow-web/src/components/Modeler/SubFlowTable.js
forms-flow-web/src/components/Modeler/index.js
forms-flow-web/src/components/PrivateRoute.jsx

JIRA: 
1. Added custom info component and Updated screen with info component
2. Corrected decision table route

feature/FWF:3765-Added info component

---

forms-flow-web/src/components/Form/EditForm/index.js
forms-flow-web/src/components/Form/List.js

JIRA: https://aottech.atlassian.net/browse/FWF-3864

FWF-3864 [bugfix] fixed status not retaining of published forms

---

forms-flow-web/src/components/Modeler/DecisionTable.js
forms-flow-web/src/components/Modeler/SubFlowTable.js

JIRA: https://aottech.atlassian.net/browse/FWF-3703
build modal added in subflow table and decision table

build modal added in subflow table and decision table

---

forms-flow-web/src/constants/applicationComponent.js

JIRA: https://aottech.atlassian.net/browse/FWF-3868

Renamed application id and status to submission id and status

---

forms-flow-api/src/formsflow_api/services/form_process_mapper.py

JIRA: 
https://aottech.atlassian.net/browse/FWF-3908
- Assign default design permissions to the user who created the form upon its creation.

FWF-3908: Fix form design permission issue on new form creation

---

forms-flow-web/src/components/Form/EditForm/FormEdit.js
forms-flow-web/src/helper/helper.js

JIRA: https://aottech.atlassian.net/browse/FWF-3875

Fixed save form function: component changes tracking and moved to helper  file

---

forms-flow-web/src/components/Form/List.js

JIRA: https://aottech.atlassian.net/browse/FWF-3911

fixed save button api call

---

forms-flow-web/src/components/Form/EditForm/FormEdit.js

Fixed duplicate form twice click

---

forms-flow-api/docker-compose.yml
forms-flow-documents/docker-compose.yml
forms-flow-documents/sample.env
forms-flow-redis/docker-compose.yml

JIRA: 
https://aottech.atlassian.net/browse/FWF-3476

New docker-compose file for Redis: Resolving port allocated issue

---

forms-flow-web/src/components/Form/EditForm/FlowEdit.js
forms-flow-web/src/components/Form/EditForm/FormEdit.js
forms-flow-web/src/components/Modeler/ProcessCreateEdit.js

JIRA:  https://aottech.atlassian.net/browse/FWF-3913

Disabled revert button on Live

---

forms-flow-web/src/components/Application/ApplicationTable.js
forms-flow-web/src/components/Draft/DraftTable.js
forms-flow-web/src/components/Form/constants/ClientTable.js

JIRA: https://aottech.atlassian.net/browse/FWF-3945
* Fixed pagination issues in submission, draft, client tables

FWF-3945: [Bugfix] Resolved pagination issues in submission,draft,client tables

---

forms-flow-web/src/components/Form/EditForm/FormEdit.js
forms-flow-web/src/components/Modals/ExportDiagrams.js
forms-flow-web/src/components/Modals/ExportModal.js
forms-flow-web/src/components/Modeler/ProcessCreateEdit.js

JIRA: https://aottech.atlassian.net/browse/FWF-3899

FWF 3899 [ bugifx ] set form name for file name

---

forms-flow-web/src/components/Form/List.scss
forms-flow-web/src/components/Form/constants/FormTable.js
forms-flow-web/src/components/Modeler/DecisionTable.js
forms-flow-web/src/components/Modeler/SubFlowTable.js

JIRA: https://aottech.atlassian.net/browse/FWF-3879
1. Added No records page

FWF-9879:[Feature]Added no records page

---

forms-flow-web/src/components/Modeler/ProcessCreateEdit.js

bugfix publish on duplicate

---

forms-flow-web/src/components/PrivateRoute.jsx
forms-flow-web/src/constants/applicationComponent.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-3738

 adding hidden fields

---

forms-flow-api/src/formsflow_api/resources/application_history.py
forms-flow-api/src/formsflow_api/resources/process.py

JIRA: 
https://aottech.atlassian.net/browse/FWF-3910
- Authorize application history API for users with VIEW_TASKS 
- Authorize get by process key API for users with VIEW_SUBMISSIONS, VIEW_TASKS
User with view submissions permissions
Reviewer with view task permission

FWF-3910: [Bugfix] Fix permission matrix API authorize issues

---

forms-flow-web/src/components/Application/ApplicationTable.js
forms-flow-web/src/components/Draft/DraftTable.js
forms-flow-web/src/components/Form/constants/ClientTable.js

JIRA: 
* Height issue fixed in table

FWF-3816: [Bugfix] Height style fix

---

forms-flow-api/src/formsflow_api/constants/__init__.py
forms-flow-api/src/formsflow_api/services/form_process_mapper.py

JIRA: 
- Restrict form deletion with submissions on the API side

FWF-3873: [Bugfix] Restrict form deletion with submissions on API side

---

forms-flow-web/src/components/Form/EditForm/FormSettings.js
forms-flow-web/src/components/Form/constants/ClientTable.js

JIRA: 
* Added reusable search component to client table
* Updated form name and path validation only with onBlur in settings

Added search to client table, update validation

---

forms-flow-web/src/components/Form/EditForm/FormEdit.js

JIRA: 
Fixed routing issue from form edit to listing

[BUGFIX] Fixed routing issue from form edit to listing

---

forms-flow-web/src/components/Form/EditForm/FlowEdit.js
forms-flow-web/src/components/Form/EditForm/FormEdit.js
forms-flow-web/src/components/Modeler/Editors/BpmnEditor/BpmEditor.js
forms-flow-web/src/components/Modeler/Editors/DmnEditor/DmnEditor.js
forms-flow-web/src/components/Modeler/ProcessCreateEdit.js

Fixed if workflow reverted then need to show saveflow as enabled

---

forms-flow-web/src/components/Form/EditForm/FormEdit.js
forms-flow-web/src/components/ServiceFlow/list/sort/CreateNewFilter.js

JIRA: https://aottech.atlassian.net/browse/FWF-3971
The form was not being updated after importing it in create or edit page of form.

FWF-3971:[Feature] - Update imported forms' component in create or edit page.

---

forms-flow-web/src/components/Dashboard/Dashboard.js
forms-flow-web/src/components/Form/EditForm/FormEdit.js
forms-flow-web/src/components/Form/constants/ClientTable.js
forms-flow-web/src/components/ServiceFlow/list/sort/CreateNewFilter.js

JIRA: https://aottech.atlassian.net/browse/FWF-3922, 
* Added search to metrics
* Loading issue fixed

FWF-3932: Added search to metrics, loading added

---

forms-flow-bpm/forms-flow-bpm-camunda/src/main/java/org/camunda/bpm/extension/hooks/rest/service/impl/AdminRestServiceImpl.java

JIRA: 
- Checking authorization exists before creating new
- Changing the authorization to match default group (tenantkey-admin)

Checking authorization exists before creating new

---

forms-flow-web/src/components/Form/EditForm/FlowEdit.js
forms-flow-web/src/components/Form/EditForm/FormSettings.js
forms-flow-web/src/components/Modeler/Editors/Editor.scss

JIRA: https://aottech.atlassian.net/browse/FWF-3967
1.Added styles for bpmn container

bugfix/fwf-3697:Added ui corrections

---

forms-flow-web/src/components/Form/EditForm/FormEdit.js

JIRA:  https://aottech.atlassian.net/browse/FWF-3894
1. Fixed form component changes capturing for formchange and added confirmation for component delete

Fixed form component changes capturing for formchange and added confirmation for component delete

---

forms-flow-api/src/formsflow_api/services/form_process_mapper.py
forms-flow-api/src/formsflow_api/services/import_support.py
forms-flow-api/src/formsflow_api/services/process.py

JIRA: 
https://aottech.atlassian.net/browse/FWF-3972
Multitenant changes
- Added tenant-key prefix to path & name validation
- Form title validation is done on the mapper 
- Moved validate_form_title method to mapper service
alpha-tenant with testform1
Validate on beta-tenant
- [] Updated changelog

FWF-3972: [Bugfix] Multitenant form validation fix

---

forms-flow-web/src/components/Modeler/ProcessCreateEdit.js

JIRA: https://aottech.atlassian.net/browse/FWF-4017

Fixed unsaved changes showing on creation in subflow and dmn

---

forms-flow-web/src/components/Form/EditForm/FlowEdit.js
forms-flow-web/src/components/Modeler/ProcessCreateEdit.js
forms-flow-web/src/helper/processHelper.js

JIRA: https://aottech.atlassian.net/browse/FWF-4019
1. Optimized performance 
2. fixed attribute change not capture
3. fixed save button not disabled after non change save flow

Optimized performance and fixed bpmn xml compare issue

---

forms-flow-web/src/components/Form/EditForm/FlowEdit.js
forms-flow-web/src/components/Form/constants/FormTable.js
forms-flow-web/src/components/Modals/TaskVariableModal.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-4007
https://aottech.atlassian.net/browse/FWF-3964
1.Added applicationId and applicationStatus as default variables kin selected variables
2. Fixed style issue in form Table 
3.  Ignored specific components getting selected by its key and types

feature/fwf-4007:Added applicationId& applicationStatus as default task variable Ignored specific components getting selected

---

forms-flow-api/src/formsflow_api/schemas/form_process_mapper.py
forms-flow-api/src/formsflow_api/services/form_process_mapper.py
forms-flow-api/src/formsflow_api/services/import_support.py

JIRA: 
- mapper creation payload fixes
- Set the default value for who can we view submission to the creator of the form

[Bugfix]: Webapi mapper create payload fixes

---

forms-flow-web/src/components/Form/List.js
forms-flow-web/src/constants/applicationComponent.js

added default values

---

forms-flow-bpm/forms-flow-bpm-camunda/src/main/java/org/camunda/bpm/extension/hooks/listeners/data/FormProcessMappingData.java
forms-flow-bpm/forms-flow-bpm-camunda/src/test/java/org/camunda/bpm/extension/hooks/listeners/FormBPMFilteredDataPipelineListenerTest.java

JIRA: 
- Updated taskVariables param from taskVariable in the FormBPMFilteredDataPipelineListener fetch data
Issue
After fix

[Bugfix]: Update taskVariables param in form bpm filtered listener

---

deployment/docker/docker-compose.yml
forms-flow-api/docker-compose.yml
forms-flow-api/sample.env
forms-flow-api/src/formsflow_api/config.py
forms-flow-api/src/formsflow_api/constants/__init__.py
forms-flow-api/src/formsflow_api/services/external/admin.py
forms-flow-api/src/formsflow_api/services/form_process_mapper.py
forms-flow-api/src/formsflow_api/services/import_support.py

JIRA: 
https://aottech.atlassian.net/browse/FWF-4001
- Added form access on import
- Fix  fetch authorization by parent formId on export
- Prefix tenant key to form name & path on create form on import
- Code optimization on export

[Bug fix]  Added form access on import & export fixes

---

forms-flow-idm/migration/README.md
forms-flow-idm/migration/migrate-7.0.0.py
forms-flow-idm/migration/utils.py

JIRA: 
- FWF-3720: Updating permission migration for multi tenant setup

FWF-3720: Updating permission migration for multi tenant setup

---

.github/workflows/forms-flow-documents-cd.yml
forms-flow-documents/Dockerfile-ARM64

Reverts AOT-Technologies/forms-flow-ai#2399

Revert "CD Action change to push multi-arch images for documents-api"

---

forms-flow-web/src/constants/applicationComponent.js

Fixed unwatned data saving in submission

---

deployment/docker/sample.env
forms-flow-web-root-config/public/config/config.sample.js
forms-flow-web-root-config/sample.env

JIRA:  https://aottech.atlassian.net/browse/FWF-3992
Sample theming variables added

env update for custom theming

---

forms-flow-idm/keycloak/imports/formsflow-ai-realm.json
forms-flow-idm/realm-exports/Multi tenant realm.json

JIRA: 
https://aottech.atlassian.net/browse/FWF-4028

updated internationalization for multi and normal

---

forms-flow-web/src/components/Form/List.js

JIRA: 
updated import type in form listing page.

FWF-3971:[Feature] - Import type issue fix  in form listing page.

---

forms-flow-api/src/formsflow_api/models/application.py
forms-flow-api/src/formsflow_api/models/authorization.py
forms-flow-api/src/formsflow_api/resources/authorization.py
forms-flow-api/src/formsflow_api/services/authorization.py
forms-flow-web/src/apiManager/services/authorizationService.js
forms-flow-web/src/components/Form/Item/index.js

JIRA: https://aottech.atlassian.net/browse/FWF-4065

Fixed authorization for application and submission view

---

forms-flow-api-utils/src/formsflow_api_utils/utils/user_context.py

JIRA: 
https://aottech.atlassian.net/browse/FWF-4084
- Update group_or_roles to  return groups in multitenant

FWF-4084: Update group_or_roles to  return groups in multitenant

---

forms-flow-documents/requirements.txt

JIRA: 
- Included setuptools
-  selenium version change to 4.25.0
Error when setuptools missing
Error with selenium==4.27.1 on download pdf

[Bugfix]: Fix documents api build issue

---

forms-flow-web/src/apiManager/services/processServices.js
forms-flow-web/src/components/Form/EditForm/FormEdit.js
forms-flow-web/src/components/Modeler/ProcessCreateEdit.js

Fixed (web) : tenant key assigned with mapperId in api call of getProcessDetails

---

forms-flow-web/src/components/Form/EditForm/FormEdit.js
forms-flow-web/src/components/Form/EditForm/FormSettings.js
forms-flow-web/src/components/Form/List.js

JIRA: https://aottech.atlassian.net/browse/FWF-4078
* Added input validate loader for form title in settings

FWF-4078: Added input validate loader for form title

---

forms-flow-web/src/components/PrivateRoute.jsx

JIRA: 
https://aottech.atlassian.net/browse/FWF-3989
https://jam.dev/c/21d075f1-818e-4be8-8241-311253836a96

updated calling userroles by authenticating

---

forms-flow-documents/requirements/prod.txt

JIRA: 
- Added setuptools, 
- set version for selenium==4.25.0 since the download pdf is breaking with the latest version of selenium.

Documents-api: Update in prod.txt

---

forms-flow-api-utils/src/formsflow_api_utils/utils/permisions.py
forms-flow-api/tests/docker/realms/forms-flow-ai-realm.json
forms-flow-idm/keycloak/imports/formsflow-ai-realm.json
forms-flow-idm/migration/migrate-7.0.0.py
forms-flow-idm/realm-exports/Group based auth.json

JIRA: 
- Typo fix in permissions

Typo fix in permissions

---

forms-flow-web/src/components/Form/EditForm/FormEdit.js
forms-flow-web/src/components/Form/EditForm/FormSettings.js
forms-flow-web/src/helper/helper.js

JIRA:  https://aottech.atlassian.net/browse/FWF-4022
1.Added tenantkey prefix editable in path

bugfix/fwf-4022:Fixed tenantkey prefix editable in path

---

forms-flow-web/src/components/Form/Item/Submission/Item/Edit.js
forms-flow-web/src/components/Form/Item/View.js

JIRA: https://aottech.atlassian.net/browse/FWF-3933
* Added new class for wizard name issue fix

FWF-3933: [BugFix] Added class for wizard page name fix

---

forms-flow-web/package-lock.json
forms-flow-web/package.json

FWF-4097 [Feature] Updated formiojs and react-formio versions to incorporate hidden fields selection in conditional chaining
JIRA: https://aottech.atlassian.net/browse/FWF-4097
-Hidden fields will be listed along with form components in simple, advanced conditional logic

FWF-4097 [Feature] Updated formiojs and react-formio versions to incorporate hidden fields selection in conditional chaining

---

forms-flow-api-utils/src/formsflow_api_utils/utils/__init__.py
forms-flow-api/requirements.txt
forms-flow-api/requirements/prod.txt
forms-flow-api/src/formsflow_api/resources/process.py
forms-flow-api/src/formsflow_api/services/import_support.py
forms-flow-api/src/formsflow_api/services/process.py
forms-flow-api/tests/unit/api/test_process.py

JIRA: 
- Webapi permission matrix changes
Import .bpmn file restricted for the user without create_bpmn_flows permission

FWF-4093: [Feature] Webapi permission matrix changes

---

forms-flow-api/src/formsflow_api/constants/__init__.py
forms-flow-web/src/components/Modeler/helpers/helper.js

JIRA: 
- Changing the start event to Async to improve performance

Adding async start event

---

forms-flow-web/src/components/Form/EditForm/FormEdit.js

JIRA: https://aottech.atlassian.net/browse/FWF-4032

FWF-4032:[Feature]-Custom Scrollabr in layout.

---

forms-flow-web/craco.config.js
forms-flow-web/package-lock.json
forms-flow-web/package.json
forms-flow-web/src/components/Form/constants/ClientTable.js

updated package

---

forms-flow-api/requirements.txt
forms-flow-api/requirements/prod.txt
forms-flow-api/src/formsflow_api/models/authorization.py
forms-flow-api/src/formsflow_api/services/authorization.py
forms-flow-api/src/formsflow_api/services/import_support.py

…sername
JIRA: 
- Edit import designer auth username will existing username
- Remove parentformId from new import if it exists
- Check none check for roles

FWF-4088: [Bugfix] Edit import designer auth username will existing username & other minor bug fixes

---

forms-flow-api-utils/src/formsflow_api_utils/utils/permisions.py
forms-flow-api/tests/docker/realms/forms-flow-ai-realm.json
forms-flow-idm/keycloak/imports/formsflow-ai-realm.json
forms-flow-idm/migration/migrate-7.0.0.py
forms-flow-idm/realm-exports/Group based auth.json

Changes to permission labels to match with re-design terminology

---

forms-flow-api/src/formsflow_api/constants/__init__.py
forms-flow-web/src/components/Modeler/helpers/helper.js

JIRA: 
Removed the Async continuation from the start event since it is throwing an error with the version upgrade

FWF-4111: [Bugfix] Removed the Async continuation from start event 

---

forms-flow-bpm/forms-flow-bpm-camunda/src/main/resources/application.yaml

JIRA: 
- Add deployment permission to designers

Add deployment permission to designers

---

forms-flow-api/src/formsflow_api/app.py
forms-flow-api/src/formsflow_api/services/import_support.py

JIRA: 
- Removed after response translation code
- Removed auth check on edit import only bpmn for create_bpmn_flows since now we're not restricting workflow edit with create_bpmn_flows in opensrc

FWF-4109: [Bugfix] Webapi removed after response translation code

---

forms-flow-web/src/components/CustomComponents/MultiSelect.js
forms-flow-web/src/components/Form/EditForm/FormSettings.js
forms-flow-web/src/helper/helper.js

JIRA:  https://aottech.atlassian.net/browse/FWF-4081
1.Fixed tenantkey showing in permissions

bugfix/fwf-4081:fixed showing tenantkey in permission

---

deployment/docker/sample.env
forms-flow-web-root-config/sample.env
forms-flow-web/src/components/Form/EditForm/FormEdit.js
forms-flow-web/src/components/Form/Item/CreateTemplateConfirmModal.js
forms-flow-web/src/components/Form/Item/Submission/Item/View.js
forms-flow-web/src/components/Form/Steps/PreviewStepper.js
forms-flow-web/src/components/Form/Steps/SaveNext.js
forms-flow-web/src/components/Form/Steps/WorkFlow.js
forms-flow-web/src/components/Modeler/SubFlowTable.js
forms-flow-web/src/components/ServiceFlow/details/ServiceTaskDetails.js
forms-flow-web/src/components/ServiceFlow/list/ServiceTaskList.js
forms-flow-web/src/components/ServiceFlow/list/ServiceTaskListViewDetails.js
forms-flow-web/src/components/ServiceFlow/list/search/TaskFilterViewComponent.js
forms-flow-web/src/components/ServiceFlow/list/sort/CreateNewFilter.js

JIRA: https://aottech.atlassian.net/browse/FWF-4090
https://aottech.atlassian.net/browse/FWF-4072
1.Replaced 'workflow' with 'flow'
2.UI issues fixed

ui issues second part fixes(open src)

---

.github/workflows/forms-flow-documents-cd.yml
forms-flow-analytics/docker-compose.yml

JIRA: 
Issue Type: https://aottech.atlassian.net/browse/FWF-4107
* Updated the analytics version to 24.04.0
* Reverted the Documents-api CD action

FWF-4107: Analytics version upgradation and reverting the CD Action for Documents-api

---

forms-flow-api/src/formsflow_api/services/form_process_mapper.py

JIRA: 
- Added parentFormId to validation query to exclude current form while validating title
Including parentFormId

FWF-4120: [Bugfix] Added parentFormId to validation query

---

forms-flow-web/src/components/Application/ViewApplication.js
forms-flow-web/src/components/Draft/Edit.js
forms-flow-web/src/components/Draft/ViewDraft.js
forms-flow-web/src/components/Form/EditForm/FormEdit.js
forms-flow-web/src/components/Form/Item/Submission/Item/View.js
forms-flow-web/src/components/Form/Item/View.js
forms-flow-web/src/components/Form/constants/ClientTable.js
forms-flow-web/src/components/ServiceFlow/list/ServiceTaskListView.js

JIRA: https://aottech.atlassian.net/browse/FWF-4117
https://aottech.atlassian.net/browse/FWF-4112
changes in edit page and removed process diagrams in submission pages

changes in edit page and process diagram in submission page

---

forms-flow-web/src/components/App.jsx

JIRA: https://aottech.atlassian.net/browse/FWF-4035
1. Updated helper function for showing sidebar

bugfix/fwf-3035:Updated hleper fn

---

forms-flow-web/src/components/BPMN/BpmnViewer.js
forms-flow-web/src/components/CustomComponents/NavigateBlocker.jsx
forms-flow-web/src/components/CustomComponents/SortableHeader.js
forms-flow-web/src/components/Form/EditForm/FlowEdit.js
forms-flow-web/src/components/Form/EditForm/FormEdit.js
forms-flow-web/src/components/Insights/Insights.js
forms-flow-web/src/components/Insights/Insights.scss
forms-flow-web/src/components/Modals/ExportModal.js
forms-flow-web/src/components/Modals/TaskVariableModal.js
forms-flow-web/src/components/Modeler/Editors/BpmnEditor/BpmEditor.js
forms-flow-web/src/constants/applicationComponent.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-4114
https://aottech.atlassian.net/browse/FWF-4020
https://aottech.atlassian.net/browse/FWF-4101
https://aottech.atlassian.net/browse/FWF-4122
-Unsaved modal showing during migration is made unavailable. style fixes. 
-Button disabling fix during migration and button loading 
-analytics iframe height set to 90vh
-unsaved modal issues during delete, siwthcing between form,flow tabs fix
-Save button position change during form create

FWF-4114-4020-4101-4122 [Bugfix] Unsaved modal showing during migration is made unavailable. style fixes. button disabling fix in migration

---

forms-flow-web/src/apiManager/services/FormServices.js
forms-flow-web/src/components/Form/EditForm/FormSettings.js
forms-flow-web/src/components/ServiceFlow/list/sort/CreateNewFilter.js

JIRA: https://aottech.atlassian.net/browse/FWF-4120
1.Update validate api with parentFormId and formId
2.Added maxlength for permission list in create new filter and made scrollable

bugfix/fwf-4120:Updated validate api with parentFormId and formId

---

forms-flow-web/src/components/Application/ViewApplication.js
forms-flow-web/src/components/Dashboard/Dashboard.js

JIRA: https://aottech.atlassian.net/browse/FWF-4121
Scroll fixes in 
- submissions page
- dashboard page

FWF-4121 [Bugfix] scroll issues fixes

---

forms-flow-web/src/components/Form/SubmitList.js
forms-flow-web/src/components/Modals/TaskVariableModal.js

JIRA: https://aottech.atlassian.net/browse/FWF-4141
- taskvarible hidden variable showing issue fixed 
- modal sizing issue fixed. changed from sm size to lg

FWF-4141 [Bugfix] taskvarible hidden variable showing issue fixed and modal sizing issue

---

forms-flow-web/src/components/Modals/TaskVariableModal.js

JIRA: https://aottech.atlassian.net/browse/FWF-4128
* Updated wizard name issue in variables, design update in submissions

Updated wizard name issue in variables, design update in submissions

---

forms-flow-web/src/components/Dashboard/Dashboard.js
forms-flow-web/src/components/Form/EditForm/FormEdit.js
forms-flow-web/src/components/ServiceFlow/details/TaskDetail.scss
forms-flow-web/src/components/ServiceFlow/list/search/TaskFilterViewComponent.js

JIRA: https://aottech.atlassian.net/browse/FWF-4129
1.Fixed UI Issues 
2.

bugfix/fwf-4129:Fixed ui issuesin opensource

---

forms-flow-web/src/components/App.jsx

JIRA: https://aottech.atlassian.net/browse/FWF-4136
Sidebar hiding issue in multi environemnt pages fixed

FWF-4136 [Bugfix] Sidebar issue fixes with multi env

---

forms-flow-web/src/components/Form/EditForm/FormEdit.js

JIRA: https://aottech.atlassian.net/browse/FWF-4055
1.Fixed flow not updating in duplicate

bugfix/fwf-4055:Fixed flow is not updating when duplicating

---

forms-flow-web/src/components/Dashboard/Dashboard.js

JIRA: https://aottech.atlassian.net/browse/FWF-4135

Resolved UI issues in dashboard search

---

forms-flow-web/src/components/Form/EditForm/FormEdit.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-4131
https://jam.dev/c/5fcd1fbc-dc76-44d6-8e66-bf1d9d800270

minor version state update on unpublish

---

forms-flow-api/src/formsflow_api/services/import_support.py

JIRA: https://aottech.atlassian.net/browse/FWF-4132

Fixed returning task variable proper json format

---

forms-flow-web/src/components/ServiceFlow/list/sort/CreateNewFilter.js

JIRA: https://aottech.atlassian.net/browse/FWF-4154

Permission matrix fix for filter

---

forms-flow-web/src/components/Form/List.js

JIRA: https://aottech.atlassian.net/browse/FWF-4020
-Fixed modal showing for new forms switching from form to layout page

FWF-4020 [Bugfix] Unsaved changes issue for new form create without save fixed

---

forms-flow-web/src/components/Dashboard/StatusChart.js
forms-flow-web/src/components/Draft/Edit.js
forms-flow-web/src/components/Form/Item/Submission/Item/Edit.js
forms-flow-web/src/components/ServiceFlow/details/TaskDetail.scss
forms-flow-web/src/containers/Confirm.js

JIRA: https://aottech.atlassian.net/browse/FWF-4152
1.Fixed scrolling issues
2. centred confirmation modal

Bugfix/fwf 4152 scrolling issue&UI enhancement

---

forms-flow-web/src/components/Form/Item/index.js
forms-flow-web/src/constants/applicationComponent.js

JIRA: https://aottech.atlassian.net/browse/FWF-4160
1. Added Submitter's Email, First name , Last name
2. fixed form submission view caching problem,

Added: Added Submitter's Email , firstname, lastname & Fixed: cache existing form submission view

---

forms-flow-api/src/formsflow_api/services/process.py

JIRA: 
https://aottech.atlassian.net/browse/FWF-4168
- Currently migrated workflows are only saved in the process table with the new process key(form name) and not deployed to camunda.
- This PR will deploy the process to camunda
Before workflow migration
After migration

FWF-4168: [Bugfix] Deploy migrated workflow

---

forms-flow-api/src/formsflow_api/constants/__init__.py
forms-flow-web/src/components/Modals/TaskVariableModal.js
forms-flow-web/src/constants/applicationComponent.js

JIRA: https://aottech.atlassian.net/browse/FWF-4174
1. Added default task variables
2. removed all available roles

Added: added some hidden fields to default taskvariables & removed all user roles

---

forms-flow-web/src/components/Dashboard/Dashboard.js
forms-flow-web/src/components/Dashboard/StatusChart.js

JIRA: https://aottech.atlassian.net/browse/FWF-4170
* With submissions:
* No submissions:

[BugFix]: FWF-4170 Submission status UI fixes

---

forms-flow-web/src/components/Form/EditForm/FormEdit.js
forms-flow-web/src/components/Modals/ActionModal.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-4167

updated mapper call and disable the action modal

---

.github/workflows/trivy-scan.yml

This introduces a new GitHub Actions workflow named trivy-scanning. The workflow is designed to identify vulnerabilities in defined container images and the codebase.
Outputs:
Repository Scan Results: Accessible via the GitHub Security tab, showing vulnerabilities detected within the codebase.
Container Image Scan Reports: Available as downloadable HTML artifacts for each specified container image.

Added Trivy Action File: Container and Repository Vulnerability Scanning

---

forms-flow-api/src/formsflow_api/constants/__init__.py

JIRA: 
Updated currentUserRole label in default task variables from Current User Role to Current User Roles

Webapi: Updated currentUserRole label in default task variables from Current User Role to Current User Roles

---

forms-flow-web/src/components/Modals/TaskVariableModal.js

JIRA: https://aottech.atlassian.net/browse/FWF-4173
1.set initially updateform as null
2. fixed wizard form next and previous btn clickable in taskvariable

Fixed: set initial form as null and fixed wizard form next and previous button clickable in taskvariable

---

forms-flow-web/src/components/Application/Details/ApplicationDetails.js
forms-flow-web/src/components/Modals/ExportModal.js
forms-flow-web/src/components/ServiceFlow/details/ServiceTaskDetails.js

JIRA: https://aottech.atlassian.net/browse/FWF-4192

Resolved long form and flow name issues

---

forms-flow-bpm/forms-flow-bpm-camunda/src/main/resources/application.yaml

Adding DMN authorization for designers and reviewers

---

forms-flow-web/src/components/Dashboard/StatusChart.js

JIRA: https://aottech.atlassian.net/browse/FWF-4191

Resolved status name issue in metrics

---

forms-flow-web/src/components/Form/EditForm/FlowEdit.js
forms-flow-web/src/components/Form/EditForm/FormEdit.js
forms-flow-web/src/components/Modals/TaskVariableModal.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-4143
https://aottech.atlassian.net/browse/FWF-4091
https://aottech.atlassian.net/browse/FWF-4104
https://jam.dev/c/c70bc96b-5b70-4b4b-a675-f1750d712abb

Fix for Handle flow and layout save while form is published

---

forms-flow-web/src/components/Form/EditForm/FlowEdit.js

JIRA: https://aottech.atlassian.net/browse/FWF-4210

FWF-4210:[Feature] - Flow history button disabling on published state.

---

forms-flow-web/src/components/Form/EditForm/FlowEdit.js
forms-flow-web/src/components/Form/EditForm/FormEdit.js

JIRA: https://aottech.atlassian.net/browse/FWF-4211
- Setting of updated process id on unpublish and save code moved as common code without considetring whether change is happened on flow/layout 
- Redundant isWorkflow changed flag to formedit alone and removed extra usestate in flowedit

FWF-4211 [Bugfix] process id error after unpublish and save fixed

---

.github/workflows/forms-flow-data-analysis-api-ci.yml
CHANGELOG.md
forms-flow-api/README.md
forms-flow-bpm/README.md
forms-flow-data-analysis-api/README.md
forms-flow-documents/README.md
forms-flow-web/README.md

release-7.0.0 changelog & readme

---

forms-flow-api/requirements.txt
forms-flow-api/requirements/prod.txt
forms-flow-documents/requirements.txt
forms-flow-documents/requirements/prod.txt
jobs/sentiment-analysis/requirements.txt
jobs/sentiment-analysis/requirements/prod.txt

JIRA: 
Updated utils reference in requirements file to point to the release7.0.0 branch

Updated utils reference in requirements file to point to the release7.0.0 branch

---

CHANGELOG.md
DEPENDENCIES.md
README.md
forms-flow-web-root-config/sample.env

JIRA: 
Release v7.0.0 documentation updates
- Dependencies.md
- Changelog.md
- Readme.md
- web-root-config - sample.env

🚀 Release v7.0.0

---

forms-flow-web/src/components/Form/EditForm/FormSettings.js

JIRA: 3 in https://aottech.atlassian.net/browse/FWF-4013

Added maxLength to form name in settings

---

forms-flow-web/src/components/BPMN/bpm.scss

JIRA: https://aottech.atlassian.net/browse/FWF-4194
workflow components getting blank with long form name issue fixed

workflow components getting blank with long form name issue fixed

---

forms-flow-web/src/components/PrivateRoute.jsx

JIRA: https://aottech.atlassian.net/browse/FWF-4223
1. changed publish event position before authenticate

Fixed: logout button issue

---

forms-flow-web/src/components/Modals/ImportProcess.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-4225
https://jam.dev/c/9823e463-24de-4a4e-84b5-164a7f419704

update process on import

---

forms-flow-web/src/components/Modals/ImportProcess.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-4225

update process on edit fix 

---

forms-flow-web/src/components/Modals/ActionModal.js
forms-flow-web/src/components/Modeler/ProcessCreateEdit.js

JIRA: 
* Fixed publish and migrate note issues, 
* Enabled duplicate option

Fixed publish and migrate note issues, enabled duplicate option

---

forms-flow-web/src/components/PrivateRoute.jsx

Fixed: logout button issue to release/7.0.0

---

forms-flow-api/requirements.txt
forms-flow-api/requirements/prod.txt
forms-flow-documents/requirements.txt
forms-flow-documents/requirements/prod.txt
jobs/sentiment-analysis/requirements.txt
jobs/sentiment-analysis/requirements/prod.txt

JIRA: 
Updated utils reference in the requirements file to point to the develop branch

Updated utils reference in the requirements file to point to the develop branch

---

forms-flow-web/src/components/Modals/ActionModal.js

Sync/master 7.0.0 ➡️ develop 

---

forms-flow-web/src/components/Form/EditForm/FormSettings.js
forms-flow-web/src/components/Modals/SettingsModal.js

JIRA: https://aottech.atlassian.net/browse/FWF-4138
=>The name and path will be validated on clicking the save changes button if not yet done. 
=> If validation error that will be cleared on changing the value of the input for further check.
=>the Save Changes button will be disabled if any validation error surfaced.

FWF-4138:[Bugfix]- Settings validation update.

---

forms-flow-web/src/resourceBundles/i18n.js

JIRA: https://aottech.atlassian.net/browse/FWF-3782

Added translation for wizard for buttons

---

forms-flow-web/src/components/Modeler/ProcessTable.js

JIRA: https://aottech.atlassian.net/browse/FWF-3963
1.Fixed search retaining issue when switching between bpmn and dmn

bugfix/fwf-3963:Fixed search retaining issue when switching bpmn&dmn

---

forms-flow-api/src/formsflow_api/services/form_process_mapper.py
forms-flow-api/src/formsflow_api/services/import_support.py

JIRA: https://aottech.atlassian.net/browse/FWF-4274

Fixed: show incorrect version on save layout after edit import

---

forms-flow-web/src/components/CustomComponents/SortableHeader.js
forms-flow-web/src/components/Modals/TaskVariableModal.js

JIRA: https://aottech.atlassian.net/browse/FWF-4187
color updation changes

color updation changes

---

forms-flow-web/src/components/Form/EditForm/FormSettings.js
forms-flow-web/src/components/Modals/SettingsModal.js

JIRA: https://aottech.atlassian.net/browse/FWF-4138
--> Updated name => title to have a common approach
--> Added a sanitization to remove # from input
--> Added a loading for validation in save button.( only on clicking save without validation )

FWF-4138:[Feature] - Validation updates for settings modal

---

forms-flow-web/src/components/Form/EditForm/FormEdit.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-4260
https://jam.dev/c/76859159-92e1-4a1d-9f16-b2aea5168a90

updated form title on major version

---

forms-flow-web/src/components/Modals/TaskVariableModal.js

JIRA: https://aottech.atlassian.net/browse/FWF-4311

FWF-4311 [bugfix] fixed hide Label issue in task variables

---

forms-flow-web/src/components/Modals/TaskVariableModal.js

JIRA: https://aottech.atlassian.net/browse/FWF-4311
1. removed conditions form the component only for rendering the form in task variable modal

FWF-4311 [ Bugfix ] :Fixed => showing conditionaly rendered component in taskvariable modal

---

forms-flow-web/src/components/CustomComponents/FilterSortActions.js
forms-flow-web/src/components/Form/List.js
forms-flow-web/src/components/Modeler/ProcessTable.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-4269

Added data-test-id and aria labels

---

forms-flow-api-utils/src/formsflow_api_utils/utils/auth.py
forms-flow-api-utils/src/formsflow_api_utils/utils/format.py

JIRA: 
https://aottech.atlassian.net/browse/FWF-4295
- Added the tenantKey in webAPI log

Add tenantKey to web-api logs

---

forms-flow-web/src/assets/styles/base.scss
forms-flow-web/src/assets/styles/formioTooltip.scss
forms-flow-web/src/components/App.jsx

JIRA: https://aottech.atlassian.net/browse/FWF-4289

FWF-4289 [bugfix] fixed tooltip issue in formio forms

---

forms-flow-web/src/assets/styles/base.scss
forms-flow-web/src/components/BPMN/bpm.scss
forms-flow-web/src/components/Dashboard/dashboard.scss
forms-flow-web/src/components/Form/List.scss
forms-flow-web/src/components/Form/Steps/steps.scss
forms-flow-web/src/components/Form/stepper.scss
forms-flow-web/src/components/Insights/Insights.scss
forms-flow-web/src/components/Modeler/Editors/Editor.scss
forms-flow-web/src/components/NotFound/pagenotfound.scss
forms-flow-web/src/components/ServiceFlow/ServiceFlow.scss
forms-flow-web/src/components/ServiceFlow/details/TaskDetail.scss
forms-flow-web/src/containers/Stepper/style.scss
forms-flow-web/src/containers/styles.scss
forms-flow-web/src/styles.scss
forms-flow-web/src/variables.scss

JIRA: https://aottech.atlassian.net/browse/FWF-4305
color corrections with new style variables

color correction with new variables

---

forms-flow-web/src/_tests_/unit/list.test.js
forms-flow-web/src/_tests_/unit/mockState.js
forms-flow-web/src/components/Form/EditForm/FormEdit.js
forms-flow-web/src/components/Modals/ActionModal.js
forms-flow-web/src/components/Modals/ImportProcess.js
forms-flow-web/src/components/Modeler/ProcessCreateEdit.js

JIRA: https://aottech.atlassian.net/browse/FWF-4181
Added Translation for action modal

FWF-4181: [Feature] Added translation in action modal

---

forms-flow-web/src/assets/styles/base.scss
forms-flow-web/src/assets/styles/formioTooltip.scss
forms-flow-web/src/assets/styles/layouts.scss
forms-flow-web/src/components/App.jsx

JIRA: https://aottech.atlassian.net/browse/FWF-4289

FWF-4289 [bugfix] fixed formio tooltip issue by override semantic css in relase/6.0.2

---

forms-flow-api/src/formsflow_api/constants/__init__.py
forms-flow-api/src/formsflow_api/resources/form_process_mapper.py
forms-flow-api/src/formsflow_api/services/authorization.py
forms-flow-api/src/formsflow_api/services/form_process_mapper.py
forms-flow-api/tests/unit/api/test_form_process_mapper.py

JIRA: https://aottech.atlassian.net/browse/FWF-3772
1. added new api  to get form data after checking proper authorization

FWF-3772 [feature] added new api /form-data/form in webapi to get the form data after checking proper authorization

---

forms-flow-web/src/routes/Design/Forms/FlowEdit.js
forms-flow-web/src/routes/Design/Forms/FormEdit.js

Added dataTestId for form and flow history modal

---

forms-flow-web/src/_tests_/unit/formEdit.test.js
forms-flow-web/src/components/Modals/SettingsModal.js
forms-flow-web/src/routes/Design/Forms/FormEdit.js

JIRA: https://aottech.atlassian.net/browse/FWF-4222
form edit page testcase

FWF-4222 form edit page testcase

---

forms-flow-web/src/components/CustomComponents/FilterSortActions.js

JIRA: https://aottech.atlassian.net/browse/FWF-4333
Added custom button with icon only for filter and refresh

FWF-4333 : [Feature] Added custom button with icon only for filter and refresh

---

forms-flow-web/src/apiManager/services/bpmFormServices.js
forms-flow-web/src/routes/Submit/Forms/SubmitList.js

changed done call back from params object to next param

---

forms-flow-api-utils/src/formsflow_api_utils/utils/__init__.py
forms-flow-api-utils/src/formsflow_api_utils/utils/enums.py

JIRA: 
Added AIRequestType to API utils which is used by chatbot

Added AIRequestType to API utils

---

.github/workflows/forms-flow-api-cd.yml

Update forms-flow-api-cd.yml to add QEMU workflow action

---

.github/workflows/forms-flow-data-analysis-api-cd.yml
.github/workflows/forms-flow-documents-cd.yml

Fixed cd for documents, analysis api

---

forms-flow-web/package-lock.json
forms-flow-web/package.json
forms-flow-web/src/components/ServiceFlow/index.js
forms-flow-web/src/services/SocketIOUpdatedService.js

JIRA: https://aottech.atlassian.net/browse/FWF-4365
Replaced currently used stompjs with stomp/stompjs package as the other package is not actively maintained. 
Currently the change is done in open source repo to see whether its working. If working fine can be added to MF

FWF-4365 [Feature] Replaced stompjs with stomp/stompjs

---

forms-flow-web/src/apiManager/endpoints/index.js
forms-flow-web/src/apiManager/services/draftService.js
forms-flow-web/src/components/Draft/EditDraft.js
forms-flow-web/src/components/PublicRoute.jsx
forms-flow-web/src/routes/Submit/Forms/SubmitIndex.js
forms-flow-web/src/routes/Submit/Forms/UserForm.js

JIRA: https://aottech.atlassian.net/browse/FWF-4346
Issue Type : BUG/ FEATURE
1. Added new submission page 
2. Handled both new submission and draft in one file

feature/fwf-4346:Added new submission page

---

forms-flow-api-utils/src/formsflow_api_utils/utils/__init__.py
forms-flow-api-utils/src/formsflow_api_utils/utils/telemetry.py

JIRA: 
https://aottech.atlassian.net/browse/FWF-1900
1. Added telemetry.py in forms-flow-api-utils

Added telemetry.py in forms-flow-api-utils

---

forms-flow-data-layer/main.py
forms-flow-data-layer/requirements/base.txt
forms-flow-data-layer/src/db/__init__.py
forms-flow-data-layer/src/db/bpmn_db.py
forms-flow-data-layer/src/db/formio_db.py
forms-flow-data-layer/src/db/webapi_db.py
forms-flow-data-layer/src/utils/__init__.py
forms-flow-data-layer/src/utils/logger.py
forms-flow-data-layer/src/utils/sql_base.py

feateure added sqlalchemy and changed db config

---

forms-flow-api/src/formsflow_api/models/application.py
forms-flow-api/src/formsflow_api/models/form_process_mapper.py
forms-flow-api/src/formsflow_api/resources/form_process_mapper.py
forms-flow-api/src/formsflow_api/schemas/form_process_mapper.py
forms-flow-api/src/formsflow_api/services/form_process_mapper.py

JIRA: 
https://aottech.atlassian.net/browse/FWF-4378
-  Added sort by to submission count
- Refactored the code to utilize subqueries to fetch submission counts.
- find_all_active_by_formid method moved from form_process_mapper models to application models to eliminate circular import

FWF-4378: [Feature] Added sortby to submission count

---

.github/workflows/forms-flow-root-config-cd.yml

Updated action/cache version update in  forms-flow-root-config-cd.yml

---

.github/workflows/forms-flow-api-cd.yml
.github/workflows/forms-flow-bpm-cd.yml
.github/workflows/forms-flow-documents-cd.yml
.github/workflows/forms-flow-idm.yml
.github/workflows/forms-flow-root-config-cd.yml

fix for codeql action break

---

forms-flow-web/src/constants/constants.js
forms-flow-web/src/routes/Design/Forms/FormEdit.js
forms-flow-web/src/routes/Design/Forms/List.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-4066

fix for import error

---

.github/workflows/forms-flow-api-cd.yml
.github/workflows/forms-flow-bpm-cd.yml
.github/workflows/forms-flow-data-analysis-api-cd.yml
.github/workflows/forms-flow-documents-cd.yml

updated the action

---

.github/workflows/forms-flow-bpm-ci.yml

[Bugfix] Bpm ci actions cache version updated to v4 from v1

---

.github/workflows/forms-flow-api-cd.yml
.github/workflows/forms-flow-bpm-cd.yml
.github/workflows/forms-flow-data-analysis-api-cd.yml
.github/workflows/forms-flow-documents-cd.yml
.github/workflows/forms-flow-idm.yml
.github/workflows/forms-flow-root-config-cd.yml

Updated action/cache version in all workflow files  as generic fix (even on workflow files where workflow run didnt happened)
JIRA: 

[Bugfix] Actions cache package version upgrade to v4 from v1 in multiple yml files

---

.github/workflows/forms-flow-bpm-cd.yml

JIRA: 
Refer 
https://github.com/github/codeql-action/issues/2187

fix for skipping null severity snyk

---

forms-flow-api/src/formsflow_api/resources/user.py
forms-flow-api/src/formsflow_api/services/factory/bcgov_shared_realm_service.py
forms-flow-api/src/formsflow_api/services/factory/keycloak_admin.py
forms-flow-api/src/formsflow_api/services/factory/keycloak_factory.py
forms-flow-api/src/formsflow_api/services/factory/keycloak_group_service.py
forms-flow-api/src/formsflow_api/services/import_support.py

Fix lint error

---

forms-flow-api/src/formsflow_api/resources/filter.py
forms-flow-api/src/formsflow_api/services/application.py
forms-flow-web/src/components/Modals/TaskVariableModal.js

JIRA: [ FWF-4387](https://aottech.atlassian.net/browse/FWF-4387)
Issue Type: BUG/
1. taking parent component api key and construct the api key with current component in front end
2. taking nested data from the object on backend

FWF-4387 [bugfix] fixed taskvariable data for container

---

forms-flow-web/src/components/ServiceFlow/ServiceFlow.scss
forms-flow-web/src/containers/TaskHead.js

JIRA: https://aottech.atlassian.net/browse/FWF-4402
1.filter in list view height issue fixed 
2.custom switch class added

style changes for patch 7.0.1

---

CHANGELOG.md
README.md

JIRA: 
Changelog and readme fles update

Release 7.0.1 Changelog and readme updated

---

forms-flow-api/requirements.txt
forms-flow-api/requirements/prod.txt
forms-flow-documents/requirements.txt
forms-flow-documents/requirements/prod.txt

release/7.0.1 :  Utils url changed

---

.github/workflows/forms-flow-bpm-cd.yml

Fixing invalid syntax in BPM CD

---

forms-flow-web/src/components/PrivateRoute.jsx

JIRA:  https://aottech.atlassian.net/browse/FWF-3865

FWF-3865 [bugfix] removed unwanted available roles fetching api call

---

forms-flow-web-root-config/src/index.ejs

Fixed broken links, arj.js and bpmn property panel.css

---

forms-flow-web-root-config/src/index.ejs

JIRA: https://aottech.atlassian.net/browse/FWF-4421

FWF-4221 [bugfix] fixed cdn breaking

---

forms-flow-web-root-config/src/formsflow-root-config.js
forms-flow-web-root-config/src/index.ejs

JIRA: https://aottech.atlassian.net/browse/FWF-4416

FWF-4416 [bugfix] preload custom theme

---

forms-flow-web/src/apiManager/endpoints/index.js
forms-flow-web/src/components/Draft/EditDraft.js
forms-flow-web/src/components/Form/constants/SubmissionsAndDraftTable.js
forms-flow-web/src/routes/Submit/Forms/DraftAndSubmissions.js
forms-flow-web/src/routes/Submit/Forms/UserForm.js

JIRA: https://aottech.atlassian.net/browse/FWF-4344
-Updated sort filter
-Updated New submission api
-Updated time format in table
-Added Delete modal for the draft delete.

FWF-4344:[Feature]- Submission api updates and client page bug fixes

---

forms-flow-web/src/apiManager/services/bpmTaskServices.js
forms-flow-web/src/components/ServiceFlow/details/UserSelectionDebounce.js

JIRA: https://aottech.atlassian.net/browse/FWF-4390

FWF-4390 [feature] users will list based on groups which is associated with task

---

forms-flow-web/src/apiManager/services/applicationServices.js
forms-flow-web/src/components/Form/constants/SubmissionsAndDraftTable.js
forms-flow-web/src/routes/Submit/Forms/DraftAndSubmissions.js
forms-flow-web/src/routes/Submit/Forms/UserForm.js

JIRA: https://aottech.atlassian.net/browse/FWF-4344

FWF-4344:[Feature]- Added loader in application table.

---

forms-flow-web/src/routes/Submit/Forms/UserForm.js

JIRA: 
1.Fixed redirection issue in onsubmit form

bugfix/fwf-4344:Fixed redirection issue in onSubmit form

---

forms-flow-bpm/forms-flow-bpm-camunda/src/main/java/org/camunda/bpm/extension/commons/connector/HTTPServiceInvoker.java
forms-flow-web-root-config/src/index.ejs

JIRA: 
-formio url validation commented in bpm for service url fixes . 
-Updated properties panel css cdn link

Release 7.0.1 [Bugfix] formio url validation commented in bpm for service url fixes . Updated properties panel css

---

.github/workflows/forms-flow-data-layer-ci.yml
forms-flow-data-layer/src/config/envs.py
forms-flow-data-layer/src/graphql/resolvers/submission_resolvers.py
forms-flow-data-layer/src/utils/keycloak_oidc.py
forms-flow-data-layer/tests/conftest.py
forms-flow-data-layer/tests/docker/docker-compose.yml
forms-flow-data-layer/tests/docker/realms/forms-flow-ai-realm.json
forms-flow-data-layer/tests/resolvers/test_submissions.py
forms-flow-data-layer/tests/utils.py

JIRA: 
https://aottech.atlassian.net/browse/FWF-4432
- Added test utils for JWT token generation 
- Updated test cases for submissions to utilize mocks.
- Added mock Keycloak configuration for pytest
- Added CI job GitHub Actions to run tests in the data-layer

Feature/fwf 4432 Data layer: Add pytest in CI

---

deployment/Individual-deployment/README.md

updated doc

---

forms-flow-api/src/formsflow_api/services/form_process_mapper.py
forms-flow-api/src/formsflow_api/services/import_support.py
forms-flow-web/src/components/Form/EditForm/FormEdit.js

JIRA: https://aottech.atlassian.net/browse/FWF-4445

[Hotfix] Fwf 4445 fix version issue in form edit import

---

.github/workflows/forms-flow-api-ci.yml
.github/workflows/forms-flow-bpm-ci.yml
.github/workflows/forms-flow-data-analysis-api-ci.yml
.github/workflows/forms-flow-data-layer-ci.yml
.github/workflows/forms-flow-documents-ci.yml
.github/workflows/forms-flow-web-cd.yml
.github/workflows/forms-flow-web-ci.yml

updated ubantu version

---

forms-flow-web/src/helper/processHelper.js

JIRA: https://aottech.atlassian.net/browse/FWF-4477

[Hotfix] FWF-4477 [bugfix] ignored bpmn modler warnings

---

forms-flow-web/src/helper/processHelper.js

JIRA: https://aottech.atlassian.net/browse/FWF-4477

FWF-4477 [bugfix] ignored warnings form bpmn

---

forms-flow-api/src/formsflow_api/services/factory/keycloak_group_service.py

JIRA: https://aottech.atlassian.net/browse/FWF-4390

FWF-4390 [bugfix] fixed tenantKey adding in group name

---

forms-flow-web/src/components/Form/ExportAsPdf/downloadPdfButton.jsx
forms-flow-web/src/components/Form/constants/ClientTable.js
forms-flow-web/src/components/Form/constants/SubmissionsAndDraftTable.js
forms-flow-web/src/routes/Submit/Submission/SubmissionView.js

JIRA: https://aottech.atlassian.net/browse/FWF-4464
Client screen issue fixes and style fixes

FWF-4464 [Bugfix] Client screen issue fixes and style fixes

---

.github/workflows/forms-flow-bpm-cd.yml

JIRA: https://aottech.atlassian.net/browse/FWF-4434

FWF-4434 [Bugfix] Serif error in bpm build error fix

---

CHANGELOG.md
forms-flow-api-utils/src/formsflow_api_utils/utils/permisions.py
forms-flow-api/tests/docker/realms/forms-flow-ai-realm.json
forms-flow-bpm/forms-flow-bpm-camunda/src/main/java/org/camunda/bpm/extension/keycloak/rest/KeycloakAuthenticationFilter.java
forms-flow-bpm/forms-flow-bpm-camunda/src/main/resources/application.yaml
forms-flow-idm/keycloak/imports/formsflow-ai-realm.json
forms-flow-idm/realm-exports/Group based auth.json

Adding changes for new permission to work on submitter tasks

---

forms-flow-api/src/formsflow_api/services/factory/bcgov_shared_realm_service.py

Fixing issue CSS API for query param

---

forms-flow-web/src/apiManager/services/userservices.js

JIRA: https://aottech.atlassian.net/browse/FWF-4431
1. Stored formio token in sessionStorage

feature/fwf-443:1 Stored formio token in sessionStorage

---

forms-flow-web/src/_tests_/unit/draftAndSubmissions.test.js
forms-flow-web/src/_tests_/unit/submissionAndDraftTable.test.js

JIRA: https://aottech.atlassian.net/browse/FWF-4360

FWF-4360:[Feature]- Unit Test Case: DraftAndSubmissioins.js and SubmissionAndDraftTable.js pages

---

forms-flow-data-layer/src/graphql/resolvers/__init__.py
forms-flow-data-layer/src/graphql/resolvers/submission_resolvers.py
forms-flow-data-layer/src/graphql/schema/__init__.py
forms-flow-data-layer/src/graphql/schema/submission_schema.py
forms-flow-data-layer/src/graphql/service/formio_form_service.py
forms-flow-data-layer/src/graphql/service/submission_service.py
forms-flow-data-layer/src/models/formio/submission.py
forms-flow-data-layer/tests/resolvers/test_submissions.py
forms-flow-data-layer/tests/utils.py

JIRA: 
https://aottech.atlassian.net/browse/FWF-4446
- Added support to query  data attributes from web-api and form submission data
- Added tenant authorization and form authorization while fetching data
- Added single field sorting and pagination.
sample query
```
query MyQuery {
querysubmissions(
limit: 5
sortOrder: "desc"
sortBy: "id"
pageNo: 1
search: {created_by: "formsflow-designer", location: "delhi"}
mongoProjectFields: ["location", "name"]
parentFormId: "67eced6a11e3ea332946080e"
) {
totalCount
pageNo
submissions {
id
createdBy
applicationStatus
data
}
limit
}
}
```

Fwf 4446 add query support data layer

---

forms-flow-web/src/components/Modals/ActionModal.js
forms-flow-web/src/components/Modals/ImportProcess.js
forms-flow-web/src/routes/Design/Forms/List.js

JIRA: https://aottech.atlassian.net/browse/FWF-4355
1. Button style fixes 
2. Typo fixes

bugfix/fwf-4355:Button style fixes & typo fixes

---

.github/workflows/forms-flow-idm.yml

[Bugfix] Update docker build action/cache version to 4 from 2 in idm

---

forms-flow-data-layer/src/graphql/service/submission_service.py

JIRA: 
https://aottech.atlassian.net/browse/FWF-4446
- When checking authorized to view/query submissions, need to check the APPLICATION in the authorization table.

Data-layer: FWF-4446: [Bugfix] Updates to query results based on user permissions who can view the applications

---

forms-flow-web/src/routes/Submit/Forms/UserForm.js

JIRA: https://aottech.atlassian.net/browse/FWF-4327?focusedCommentId=29073
Issue Type: BUG 
fixed draft previous data mutating

FWF-4327 [bugfix] fixed draft previous data mutating

---

forms-flow-web/src/routes/Submit/Forms/UserForm.js

JIRA: https://aottech.atlassian.net/browse/FWF-4462
Issue fix for anonymous user with day component form loading fixed by passing default language

FWF-4462 [Bugfix] Issue fix for anonymous user with day component form loading

---

forms-flow-web/src/components/Modeler/lint-rules/packed-config.js

JIRA: https://aottech.atlassian.net/browse/FWF-4478
- commented some lint rule to enable inclusive gateway and some other nodes
-->

FWF-4478 [bugfix] fixed lint error in bpmn

---

forms-flow-web/src/_tests_/unit/BPMN/DecisionTable.test.js
forms-flow-web/src/_tests_/unit/BPMN/ProcessTable.test.js
forms-flow-web/src/routes/Design/Forms/List.js
forms-flow-web/src/routes/Design/Process/ProcessTable.js
forms-flow-web/src/routes/Submit/Forms/DraftAndSubmissions.js
forms-flow-web/src/routes/Submit/Forms/SubmitList.js

JIRA: https://aottech.atlassian.net/browse/FWF-4453
1. Fixed sorting from sort modal

bugfix/fwf-4453:Fixed soringtby resetting sort values from sortmodal in all tables

---

.github/workflows/pr_review_agent.yml

JIRA: https://aottech.atlassian.net/browse/FWF-4563

❇️  Create pr_review_agent.yml

---

CHANGELOG.md
forms-flow-api-utils/src/formsflow_api_utils/utils/permisions.py
forms-flow-idm/keycloak/imports/formsflow-ai-realm.json
forms-flow-idm/realm-exports/Group based auth.json

JIRA: 
- Added new permission to view the process diagram and view history

FWF-4497: [Feature] Added new permission to view the process diagram and view history

---

forms-flow-web/src/routes/Submit/Forms/SubmitIndex.js

Fixed draft creation by clearing existing draft data

---

.github/workflows/check-dependecy-pr.yml

updated dependency pr with custom action

---

forms-flow-bpm/forms-flow-bpm-camunda/pom.xml
forms-flow-bpm/forms-flow-bpm-utils/pom.xml
forms-flow-bpm/pom-default.xml
forms-flow-bpm/pom.xml

JIRA: https://aottech.atlassian.net/browse/FWF-4830
Issue Type: HOTFIX
DEPENDENCY PR:
Updated version to 7.0.3.rc

FWF-4830 [Hotfix] Updated bpmn image version to 7.0.3.rc

---

CHANGELOG.md
forms-flow-api-utils/src/formsflow_api_utils/utils/pdf.py
forms-flow-documents/requirements.txt
forms-flow-documents/requirements/prod.txt
forms-flow-documents/src/formsflow_documents/app.py

JIRA: 
https://aottech.atlassian.net/browse/FWF-4884
DEPENDENCY PR:
- Increase wait time to 60 seconds for element presence in PDF generation
- Added locale check for token info in app initialization
- Update formsflow_api_utils dependency to use patch/7.0.4 in requirements file to include the latest changes in requirements

Documents API fixes: Increase wait time for PDF generation and add locale check for token info in app initialization

---

CHANGELOG.md
forms-flow-web-root-config/sample.env
forms-flow-web/src/routes/Design/Forms/FormEdit.js

🚀 Develop to Release 7.1.0

---

forms-flow-web/src/routes/Design/Forms/FlowEdit.js

JIRA:  https://aottech.atlassian.net/browse/FWF-4654
DEPENDENCY PR:
1. Updated variable selection modal 
2. added unsaved layoutchanges modal 
1. Kept old task variable component and will remove after review
___
Enhancement
___
- Add reusable variable selection modal
- Introduce unsaved changes warning modal
- Map and fetch task variables on load
- Save variables via API on confirmation
___
```mermaid
flowchart LR
A["FlowEdit: Click Variables"] -- "click" --> B{"layoutNotsaved?"}
B -- "yes" --> C["UnsavedChangesModal"]
B -- "no" --> D["VariableModal"]
D -- "save" --> E["API: saveFormProcessMapperPut"]
```
<table><thead><tr><th></th><th align="left">Relevant …

feature/fwf-4654: Added new variable selection modal

---

forms-flow-api/src/formsflow_api/resources/submissions_filter.py
forms-flow-api/src/formsflow_api/services/submissions_filter.py
forms-flow-api/tests/unit/api/test_submissions_filter.py

JIRA: 
https://aottech.atlassian.net/browse/FWF-5114
DEPENDENCY PR:
Add default submissions filter to submission filter list API response model 
- Introduced a new response model `FilterResponseWithDefaultFilter` to include a default submissions filter ID.
- Updated `SubmissionsFilterService` to retrieve and include the user's default submissions filter in the response.
- Modified unit tests to validate the new response structure and ensure correct filter data is returned.
___
Enhancement, Tests
___
- Introduce default submissions filter response model
- Include defaultSubmissionsFilter in service output
- Update API docs to use new response structure
- Extend unit tests for default filter logic
___ …

FWF-5114: Add default submissions filter to analyze submission filter list API response

---

forms-flow-data-layer/src/db/sql_base.py
forms-flow-data-layer/src/models/webapi/base.py

JIRA: 
https://aottech.atlassian.net/browse/FWF-4940
DEPENDENCY PR:
- Refactor session management with Session Per Request
https://jam.dev/c/c1ae2092-4aca-4f34-89e9-9845d780933f
___
___
- Changed session creation to synchronous factory
- Webapi execute now uses async context manager
- Ensures sessions close after query execution
___
```mermaid
flowchart LR
Start["Call execute(query)"] --> GetSession["webapi_db.get_session()"]
GetSession --> WithSession["async with session"]
WithSession --> Execute["session.execute(query)"]
Execute --> End["Return result & close session"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</stro …

🐛 FWF-4940: [Bugfix] Datalayer: Fix Transaction not restarting when there's error in webapi query

---

forms-flow-web/src/routes/Design/Process/ProcessTable.js
forms-flow-web/src/routes/Design/Process/index.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-5042
https://jam.dev/c/c6a5caf4-a8bf-4181-a3cb-27b1fb6f0754
DEPENDENCY PR:
___
Bug fix
___
- Added manageAdvancedWorkFlows permission check
- Enabled 'New Process' button for workflows
- Included manage_advance_workflows in route guard
___
```mermaid
flowchart LR
A["User roles"] -- "create_designs or manage_advance_workflows" --> B["Show 'New Process' button"]
A -- "manage_advance_workflows" --> C["Allow Process route access"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>ProcessTable.js</strong><dd><code>Add advanced workflows …

bugfix/FWF-5042 [bugfix] updated permission on workflow

---

forms-flow-web/src/_tests_/unit/mockState.js
forms-flow-web/src/_tests_/unit/rootReducer.js
forms-flow-web/src/components/Application/ApplicationTable.js
forms-flow-web/src/components/Draft/DraftTable.js
forms-flow-web/src/components/Form/constants/ClientTable.js
forms-flow-web/src/components/Form/constants/FormTable.js
forms-flow-web/src/components/Form/constants/SubmissionsAndDraftTable.js
forms-flow-web/src/components/Form/constants/table.js
forms-flow-web/src/modules/bpmFormReducer.js
forms-flow-web/src/modules/index.js
forms-flow-web/src/routes/Design/Process/ProcessTable.js
forms-flow-web/src/routes/Submit/Forms/SubmitList.js

- Updaged pagination from 5 to 10 in all pages.
- Upadted search barissue in submission page.
JIRA: http://aottech.atlassian.net/browse/FWF-4956
DEPENDENCY PR:
___
Enhancement
___
- Increase default pagination limit to 10.
- Update pageOptions values accordingly.
- Adjust TableSkeleton rows to 10.
- Remove redundant div in SearchBar.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody></tr></tbody></table>
</details>
___

FWF-4956:[Bugfix] - WEB bugfixes

---

CHANGELOG.md
forms-flow-idm/README.md
forms-flow-idm/keycloak/imports/formsflow-ai-realm.json
forms-flow-idm/migration/README.md
forms-flow-idm/migration/migrate-7.2.0.py
forms-flow-idm/migration/utils.py
forms-flow-idm/realm-exports/Group based auth.json

JIRA: 
https://aottech.atlassian.net/browse/FWF-4669
https://aottech.atlassian.net/browse/FWF-5117
DEPENDENCY PR:
Update migrate-7.2.0.py to migrate new roles(permissions ) to the existing default & custom groups
Added migration functions
- To assign new roles to default groups
- To map old roles to new roles for custom groups. &  assign new roles for custom groups.
- Introduced `get_groups` and `get_sub_groups` utility functions for group management.
- Updated main migration logic to include new role migration processes for both single-tenant and multi-tenant environments.
___
Enhancement
___
- Expand migration script for single and multi-tenant groups
- Add utilities: get_groups, get_sub_groups, group ID by path
- Update docs and README migration instructions
- …

IDM: Feature/fwf 4669  Add migrate permissions to the existing groups  7 to 7.1

---

forms-flow-api/src/formsflow_api/constants/__init__.py
forms-flow-api/src/formsflow_api/services/factory/keycloak_group_service.py

JIRA: 
https://aottech.atlassian.net/browse/FWF-4896
DEPENDENCY PR:
- Refactor error handling for role creation to use a more descriptive error message
___
___
- Improve duplicate role error message
- Add new error code `ROLE_ERROR`
- Replace old `DUPLICATE_ROLE` references
- Preserve HTTP 400 status code
___
<tr>
<td>
<details>
<summary><strong>__init__.py</strong><dd><code>Define `ROLE_ERROR` with detailed message</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …

Bugfix: Refactor error handling for role creation to use more descriptive error message

---

forms-flow-data-layer/src/models/formio/submission.py

JIRA: 
https://aottech.atlassian.net/browse/FWF-5141
DEPENDENCY PR:
- Enhance query filtering in query_submission to support date filtering of DD-MM-YYYY format in the form fields
___
___
- Support DD-MM-YYYY date filtering in queries
- Compute inclusive UTC date ranges
- Fallback to regex for non-date strings
___
```mermaid
flowchart LR
A["Filter value"] -- "parse as DD-MM-YYYY" --> B["Parsing success?"]
B -- "Yes" --> C["Build $gte/$lt range filter"]
B -- "No" --> D["Fallback regex filter"]
```
<tr>
<td>
<details> …

[Bugfix] Datalayer: Add date filtering in form fields

---

forms-flow-web/src/routes/Submit/Forms/UserForm.js
forms-flow-web/src/routes/Submit/Submission/Item/ResubmitForm.js

JIRA: https://aottech.atlassian.net/browse/FWF-4988
DEPENDENCY PR: https://github.com/AOT-Technologies/forms-flow-ai-micro-front-ends/pull/744
Updated code for header visibility issue in anonymous forms
- **Link**: [#744](https://github.com/AOT-Technologies/forms-flow-ai-micro-front-ends/pull/744)
- **Status**: 🕐 Open
___
Enhancement
___
- Introduce `scrollableOverview` CSS class variable
- Dynamically assign container class in wizard display
- Update `UserForm.js` and `ResubmitForm.js` accordingly
___
```mermaid
flowchart LR
A["form.display"] -- "wizard?" --> B["user-form-container-with-wizard"]
A -- "other" --> C["user-form-container"]
B --> D["<div class='wizard-tab ...'/>"]
C --> D
``` …

FWF-4088:[Feature] - Custom header adjustment for vizard forms

---

forms-flow-data-layer/src/graphql/service/submission_service.py
forms-flow-data-layer/src/utils/datetime_utils.py

JIRA: 
https://aottech.atlassian.net/browse/FWF-5153
https://aottech.atlassian.net/browse/FWF-5156
DEPENDENCY PR:
- Fixed sorting on form fields to apply across the entire dataset, not just within individual pages.
- Updated list-type responses from the unified data layer query to be returned as comma-separated values.
___
___
- Fix cross-page sorting for form fields
- Enable pagination only when WebAPI sorts
- Join string lists into comma-separated values
- Add sorting/pagination debug logging
___
```mermaid
flowchart LR
A["submission_service.get_submission"] -- "detect sort field in WebAPI" --> B["is_sort_on_webapi_side"]
B -- "and no mongo filters" --> C["is_paginate_on_webapi_side=True"]
A -- "log decision" --> D["logger.info(...)"] …
```

[Bugfix] Datalayer: Fix sort on form fields working for individual pages  & Enhance list of string responses

---

forms-flow-web/src/routes/Design/Forms/FormEdit.js

JIRA: https://aottech.atlassian.net/browse/FWF-5173
DEPENDENCY PR: https://github.com/AOT-Technologies/forms-flow-ai-micro-front-ends/pull/755
Updated the text in Publish unpublish modal
- **Link**: [#755](https://github.com/AOT-Technologies/forms-flow-ai-micro-front-ends/pull/755)
- **Status**: 🕐 Open
___
Enhancement
___
- Update unpublish modal title and text
- Clarify impact on form and flow
- Adjust primary and secondary button labels
- Maintain publish flow unchanged
___
```mermaid
flowchart LR
A["FormEdit.js modal config"] -- "case 'unpublish'" --> B["Updated title/message"]
A -- "case 'unpublish'" --> C["Updated primary/secondary labels"]
B -- "Clarify scope: form & flow" --> D["User sees clearer messaging"]
```
<details> <summary><h3> File …

FWF-5173:[Feature] - Publish - Unpublish Modal Text Update

---

forms-flow-web/src/components/PrivateRoute.jsx

JIRA: https://aottech.atlassian.net/browse/FWF-5202
DEPENDENCY PR:
___
Bug fix
___
Fallback to stored language when Keycloak absent
Dispatch language from localStorage with default
Prevents undefined locale on submission view
Aligns language initialization across routes
___
```mermaid
flowchart LR
KC["Keycloak locale available?"] -- "Yes" --> UseKC["Use KC/tenant/selected LANGUAGE"]
KC -- "No" --> LS["Read 'lang' from localStorage or 'en'"]
UseKC -- "dispatch setLanguage" --> Store["Redux language set"]
LS -- "dispatch setLanguage" --> Store
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details> …

FWF-5202 : [HotFix] Fixed language error in history --> view submission page

---

forms-flow-web/src/routes/Submit/Submission/Item/ResubmitForm.js

JIRA: https://aottech.atlassian.net/browse/FWF-5221
DEPENDENCY PR:
Added a class in the header bar to set the spacing between layout and header. 
___
Enhancement
___
- Add `nav-bar` class to header
- Align header with global navigation
- Improve spacing on resubmit page
- No functional logic changes
___
```mermaid
flowchart LR
ResubmitFormJS["ResubmitForm.js header Card"]
CSSGlobal["Global nav-bar styles"]
UIResult["Aligned header spacing on resubmit page"]
ResubmitFormJS -- adds class "nav-bar" --> CSSGlobal
CSSGlobal -- applies spacing styles --> UIResult
```
<tr>
<td> …

FWF-5221:[Feature] - Updated Class in Resubmit Page

---

forms-flow-documents/src/formsflow_documents/services/pdf.py

JIRA: 
https://aottech.atlassian.net/browse/FWF-4928
DEPENDENCY PR:
- Added a method to copy template.html to the temporary directory for  PDF generation with a generic custom theme
**Issue** 
**Fixed**
___
___
- Copy `template.html` to temp dir
- Add `is_b64image` as Jinja global
- Handle PDFs without template variables
- Improve logging for template copy
___
```mermaid
flowchart LR
A["PDFService.create_pdf_from_custom_template"] -- "no template vars" --> B["copy_templates_to_temp"]
B -- "ensure template.html in temp" --> C["Jinja Environment"]
C -- "env.globals.update(is_signature)" --> D["Render HTML"]
D -- "rendered_html" --> E["Generate PDF"]
```
<table><thead><tr><th></th><th …

[🐛Bugfix] Documents-API: Fix custom pdf download extending template.html is failing

---

forms-flow-web/src/routes/Design/Forms/FormEdit.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-5191
https://jam.dev/c/84f9b51f-fb96-40a7-b8b6-6229ee5ace73
DEPENDENCY PR:
___
___
- Add modal guarding actions with unsaved changes
- Introduce pending action state management
- Gate duplicate/import when changes exist
- Reset pending state on modal close
___
```mermaid
flowchart LR
open["User selects action (Duplicate/Import)"]
check["Detect unsaved changes (form/workflow)"]
pend["Store pending action"]
modal["Show 'Unsaved Changes' confirm modal"]
stay["Stay in the Editor (cancel)"]
discard["Discard changes and continue"]
proceed["Proceed with selected action"]
reset["Reset selected/pending action on close"]
open -- "handleActionWithUnsavedCheck" --> check
check -- "changes present" --> pend …
```

FWF-5191 [bugfix] added new modal to indicate preventing action

---

.github/workflows/forms-flow-web-ci.yml

JIRA: 
DEPENDENCY PR:
- Commented web ci TEST step as we are not currently focusing on unit test case in frontend code. To be added again on a later stage
___
Enhancement
___
- Comment out web CI test job
- Preserve linting and build steps
- Disable Node 16 test matrix temporarily
- Keep workflow structure for future re-enable
___
```mermaid
flowchart LR
Lint["Lint job"] -- "unchanged" --> Build["Build job"]
TestJob["Test job"] -- "commented out" --> Workflow["Workflow"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>forms-flow-web-ci.yml</strong><dd><code>Disable Test job in web …

Commented web unit test step in web-ci workflow

---

forms-flow-web-root-config/src/index.ejs

JIRA: https://aottech.atlassian.net/browse/FWF-5335
DEPENDENCY PR: https://github.com/AOT-Technologies/forms-flow-ai-micro-front-ends/pull/809
Updated stylesheet with new font family 'Figtree'
- **Link**: [#809](https://github.com/AOT-Technologies/forms-flow-ai-micro-front-ends/pull/809)
- **Status**: 🕐 Open

FWF-5335-Typography Update in web.

---

docs/sequence-diagrams/client-flow.md
docs/sequence-diagrams/designer-flow.md
docs/sequence-diagrams/reviewer-flow.md

JIRA: 
DEPENDENCY PR:
- Refactor sequence diagrams for client and designer flows to enhance draft handling and clarify API interactions
**Client flow**
**Designer flow**
___
Documentation, Enhancement
___
- Refine client draft handling flow
- Expand designer update and publish steps
- Align API endpoints and notes
- Remove redundant reviewer submission retrieval
___
```mermaid
flowchart LR
A["Client flow diagrams"] -- "Drafts alt path, submit endpoint fix" --> B["Clear draft/update/submit"]
C["Designer flow diagrams"] -- "Create, update, workflow, publish" --> D["Audit/auth/process mapping clarified"]
E["Reviewer flow diagrams"] -- "Remove redundant submission fetch" --> F["Lean review sequence"]
``` …

FWF-5357: Update user journey flows sequential diagrams

---

forms-flow-web/src/routes/Design/Forms/FormEdit.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-5362
DEPENDENCY PR:
___
Bug fix
___
- Always show Layout header for viewers
- Keep actions gated by permissions
- Minor JSX condition cleanup
___
```mermaid
flowchart LR
perms["Permission flags: createDesigns, viewDesigns"]
header["Layout header rendering"]
actions["Preview/Save actions"]
perms -- "view or create" --> header
perms -- "create only" --> actions
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>FormEdit.js</strong><dd><code>Fix conditional rendering for Layout header</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

FWF-5362 [bugfix] removed  the permision unwantedly given

---

forms-flow-web/src/components/CustomComponents/NavigateBlocker.jsx
forms-flow-web/src/routes/Design/Forms/FormEdit.js

JIRA: [https://aottech.atlassian.net/browse/FWF-5218](https://aottech.atlassian.net/browse/FWF-5218)
DEPENDENCY PR: [https://github.com/AOT-Technologies/forms-flow-ai-micro-front-ends/pull/827](https://github.com/AOT-Technologies/forms-flow-ai-micro-front-ends/pull/827)
Common Modal replaced with new prompt modal

Feature/fwf 5218 UI modal

---

forms-flow-web-root-config/src/microfrontend-layout.html
forms-flow-web/src/components/App.jsx
forms-flow-web/src/components/BaseRouting.jsx
forms-flow-web/src/components/Form/constants/FormTable.js
forms-flow-web/src/routes/Design/Forms/List.js

JIRA: https://aottech.atlassian.net/browse/FWF-5338
DEPENDENCY PR: https://github.com/AOT-Technologies/forms-flow-ai-micro-front-ends/pull/829/files
--> Updated Global layout CSS classes
--> Added an example implementation in Designer Listing page. 
- **Link**: [#829](https://github.com/AOT-Technologies/forms-flow-ai-micro-front-ends/pull/829)
- **Status**: ✅ Merged

FWF-5338:[v8Feature] - Grid system Implementation

---

forms-flow-web/src/components/Modeler/Editors/BpmnEditor/BpmEditor.js
forms-flow-web/src/components/Modeler/Editors/Editor.scss

JIRA: https://aottech.atlassian.net/browse/FWF-5349
DEPENDENCY PR: https://github.com/AOT-Technologies/forms-flow-ai-micro-front-ends/pull/834
- **Link**: [#834](https://github.com/AOT-Technologies/forms-flow-ai-micro-front-ends/pull/834)
- **Status**: 🕐 Open
___
___
- Add visible border to BPMN canvas
- Add dark border to properties panel
___
```mermaid
flowchart LR
Canvas["BPMN canvas container"] -- "add border classes" --> UI["Improved visual boundary"]
PropsPanel["Properties panel"] -- "add dark border style" --> UI
```
<tr>
<td>
<details> …

FWF-5349 : [BugFix] resolved bpmn modeler ui issues

---

forms-flow-web/src/helper/convertFormDisplay.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-5401
Its a quick fix the panel not persist even the data is not getting from the response,rest of data are there while refresh[also its an edge case]
DEPENDENCY PR:
___
Bug fix
___
- Fix panel flattening in normal form
- Spread child components correctly
- Prevent nested array in output
___
```mermaid
flowchart LR
A["panel with components"] -- "flatten" --> B["spread children"]
C["non-panel component"] -- "push as-is" --> D["flattened list"]
B -- "append" --> D
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details> …

FWF-5401 [bugfix] updated the logic for converting form to wizard

---

CHANGELOG.md
forms-flow-api/src/formsflow_api/constants/__init__.py
forms-flow-api/src/formsflow_api/resources/form_process_mapper.py
forms-flow-api/src/formsflow_api/services/form_process_mapper.py
forms-flow-api/tests/unit/api/test_form_process_mapper.py

JIRA: 
https://aottech.atlassian.net/browse/FWF-5397
DEPENDENCY PR:
- Added a new endpoint to handle form, workflow, authorization, and settings creation

✨  [V8 feature] New post endpoint to perform combine form save operations in form design page
