AOT-Technologies/forms-flow-ai

CHANGELOG.md
forms-flow-idm/keycloak-setup.md
forms-flow-web/src/components/Application/List.js
forms-flow-web/src/components/Application/table.js

-In application dashboard, the "Application Status" column search component has been enhanced to show all possible values in dropdown (Component : forms-flow-web)
-In application dashboard, the button label has been modified to show as "Acknowledge" for status "Awaiting Acknowledgement" (Component : forms-flow-web)

Release v3.0.1

---

CHANGELOG.md
USAGE.md
deployment/README.md
forms-flow-api/src/api/models/application.py
forms-flow-bpm/README.md

Readme/changelog/Usage readme updates

Read me updates

---

forms-flow-web/src/components/Form/Item/Submission/index.js
forms-flow-web/src/components/ServiceFlow/constants/customEventTypes.js
forms-flow-web/src/components/ServiceFlow/details/ServiceTaskDetails.js

Save As Draft for Tasks

---

forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/controllers/AdminController.java

Changes to revoke create instance permission for Read access users.

---

.gitignore
deployment/docker/docker-compose-linux.yml
deployment/docker/docker-compose-windows.yml
forms-flow-analytics/sample.env
forms-flow-api/docker-compose-linux.yml
forms-flow-api/docker-compose-windows.yml
forms-flow-api/requirements.txt
forms-flow-api/requirements/dev.txt
forms-flow-api/requirements/prod.txt
forms-flow-api/src/api/__init__.py
forms-flow-api/src/api/config.py
forms-flow-api/src/api/models/__init__.py
forms-flow-api/src/api/models/application_history.py
forms-flow-api/src/api/resources/__init__.py
forms-flow-api/src/api/resources/application.py
forms-flow-api/src/api/resources/application_history.py
forms-flow-api/src/api/resources/checkpoint.py
forms-flow-api/src/api/resources/form_process_mapper.py
forms-flow-api/src/api/resources/process.py
forms-flow-api/src/api/services/__init__.py
forms-flow-api/src/api/services/application.py
forms-flow-api/src/api/services/form_process_mapper.py
forms-flow-api/src/api/services/process.py
forms-flow-api/src/api/services/task.py
forms-flow-api/src/api/utils/__init__.py
forms-flow-api/src/api/utils/profiler.py
forms-flow-bpm/docker-compose-linux.yml
forms-flow-bpm/docker-compose-windows.yml
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/listeners/execution/ExternalSubmissionListener.java
forms-flow-web/src/components/Form/Item/Submission/Item/index.js

Retry Logic + Other changes included

---

forms-flow-bpm/src/main/java/org/camunda/bpm/extension/keycloak/rest/RestApiSecurityConfigurationProperties.java
forms-flow-bpm/src/main/resources/application.yaml

* Upgrading bpm components - Spring boot, security etc.. (#573)
* Update CHANGELOG.md
Added release notes for 3.0.0 - 2020-10-07
* Update CHANGELOG.md
* Python API changes (#462)
Apo cleanup
* keycloak - removed unwanted parameter (#464)
* python hot-fix (#465)
* form approver action code changed (#469)
* vulnerability removed (#468)
* updated package lock
* updated for task-remove-on-completion (#471)
Co-authored-by: abhilash-aot <abhilash.kr@aot-technologies.com>
* Update application_history.py (#472)
* placeholder changed (#470)
* Fwf 771 submission cache issue (#476)
* updated for submission reload event
* Cache deleted of Formio
* FWF-779 applicationStatus-hidden-add-by-default (#477)
* updated version (#478)
* Changelog (#474)
* fix redash adding data source failing (#479)
* …

21 develop (#194)

---

forms-flow-bpm/src/main/java/org/camunda/bpm/extension/keycloak/rest/KeycloakAuthenticationFilter.java
forms-flow-bpm/src/test/java/org/camunda/bpm/extension/keycloak/rest/KeycloakAuthenticationFilterTest.java

JIRA: 
Issue Type: BUG/ FEATURE - Bug
Switching name to preferred username in AuthFilter

Switching name to preferred username in AuthFilter

---

forms-flow-api/src/formsflow_api/utils/translations/__init__.py
forms-flow-api/src/formsflow_api/utils/translations/translations.py
forms-flow-web/README.md
forms-flow-web/src/components/Form/Item/View.js

Adding translations as module

---

forms-flow-web/src/components/Form/Stepper.js

JIRA: 
form process failed for form upload

form upload issue for annonymous fixed

---

forms-flow-web/src/_tests_/test-helpers/user.test.js
forms-flow-web/src/components/ServiceFlow/list/TaskVariable.js

JIRA: 
1. fixed the value on task variable as a string

fixed taskvariable-value-format-fix

---

forms-flow-web/package-lock.json
forms-flow-web/package.json
forms-flow-web/src/_tests_/test-helpers/user.test.js

JIRA: 
added 
"async": "3.2.2"
in resolutions

updated vulnerability fixes for web side

---

forms-flow-web/src/actions/formActions.js
forms-flow-web/src/components/Form/Item/index.js
forms-flow-web/src/components/Form/Stepper.js

JIRA: 
The error message is not getting cleared when we move on to the next page

reset the form before each submission

---

forms-flow-web/src/components/Form/List.js

updated error message if json file structure not correct

---

CHANGELOG.md

changelog updated with camunda feature changes

---

README.md

updated badge

---

forms-flow-web/src/_tests_/test-helpers/user.test.js
forms-flow-web/src/components/ServiceFlow/list/TaskVariable.js

Taskvariable value format fix

---

forms-flow-web/package.json

JIRA: 
Issue Type:FEATURE
updated package version

updated package version

---

forms-flow-web/package.json

JIRA: 
Version Update from v4.0.5 to v4.0.6

Version Update

---

forms-flow-web/src/services/UserService.js

updated keycloak refresh token calling by dynamic 

---

forms-flow-forms/sample.env

JIRA: 
BUG - sample.env file Missing
Added the Sample.env file for forms-flow-forms

added sample.env back to forms

---

forms-flow-forms/sample.env

JIRA: 
Bug - Missing forms-flow-forms sample.env
Added Missing forms-flow-forms sample.env

Added Missing forms-flow-forms sample.env

---

forms-flow-web/src/components/Form/Stepper.js
forms-flow-web/src/components/Form/Steps/WorkFlow.js

JIRA: 
1. default work flow fixed to form upload
2. removed yes or no question before selecting workflow

default  workflow 

---

forms-flow-web/src/components/Form/List.js

JIRA: 
added try and catch to catch error

updated error message for unsupported json file added

---

forms-flow-web/public/index.html
forms-flow-web/src/components/Form/FileUpload/SelectFormForDownload.js
forms-flow-web/src/components/Form/List.js
forms-flow-web/src/containers/NavBar.jsx
forms-flow-web/src/styles.scss

Accessibility

---

forms-flow-web/src/components/Dashboard/Dashboard.js

fixed metrics ui issue

---

forms-flow-bpm/src/main/java/org/camunda/bpm/extension/commons/connector/support/TextAnalyzerAccessHandler.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/delegates/FormTextAnalysisDelegate.java

changes - fixes for the analysis code

changes - fixes for the analysis code

---

forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/delegates/FormTextAnalysisDelegate.java

Fixes for the analysis code

---

.github/workflows/forms-flow-data-analysis-api-cd.yml
forms-flow-data-analysis-api/src/api/__init__.py

Disabling DB init if DB support is not enabled 

---

forms-flow-web/src/_tests_/test-components/test-form/index.test.js
forms-flow-web/src/components/Dashboard/StatusChart.js
forms-flow-web/src/components/ServiceFlow/constants/taskConstants.js
forms-flow-web/src/constants/taskConstants.js

fixed task list sorting

---

forms-flow-data-analysis-api/tests/unit/api/test_sentiment_analysis.py
forms-flow-data-analysis-api/tests/unit/services/test_sentiment_analysis.py

JIRA: 
Unit test updates for sentiment analysis API response variable names changes

Update in test file for response variable changes

---

CODEOFCONDUCT.md
CODEOWNERS
CONTRIBUTING.md

Adding Code of Conduct, code owners and contribute guidelines

---

forms-flow-web/src/assets/styles/user-styles.css
forms-flow-web/src/components/Footer/Footer.js
forms-flow-web/src/components/Form/Stepper.js
forms-flow-web/src/components/Form/Steps/WorkFlow.js
forms-flow-web/src/components/Form/stepper.scss
forms-flow-web/src/constants/constants.js
forms-flow-web/src/containers/NavBar.jsx
forms-flow-web/src/styles.scss

JIRA: 
1. updated buttons
2. footer font size
3. cursor pointer on navbar
4. task variable will avoid html elements from form

updated ui

---

forms-flow-web/src/components/Form/Item/Edit.js
forms-flow-web/src/components/Form/Item/Submission/Item/View.js
forms-flow-web/src/components/Form/Item/View.js
forms-flow-web/src/components/Form/List.js
forms-flow-web/src/components/Form/Steps/SaveNext.js
forms-flow-web/src/components/Loading/Loading.js
forms-flow-web/src/components/Nodata/Nodata.js
forms-flow-web/src/resourceBundles/bg/resourceBundles.js
forms-flow-web/src/resourceBundles/de/resourceBundles.js
forms-flow-web/src/resourceBundles/en/resourceBundles.js
forms-flow-web/src/resourceBundles/formio_resourceBundles.js
forms-flow-web/src/resourceBundles/fr/resourceBundles.js
forms-flow-web/src/resourceBundles/pt/resourceBundles.js
forms-flow-web/src/resourceBundles/zh/resourceBundles.js

Internationalization updates

---

.github/workflows/forms-flow-api-ci.yml
deployment/docker/docker-compose-linux.yml
deployment/docker/docker-compose-windows.yml
forms-flow-api/docker-compose-linux.yml
forms-flow-api/docker-compose-windows.yml
forms-flow-bpm/docker-compose-linux.yml
forms-flow-bpm/docker-compose-windows.yml
forms-flow-idm/keycloak/docker-compose.yml

Reverts AOT-Technologies/forms-flow-ai#300

Revert "Removed latest tag from every docker image and changed it to the latest stable version."

---

forms-flow-web/src/apiManager/services/processServices.js
forms-flow-web/src/components/Admin/Insightdashboard.js
forms-flow-web/src/components/Form/FileUpload/fileUploadModal.js
forms-flow-web/src/components/Form/List.js
forms-flow-web/src/components/Form/Steps/TaskvariableCreate.js
forms-flow-web/src/components/Form/Steps/WorkFlow.js
forms-flow-web/src/components/ServiceFlow/constants/taskConstants.js
forms-flow-web/src/resourceBundles/bg/resourceBundles.js
forms-flow-web/src/resourceBundles/de/resourceBundles.js
forms-flow-web/src/resourceBundles/en/resourceBundles.js
forms-flow-web/src/resourceBundles/formio_resourceBundles.js
forms-flow-web/src/resourceBundles/fr/resourceBundles.js
forms-flow-web/src/resourceBundles/pt/resourceBundles.js
forms-flow-web/src/resourceBundles/zh/resourceBundles.js

JIRA: 
Added more translations for pop-up messages and other pending fields

translations updated

---

forms-flow-web/src/components/ServiceFlow/ServiceFlow.scss
forms-flow-web/src/components/ServiceFlow/index.js
forms-flow-web/src/components/ServiceFlow/list/ServiceTaskList.js
forms-flow-web/src/components/ServiceFlow/list/TaskVariable.js
forms-flow-web/src/containers/NavBar.jsx
forms-flow-web/src/styles.scss

Task list new UI with card style

---

forms-flow-data-analysis-api/entrypoint

JIRA: 
Temporary fix for the issue https://aottech.atlassian.net/browse/FWF-1392
Commented the DB commands in entrypoint.sh
Docker build successfully.
Tested the endpoint for sentiment analysis

data analysis API/DB configuration support

---

forms-flow-web/src/components/Admin/Insightdashboard.js
forms-flow-web/src/components/Admin/insightDashboard.scss

updated chip model on admin

---

forms-flow-api/src/formsflow_api/utils/translations/translations.py
forms-flow-web/README.md
forms-flow-web/src/components/Application/historyTable.js

* Updated translations.py
JIRA: 
Added German translation for messages

Internationalization updates (#4)

---

forms-flow-web/src/components/Admin/Insightdashboard.js
forms-flow-web/src/components/Application/table.js
forms-flow-web/src/components/Form/FileUpload/SelectFormForDownload.js
forms-flow-web/src/components/Form/List.js
forms-flow-web/src/constants/constants.js
forms-flow-web/src/containers/Confirm.js
forms-flow-web/src/modules/bpmFormReducer.js
forms-flow-web/src/modules/index.js
forms-flow-web/src/styles.scss

JIRA: 
Form page buttons font size and delete icon sizes are changed
Application date range picker changed
delete confirmation modal buttons changed
[image](https://user-images.githubusercontent.com/98075058/167618978-6f98b48f-1e3b-4b3e-8b61-b76ad2bc4d82.png)
[image](https://user-images.githubusercontent.com/98075058/167619276-75dce472-fdf0-4f0b-8833-b9419e8ff976.png)\

form page updated

---

forms-flow-web/src/components/Application/List.js
forms-flow-web/src/components/Form/Item/Submission/List.js
forms-flow-web/src/components/Form/List.js

Forms, Application, form Submission heading alignments corrected

Forms,  Applications and Form Submission headdings alignment

---

forms-flow-web/src/components/Form/Item/Submission/List.js

view Submission  heading alignments 
issue:
resolved:

view Submission  heading alignments corrected

---

.github/workflows/forms-flow-web-ci.yml
forms-flow-web/package.json
forms-flow-web/src/_tests_/test-components/test-error/index.test.js
forms-flow-web/src/_tests_/test-components/test-form/stepper.test.js
forms-flow-web/src/_tests_/test-components/test-serviceflow/constants.js

JIRA: 
Added lining check for web ci
As of now, the lint check was not in place even though ci was running

adding eslint to web-ci

---

deployment/docker/bundle/configuration/docker-compose.yml

1. The older v4.0.5 tag has been removed
2. Added the latest tag that has the latest version of master.

Updated docker-compose.yml with latest tag

---

forms-flow-web/src/components/Admin/Insightdashboard.js

no dashboard found message fixed

---

forms-flow-api/src/formsflow_api/config.py
forms-flow-api/src/formsflow_api/resources/form_process_mapper.py
forms-flow-api/src/formsflow_api/utils/translations/translations.py
forms-flow-api/tests/unit/api/test_form_process_mapper.py

JIRA: 
Response of form put method updated.
_**Current response**_
_**Updated response**_

Response change for form_process_mapper put method

---

forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/RestResource.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/RestResourceExceptionHandler.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/TaskRestResource.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/TaskRestResourceImpl.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/UserRestResource.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/UserRestResourceImpl.java

Rest resources added

---

forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/TaskRestResource.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/TaskRestResourceImpl.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/UserRestResource.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/UserRestResourceImpl.java

Bpm gateway - version added

---

forms-flow-bpm/Dockerfile
forms-flow-bpm/pom.xml
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/UserRestResource.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/UserRestResourceImpl.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/dto/UserProfileDto.java

pom-docker -> pom changes + user dto included

pom-docker -> pom changes + user dto included

---

forms-flow-web/src/components/Form/Create.js
forms-flow-web/src/components/Form/Item/Edit.js

JIRA: 
Accessibilty of create page improved upto 91%
[image](https://user-images.githubusercontent.com/98075058/168547012-9109c662-7d4a-4a9b-9737-b01d8f1d0c47.png)

create accessibilty improved

---

.github/workflows/forms-flow-bpm-ci.yml
forms-flow-bpm/openshift_custom_Dockerfile

JIRA: 
Filename change from pom-docker.xml to pom.xml in GitHub workflow file.

Update in bpm github workflow file

---

forms-flow-bpm/README.md
forms-flow-bpm/docker-compose.yml
forms-flow-bpm/sample.env
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/commons/connector/HTTPServiceInvoker.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/commons/connector/support/ApplicationAccessHandler.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/commons/connector/support/BPMAccessHandler.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/commons/connector/support/FormAccessHandler.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/commons/connector/support/IAccessHandler.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/commons/connector/support/TextAnalyzerAccessHandler.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/UserRestResource.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/UserRestResourceImpl.java
forms-flow-bpm/src/main/resources/application.yaml

New exchange added for bpm source camunda

New exchange added for bpm source camunda

---

forms-flow-api/src/formsflow_api/models/base_model.py

JIRA: 
https://aottech.atlassian.net/browse/FWF-1326
Application name filtering with StartCase string 
Good to merge

application filter by application name made space insensitive

---

forms-flow-web/src/apiManager/services/metricsServices.js
forms-flow-web/src/components/Dashboard/Dashboard.js

JIRA: 
The error case has been handled during no data found when date range changed
[image](https://user-images.githubusercontent.com/98075058/168610058-805ec686-7d9d-41e9-859f-b804c936ef56.png)

Metrics load error

---

forms-flow-data-analysis-api/src/api/utils/logging.py
forms-flow-data-analysis-api/tests/conftest.py

Data analysis API logging bugfix

---

forms-flow-web/src/apiManager/services/processServices.js
forms-flow-web/src/components/Form/Create.js
forms-flow-web/src/components/Form/Item/Edit.js
forms-flow-web/src/components/Form/Stepper.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-1424
*Updated the code to support mapper versioning*
*code refactor -> improved readability*
*Unit tests, Manual verification*

Fwf 1424/web versioning refactor

---

forms-flow-web/src/apiManager/services/formatterService.js
forms-flow-web/src/components/ServiceFlow/details/ServiceTaskDetails.js
forms-flow-web/src/components/ServiceFlow/details/TaskHeader.js
forms-flow-web/src/components/ServiceFlow/list/ServiceTaskList.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-1377
Added tenant-specific endpoint for process diagrams on the tasks page
The task page update was missing in the previous PR

Tenant specific process diagram for tasks

---

.github/workflows/forms-flow-data-analysis-api-ci.yml
forms-flow-data-analysis-api/requirements/dev.txt
forms-flow-data-analysis-api/setup.cfg
forms-flow-data-analysis-api/src/api/config.py
forms-flow-data-analysis-api/src/api/utils/__init__.py
forms-flow-data-analysis-api/tests/conftest.py
forms-flow-data-analysis-api/tests/docker/docker-compose.yml
forms-flow-data-analysis-api/tests/docker/realms/forms-flow-ai-realm.json
forms-flow-data-analysis-api/tests/unit/api/test_sentiment_analysis.py
forms-flow-data-analysis-api/tests/utilities/base_test.py

Adding JWT mock and keycloak docker mock for data analysis api to master

Adding JWT mock and keycloak docker mock

---

deployment/docker/docker-compose-linux.yml
deployment/docker/docker-compose-windows.yml
deployment/docker/sample.env
forms-flow-forms/docker-compose.yml
forms-flow-forms/sample.env

updated formio docker-compose file and env

---

forms-flow-web/src/components/Form/Item/Edit.js
forms-flow-web/src/components/Form/Stepper.js

JIRA: 
[issue link
](https://aottech.atlassian.net/browse/FWF-1424)
Added missing edge case in case of handling uploaded forms

added missing uploaded form edge case for versioning

---

forms-flow-api/src/formsflow_api/resources/dashboards.py
forms-flow-api/src/formsflow_api/resources/groups.py
forms-flow-api/src/formsflow_api/services/external/analytics_api.py
forms-flow-api/src/formsflow_api/services/external/keycloak.py
forms-flow-api/src/formsflow_api/services/factory/__init__.py
forms-flow-api/src/formsflow_api/services/factory/keycloak_admin.py
forms-flow-api/src/formsflow_api/services/factory/keycloak_client_service.py
forms-flow-api/src/formsflow_api/services/factory/keycloak_factory.py
forms-flow-api/src/formsflow_api/services/factory/keycloak_group_service.py

Changes to support client roles for dashboard management

---

forms-flow-web/src/components/Dashboard/Dashboard.js
forms-flow-web/src/resourceBundles/bg/resourceBundles.js
forms-flow-web/src/resourceBundles/de/resourceBundles.js
forms-flow-web/src/resourceBundles/en/resourceBundles.js
forms-flow-web/src/resourceBundles/formio_resourceBundles.js
forms-flow-web/src/resourceBundles/fr/resourceBundles.js
forms-flow-web/src/resourceBundles/pt/resourceBundles.js
forms-flow-web/src/resourceBundles/zh/resourceBundles.js

JIRA: 
Added translations for new updations on UI

Translations for new UI updation

---

forms-flow-web/src/components/Form/Item/Edit.js

JIRA: 
[issue link](https://aottech.atlassian.net/browse/FWF-1444)
Updated condition to send POST request only when form name is changed in Edit component.
Bug fix while changing form to be anonymous new version is being created which was not needed

Bugfix - Version updating on making the form Anonymous 

---

forms-flow-web/src/components/Form/Item/Submission/List.js

JIRA: 
[issue link](https://aottech.atlassian.net/browse/FWF-901)
Added applicationId query for the submissions List API

applicationId regex query for submission list call

---

forms-flow-web/src/components/Form/Item/Submission/Item/index.js
forms-flow-web/src/components/Form/Item/Submission/index.js
forms-flow-web/src/components/Form/List.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-1445
Removed view submissions button and route

solves FWF-1445

---

forms-flow-bpm/pom.xml
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/controllers/AdminController.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/controllers/TaskController.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/service/impl/AdminRestServiceImpl.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/keycloak/plugin/KeycloakIdentityProviderFactory.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/keycloak/plugin/KeycloakIdentityProviderSession.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/keycloak/rest/KeycloakAuthenticationFilter.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/keycloak/sso/KeycloakAuthenticationProvider.java
forms-flow-bpm/src/test/java/org/camunda/bpm/extension/hooks/controllers/AdminControllerTest.java
forms-flow-bpm/src/test/java/org/camunda/bpm/extension/hooks/controllers/TaskControllerTest.java
forms-flow-bpm/src/test/java/org/camunda/bpm/extension/keycloak/rest/KeycloakAuthenticationFilterTest.java

Spring Boot + camunda keycloak upgrade

Bpm upgrade

---

forms-flow-web/src/components/Form/Steps/TaskvariableCreate.js
forms-flow-web/src/components/Form/Steps/WorkFlow.js

JIRA: 
1. fixed workflow changes
2. fixed empty task variable adding

fixed workflow change

---

forms-flow-web/src/components/PrivateRoute.jsx
forms-flow-web/src/components/ServiceFlow/index.js
forms-flow-web/src/components/ServiceFlow/list/ServiceTaskList.js

JIRA: 
[Tasklist bug in rendering](https://aottech.atlassian.net/browse/FWF-1415)
Added memorization to custom routes to handle false positives on route update
issue fixed after memoizing the custom routes, the issue was even though really the path isn't changed the path is actually updating which causes the rerender, my guess is the native Route would be properly memorized and only update when there is an actual difference in the path. takeaway: Route changes always trigger a rerender even if the path is actually the same unless it's properly memoized.

Task list bug in UI rendering

---

forms-flow-web/src/components/Form/Create.js
forms-flow-web/src/services/UserService.js

JIRA: 
1. form create with multi tenant key 
2. forms fetch depending on multi tenant key

Multi tenancy web- form create and fetch 

---

forms-flow-web/src/components/Form/List.js

JIRA: 
1.tenant key added on form upload

updated tenant key on form upload

---

forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/controllers/AdminController.java

multitenant user query service - adding to admin for authorization

multitenant user query service - adding to admin for authorization

---

CONTRIBUTING.md

JIRA: 
Added JavaScript Styleguide to CONTRIBUTING.MD

Guidelines

---

forms-flow-web/src/apiManager/services/processServices.js
forms-flow-web/src/components/Form/Create.js
forms-flow-web/src/components/Form/Item/Edit.js
forms-flow-web/src/components/Form/List.js
forms-flow-web/src/helper/helper.js

JIRA: 
Update with adding and removing tenant key on 
1. Check path and name of form on upload 
2. Path and Name on create or edit

updated with form upload and fixed path and name of form with tenant key

---

forms-flow-web/src/components/Form/Create.js
forms-flow-web/src/components/Form/Item/Edit.js
forms-flow-web/src/containers/styles.scss

info added to create and edit

---

forms-flow-web/src/customFormioComponents/FileUpload/fileUpload.js
forms-flow-web/src/customFormioComponents/FileUpload/fileUpload.settingsForm.js
forms-flow-web/src/customFormioComponents/FileUpload/fileUploadInputComponent.jsx
forms-flow-web/src/customFormioComponents/index.js
forms-flow-web/src/styles.scss

CMIS File Upload Custom Component
Created a custom component for CMIS server

CMIS File Upload Custom Component

---

forms-flow-bpm/src/main/java/org/camunda/bpm/extension/keycloak/plugin/KeycloakUserService.java

Fix issue with camunda error for admin login

---

forms-flow-web/src/customFormioComponents/FileUpload/fileUploadInputComponent.jsx

the uplad butten will be shown along with the selected file details

UI changes on CMIS file upload component

---

forms-flow-web/src/customFormioComponents/FileUpload/fileUploadInputComponent.jsx
forms-flow-web/src/styles.scss

Added the base64 to convert and display the file which is selectec to upload.

CMIS File upload custom component UI changes

---

forms-flow-web/src/containers/NavBar.jsx

JIRA: 
https://aottech.atlassian.net/browse/FWF-1467
Accessibility fix
Solved some critical issues of Form and Admin

Accessibility fix

---

forms-flow-web/src/apiManager/endpoints/index.js
forms-flow-web/src/apiManager/services/cmisService.js
forms-flow-web/src/customFormioComponents/FileUpload/fileUploadInputComponent.jsx
forms-flow-web/src/styles.scss

Cmis connector

---

forms-flow-api/src/formsflow_api/resources/__init__.py
forms-flow-api/src/formsflow_api/resources/cmis_connector.py
forms-flow-api/src/formsflow_api/services/external/cmislib/atompub/binding.py

JIRA: 
Added content type to cmis file upload 

Content type added to cmis file upload

---

forms-flow-api/src/formsflow_api/resources/cmis_connector.py

JIRA: 
cmis download API response  data changed from binary to base64

cmis download API response  update

---

forms-flow-web/src/components/ServiceFlow/constants/taskConstants.js

JIRA: 
changed the Key from Created to created

create filter not working issue fixed

---

forms-flow-web/src/components/Form/Item/Edit.js

fixed anonymous check

---

forms-flow-web/src/components/Form/Create.js
forms-flow-web/src/components/Form/Item/Edit.js

updated with info

---

forms-flow-web/src/customFormioComponents/FileUpload/fileUpload.js
forms-flow-web/src/customFormioComponents/FileUpload/fileUploadInputComponent.jsx
forms-flow-web/src/styles.scss

Created Custom component for CMIS 
Feature:  Saveing  and retriving the uploaded file in CMI Server and the file name in Form.io. 
Screenshots: 
1. form: 
2. On selecting the file to upload ( if the uploaded file is a type of jpg or png will show a preview of the same:
3. After the upload shows the file name only
View 
1.  The name of the file fetching from form.io
2.  on click of download will download the image from CMI server and if the file is a type of jpj or png it will show a preview.

CMIS File upload custom component -- compleat functionalities

---

forms-flow-web/src/customFormioComponents/FileUpload/fileUpload.js
forms-flow-web/src/customFormioComponents/FileUpload/fileUploadInputComponent.jsx

changed the ui at form desinging part

Custom components name changed as CMIS file upload

---

forms-flow-web/src/customFormioComponents/FileUpload/fileUploadInputComponent.jsx

ui changed in file upload form designing

fix on ui in cms file upload component

---

forms-flow-web/src/customFormioComponents/FileUpload/fileUploadInputComponent.jsx

ui changes in file upload component

---

forms-flow-api/src/formsflow_api/config.py

JIRA: 
Change in formio url paramerter in config.py file.

Change in formio config parameter 

---

.github/workflows/forms-flow-data-analysis-api-cd.yml
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/service/impl/AdminRestServiceImpl.java

Add deployment authorization to designers

---

.github/workflows/forms-flow-api-cd.yml
.github/workflows/forms-flow-bpm-cd.yml
.github/workflows/forms-flow-bpm-ci.yml
.github/workflows/forms-flow-data-analysis-api-cd.yml
.github/workflows/forms-flow-web-cd.yml

GHA Cleanup

---

forms-flow-bpm/src/main/resources/application.yaml

cookie max age + secure mechanism added

---

forms-flow-web/src/customFormioComponents/Google-Map/GMapservice.js
forms-flow-web/src/customFormioComponents/Google-Map/Google_Map.js

Created new Google Map Custom component for NRS Demo

removed consoles and formated code

---

forms-flow-bpm/api-spec/forms-flow-bpm-api-spec.yaml

spec changes for authorization api

---

forms-flow-web/src/components/Form/Item/View.js

JIRA: https://aottech.atlassian.net/browse/FWF-1498
BUG
Fixed authentication check on view form

fixed authentication checking

---

forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/exceptions/FormsflowInternalException.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/ProcessDefinitionRestResource.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/dto/ProcessDefinitionDto.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/impl/ProcessDefinitionRestResourceImpl.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/service/AbstractRestService.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/service/ProcessDefinitionRestService.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/service/impl/AdminRestServiceImpl.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/service/impl/ProcessDefinitionRestServiceImpl.java
forms-flow-web/src/apiManager/endpoints/config.js
forms-flow-web/src/apiManager/endpoints/index.js
forms-flow-web/src/apiManager/services/bpmTaskServices.js
forms-flow-web/src/apiManager/services/processServices.js

/proces-definition - API moved from api to bpm gateway . web-api process def to set for deletion

---

forms-flow-web/src/actions/formActions.js
forms-flow-web/src/apiManager/services/FormServices.js
forms-flow-web/src/components/Form/Create.js
forms-flow-web/src/components/Form/Item/Edit.js
forms-flow-web/src/components/Form/Item/View.js
forms-flow-web/src/components/Form/List.js
forms-flow-web/src/helper/helper.js

tenant key check fixed

---

forms-flow-data-analysis-api/requirements/prod.txt
forms-flow-data-analysis-api/src/api/config.py
forms-flow-data-analysis-api/src/api/resources/sentiment_analysis.py
forms-flow-data-analysis-api/src/api/services/transformers.py
forms-flow-data-analysis-api/src/api/utils/auth.py
forms-flow-data-analysis-api/tests/unit/api/test_sentiment_analysis.py
forms-flow-data-analysis-api/tests/utilities/base_test.py

JIRA: 
Issue Type: FEATURE ✨ 
https://aottech.atlassian.net/browse/FWF-1487
Modified the `/sentiment` endpoint to return the prediction confidence 
Modified the request payload and response schema 
Refactor -> batch inference removed
TODO:

Feat: Updating inference API response with prediction confidence score

---

forms-flow-api/src/formsflow_api/services/external/bpm.py
forms-flow-bpm/api-spec/forms-flow-bpm-api-spec.yaml
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/ProcessDefinitionRestResource.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/service/impl/ProcessDefinitionRestServiceImpl.java

process definition start API moved to ext API set

---

jobs/sentiment-analysis/config.py
jobs/sentiment-analysis/sentiment_analysis.py

JIRA: 
Issue Type: FEATURE ✨ 
Updated the jobs component to accommodate modified data analysis data contract
Added new env variable `DATABASE_OUTPUT_COLUMN_CONFIDENCE` to specify the column where the confidence score needs  to be updated

Feat: sentiment jobs update for sentiment analysis v2

---

forms-flow-web/src/components/Admin/Insightdashboard.js
forms-flow-web/src/components/Admin/index.js
forms-flow-web/src/components/Application/List.js
forms-flow-web/src/components/Application/historyTable.js
forms-flow-web/src/components/Application/table.js
forms-flow-web/src/components/Dashboard/Dashboard.js
forms-flow-web/src/components/Footer/Footer.js
forms-flow-web/src/components/Insights/Insights.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-1467
Updated accessibility fix for different pages

Fwf 1467 accessibility

---

forms-flow-api/src/formsflow_api/models/application.py
forms-flow-api/src/formsflow_api/resources/metrics.py
forms-flow-api/src/formsflow_api/schemas/aggregated_application.py
forms-flow-api/src/formsflow_api/services/application.py

JIRA: https://aottech.atlassian.net/browse/FWF-1365
Added pagination, sorting, searching to metrics API
postman
1. http://192.168.16.145:5000/metrics?from=2022-05-31T18:30:00%2B00:00&to=2022-06-29T18:30:00%2B00:00&orderBy=created&pageNo=1&limit=5&sortBy=formName&sortOrder=asc
2. http://192.168.16.145:5000/metrics?from=2022-05-31T18:30:00%2B00:00&to=2022-06-29T18:30:00%2B00:00&orderBy=created&pageNo=1&limit=5&formName=new
3. http://192.168.16.145:5000/metrics?from=2022-05-31T18:30:00%2B00:00&to=2022-06-29T18:30:00%2B00:00&orderBy=created&pageNo=1&limit=5

metrics pagination, sorting, searching

---

forms-flow-bpm/src/main/java/org/camunda/bpm/extension/commons/connector/HTTPServiceInvoker.java

JIRA: 
https://aottech.atlassian.net/browse/FWF-1505

avoids Invalid/empty configuration for finding access handler class

---

VERSION
forms-flow-api/setup.cfg
forms-flow-bpm/pom-default.xml
forms-flow-bpm/pom.xml
forms-flow-forms/api-spec/forms-flow-forms-api-spec.yaml
forms-flow-web/package.json

Version upgrade

---

forms-flow-api/src/formsflow_api/services/external/base_bpm.py
forms-flow-api/src/formsflow_api/services/external/bpm.py

Changes to parse bpm response

---

forms-flow-web/src/components/Form/FormOperations/FormOperations.js

JIRA: 
the issue of redirecting to multi tenancy while clicking view/edit or submitting form is fixed
[image](https://user-images.githubusercontent.com/98075058/177503885-962e566f-24fb-4ac3-a4c8-ae3e64c998e7.png)

Multitenancy url fix

---

deployment/docker/docker-compose.yml
forms-flow-web/README.md
forms-flow-web/docker-compose.yml
forms-flow-web/package.json
forms-flow-web/sample.env

JIRA: 
Issue Type: BUG 🐛 
- Updated build script with disabling source map
- Removed source map envs
- updated default node env to production

Disabled source map for web

---

forms-flow-web/src/components/Form/List.js
forms-flow-web/src/resourceBundles/bg/resourceBundles.js
forms-flow-web/src/resourceBundles/de/resourceBundles.js
forms-flow-web/src/resourceBundles/en/resourceBundles.js
forms-flow-web/src/resourceBundles/fr/resourceBundles.js
forms-flow-web/src/resourceBundles/pt/resourceBundles.js
forms-flow-web/src/resourceBundles/zh/resourceBundles.js
forms-flow-web/src/styles.scss

JIRA: 
table header size changes and no forms found message also changed
[image](https://user-images.githubusercontent.com/98075058/177771785-0da3050b-7f28-4f5c-97dd-4b7573527f27.png)
[image](https://user-images.githubusercontent.com/98075058/177771856-e39575b6-0663-4c25-815c-6ac98d6e9891.png)

React table fix

---

forms-flow-api/src/formsflow_api/resources/form_process_mapper.py
forms-flow-api/src/formsflow_api/static/js/from_io_render.js
forms-flow-api/src/formsflow_api/templates/index.html
forms-flow-api/src/formsflow_api/utils/pdf.py

Export form wizard and tab [fixed review comments]

---

forms-flow-api/tests/docker/docker-compose.yml

JIRA: 
Issue Type: CI build fix 💚 
- forms flow forms spec URL updated to point to the opensource repo
Unit tests, Integration tests, Manual verification
The stoplight spec URL for forms flow forms was pointing towards a stale branch

updated formsflow forms stoplight api spec url

---

forms-flow-api/src/formsflow_api/utils/pdf.py

Solving permission error for seleniumwire in openshift

---

forms-flow-api/src/formsflow_api/static/js/from_io_render.js
forms-flow-web/src/styles.scss

Fixed Nested forms pdf export

---

forms-flow-web/src/containers/NavBar.jsx
forms-flow-web/src/containers/SideBar.jsx
forms-flow-web/src/helper/helper.js
forms-flow-web/src/helper/regExp/pathMatch.js

JIRA: 
Issue Type: BUG 🐛 
https://aottech.atlassian.net/browse/FWF-1454
- Created a regEx helper module to generate dynamic regEx for different environments.
- Modified path matching to use the new module 

🐛 : Fix for tab highlighting for current path in multitenant environment 

---

forms-flow-web/src/components/Form/Item/Submission/Item/Edit.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-1507
Loading issue fixed

Loading issue fixed

---

forms-flow-web/src/components/Dashboard/Dashboard.js

Removed "click to go back" button on wrong search. 
Removed closs button from the date range picker
corrected pagination bugs after the wrong search

Metrics pagination bugs removed

---

forms-flow-web/src/apiManager/services/metricsServices.js
forms-flow-web/src/components/Dashboard/Dashboard.js

Metrics pagination and search

---

forms-flow-bpm/src/test/java/org/camunda/bpm/extension/hooks/listeners/task/AccessGrantNotifyListenerTest.java

Added test cases for AccessGrantNotifyListener

Added test cases for AccessGrantNotifyListener

---

forms-flow-bpm/src/main/java/org/camunda/bpm/extension/commons/utils/VariableConstants.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/listeners/ApplicationAuditListener.java

JIRA: 
Issue Type: BUG :bug:
Populate submitted by as "service account" in application history when the Task is not performed by human
**Current behavior :**
**Expected:**

Populate submitted by as "service account" in application history for task not performed by user

---

forms-flow-web/src/_tests_/test-components/test-form/test-item/view.test.js
forms-flow-web/src/components/Form/Item/View.js

fixed  Jira ticket  https://aottech.atlassian.net/browse/FWF-1510

Public form authentification  fixed

---

forms-flow-web/package-lock.json
forms-flow-web/package.json
forms-flow-web/src/_tests_/test-components/test-dashboard/dashboard.test.js
forms-flow-web/src/apiManager/services/metricsServices.js
forms-flow-web/src/components/Dashboard/Dashboard.js

* metrics pagination updated
JIRA: 
metrics pagination, search and sort  are converted to server side

Metrics pagination (#1)

---

forms-flow-web/src/containers/NavBar.jsx
forms-flow-web/src/modules/userDetailReducer.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-1528
View submission page dropdown issue fixed

Dropdown issue fix

---

forms-flow-api/Dockerfile
forms-flow-web/src/components/Form/Item/Submission/Item/View.js

Docker file update chrome stable version

---

deployment/docker/docker-compose.yml
forms-flow-api/Dockerfile
forms-flow-api/src/formsflow_api/models/application.py
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/commons/connector/HTTPServiceInvoker.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/commons/connector/support/FormAccessHandler.java
forms-flow-forms/docker-compose.yml
forms-flow-web/src/apiManager/services/bpmFormServices.js
forms-flow-web/src/apiManager/services/bpmServices.js
forms-flow-web/src/components/Application/historyTable.js
forms-flow-web/src/components/Form/List.js
forms-flow-web/src/components/PublicRoute.jsx
forms-flow-web/src/services/UserService.js

Formadapter new

---

forms-flow-api/src/formsflow_api/app.py
forms-flow-api/src/formsflow_api/resources/form_process_mapper.py
forms-flow-api/src/formsflow_api/resources/formio.py
forms-flow-api/src/formsflow_api/schemas/formio_roles.py
forms-flow-api/src/formsflow_api/utils/enums.py
forms-flow-api/src/formsflow_api/utils/util.py
forms-flow-api/tests/unit/api/test_formio.py
forms-flow-api/tests/utilities/base_test.py

-  `/formio/roles` response format updated to match admin API
-  Updated test cases to cover known possible cases
- Improved code quality

👽 : Role API updated response format.

---

CHANGELOG.md
README.md
forms-flow-web/package-lock.json
forms-flow-web/src/components/Form/Item/View.js

Merge  Master v4.0.6 Changes to develop

Master v4.0.6  changes

---

forms-flow-data-analysis-api/setup.cfg

JIRA: 
Issue Type: Linting Fix
Updated `setup.cfg` with new pylint rules

🚨  updated pylint config with updated pylint norms

---

forms-flow-web/src/apiManager/services/bpmServices.js
forms-flow-web/src/apiManager/services/formatterService.js
forms-flow-web/src/components/ServiceFlow/details/ServiceTaskDetails.js

JIRA: https://aottech.atlassian.net/browse/FWF-1547
Updated formUrl data Request  to have form-specific Url rather than web base Url for easier processing at camunda Api
Sample Req:
`{"variables":{"formUrl":{"value":"<FormURl>/form/62d92c27c336dae4934e46c8/submission/62da620920ef3225b7299942"},"applicationId":{"value":3121}}}
`
Manual

Form url fix

---

forms-flow-web/src/components/Dashboard/Dashboard.js
forms-flow-web/src/components/Dashboard/dashboard.scss

JIRA: 
Metrics sort UI changed, pagination dropdown issue solved

Metrics sort UI

---

forms-flow-web/src/apiManager/services/languageServices.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-1305
Drop down issue with translation fixed

Fwf 1305 dropdown

---

forms-flow-bpm/src/test/java/org/camunda/bpm/extension/hooks/controllers/mapper/AuthorizationMapperTest.java
forms-flow-bpm/src/test/java/org/camunda/bpm/extension/hooks/controllers/mapper/TaskResultSetExtractorTest.java
forms-flow-bpm/src/test/java/org/camunda/bpm/extension/hooks/listeners/task/AccessGrantNotifyListenerTest.java

Added test cases for hooks/controllers/mapper

Added test cases for hooks/controllers/mapper

---

forms-flow-web/src/components/Form/Item/Edit.js

Checking anonymous button on form upload issue fixed

---

forms-flow-api/tests/unit/api/test_metrics.py

Added test cases for metrics pagination, sort and search.

metrics testcases

---

deployment/docker/README.md
forms-flow-forms/README.md
forms-flow-web/README.md

Readme updated with removing role id 

---

forms-flow-web/src/components/Dashboard/Dashboard.js
forms-flow-web/src/resourceBundles/bg/resourceBundles.js
forms-flow-web/src/resourceBundles/de/resourceBundles.js
forms-flow-web/src/resourceBundles/en/resourceBundles.js
forms-flow-web/src/resourceBundles/formio_resourceBundles.js
forms-flow-web/src/resourceBundles/fr/resourceBundles.js
forms-flow-web/src/resourceBundles/pt/resourceBundles.js
forms-flow-web/src/resourceBundles/zh/resourceBundles.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-1520
Internationalization changes added to dashboard.js

Translation updates of metrics page 

---

forms-flow-bpm/api-spec/forms-flow-bpm-api-spec.yaml
forms-flow-forms/api-spec/forms-flow-forms-api-spec.yaml

API Spec update

---

forms-flow-web/src/apiManager/services/formatterService.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-1589
Bug due to bpm service process list contract breach in multitenant environment

🐛 Tenant specific workflow bugfix

---

forms-flow-web/src/components/Modeller/ModelEditorHook.js
forms-flow-web/src/components/Modeller/lint-rules/packed-config.js

JIRA: https://aottech.atlassian.net/browse/FWF-1586
Update tenant key variable in bpmn modeller
Includes changes for issues related to jira FWF-1586
Unit tests in-progress, not yet complete

Update tenant key in bpmn modeller

---

forms-flow-idm/keycloak/docker-compose.yml

image changed

---

forms-flow-web/src/components/Admin/Insightdashboard.js
forms-flow-web/src/components/Form/constants/table.js
forms-flow-web/src/components/Modeller/index.js
forms-flow-web/src/resourceBundles/bg/resourceBundles.js
forms-flow-web/src/resourceBundles/de/resourceBundles.js
forms-flow-web/src/resourceBundles/en/resourceBundles.js
forms-flow-web/src/resourceBundles/formio_resourceBundles.js
forms-flow-web/src/resourceBundles/fr/resourceBundles.js
forms-flow-web/src/resourceBundles/pt/resourceBundles.js
forms-flow-web/src/resourceBundles/zh/resourceBundles.js

* Translation updation
JIRA: 
Updated translation for modeller changes and pagination.

Translation updates on modeller and pagination

---

forms-flow-api/src/formsflow_api/models/draft.py
forms-flow-api/src/formsflow_api/resources/draft.py
forms-flow-api/src/formsflow_api/schemas/draft.py
forms-flow-api/src/formsflow_api/services/draft.py
forms-flow-api/tests/unit/api/test_draft.py
forms-flow-api/tests/unit/api/test_formio.py

JIRA: 
- Updated API response formats
- skip failing test from CI for further inspection
- Pagination and filtering for draft listing API

✨ draft API requirements from UI

---

forms-flow-api/src/formsflow_api/templates/index.html
forms-flow-web/package-lock.json
forms-flow-web/package.json
forms-flow-web/src/index.js

formio custom component minified version and code splitted

---

forms-flow-api/src/formsflow_api/services/external/formio.py
forms-flow-api/tests/unit/api/test_formio.py

Troubleshoot CI issue

---

forms-flow-api/src/formsflow_api/resources/form_process_mapper.py
forms-flow-api/src/formsflow_api/templates/index.html
forms-flow-api/src/formsflow_api/utils/pdf.py
forms-flow-web/src/components/Form/ExportAsPdf/downloadPdfButton.jsx

PDF generation get client timezone

---

forms-flow-web/src/apiManager/services/insightServices.js

Request arg on dashboard query to return dynamic key

---

forms-flow-api/src/formsflow_api/models/draft.py
forms-flow-api/src/formsflow_api/schemas/draft.py
forms-flow-api/src/formsflow_api/services/draft.py
forms-flow-api/src/formsflow_api/utils/enums.py
forms-flow-api/src/formsflow_api/utils/util.py
forms-flow-web/src/apiManager/services/draftService.js
forms-flow-web/src/components/Draft/ViewDraft.js
forms-flow-web/src/components/Form/Item/View.js

JIRA: 
- Added process diagram in draft detail
- Bug fix in draft feature for anonymous forms
- Fixed draft listing sort

🐛 Added process diagram, anonymous form bug fix for draft

---

forms-flow-api/src/formsflow_api/models/draft.py
forms-flow-api/src/formsflow_api/services/application.py

Modified logic for the draft count to user-specific.

draft count to user specific

---

deployment/docker/docker-compose.yml
forms-flow-web/src/apiManager/services/applicationServices.js

JIRA: 
- Added draft count state update handler
- updated docker deployment compose file

🐛 draft count state update, docker compose update for token generation

---

forms-flow-bpm/pom.xml

JIRA: 
Vulnerability fix - bpm

bpm vulnerability fix 

---

forms-flow-api/src/formsflow_api/models/application.py
forms-flow-api/src/formsflow_api/models/draft.py
forms-flow-api/src/formsflow_api/resources/draft.py
forms-flow-api/src/formsflow_api/services/application.py
forms-flow-api/tests/unit/api/test_draft.py
forms-flow-web/src/_tests_/test-components/test-application/test-details/nodata.test.js
forms-flow-web/src/apiManager/services/draftService.js
forms-flow-web/src/components/Application/List.js
forms-flow-web/src/components/Application/nodata.js
forms-flow-web/src/components/Draft/List.js
forms-flow-web/src/components/PrivateRoute.jsx

JIRA: 
https://aottech.atlassian.net/browse/FWF-1612
https://aottech.atlassian.net/browse/FWF-1624

🐛 added application count with draft list

---

forms-flow-api/requirements.txt
forms-flow-api/requirements/prod.txt

Adding selenium and selenium-wire dependencies

---

forms-flow-web/package-lock.json
forms-flow-web/package.json
forms-flow-web/src/components/Draft/ViewDraft.js
forms-flow-web/src/components/Form/ExportAsPdf/downloadPdfButton.jsx
forms-flow-web/src/components/Form/Item/Submission/Item/View.js
forms-flow-web/src/featureToogle.js
forms-flow-web/src/index.js

JIRA: 
- Introduced feature flag service. Now we can disable or enable features from env or directly give true or false in featureToogle.js.
- Introduced one more ENV to enable the export pdf feature.
- `REACT_APP_EXPORT_PDF_ENABLED`.
- Hide Export PDF in Draft view.
Feature flag reference : [flagged](https://github.com/sergiodxa/flagged)

Feature flag UI

---

forms-flow-api/src/formsflow_api/utils/user_context.py
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/keycloak/rest/RestApiSecurityConfig.java

JIRA: 
- User context change to use either role or roles
- BPM fix to pass in user context for new custom endpoints

Fix for BPM task assignee issue

---

forms-flow-api/src/formsflow_api/services/authorization.py
forms-flow-api/src/formsflow_api/utils/user_context.py
forms-flow-api/tests/utilities/base_test.py

Changes for checking either roles or groups for authorization

---

forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/ProcessDefinitionRestResource.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/impl/ProcessDefinitionRestResourceImpl.java

JIRA: 
Added tenantId parameter to process definition get xml API
..camunda/engine-rest-ext/v1/process-definition/key/{key}/xml?tenantId={tenant-id}

Added tenantId parameter to process definition get xml API

---

forms-flow-web/src/components/Draft/List.js
forms-flow-web/src/components/Modeller/index.js
forms-flow-web/src/resourceBundles/bg/resourceBundles.js
forms-flow-web/src/resourceBundles/de/resourceBundles.js
forms-flow-web/src/resourceBundles/en/resourceBundles.js
forms-flow-web/src/resourceBundles/formio_resourceBundles.js
forms-flow-web/src/resourceBundles/fr/resourceBundles.js
forms-flow-web/src/resourceBundles/pt/resourceBundles.js
forms-flow-web/src/resourceBundles/zh/resourceBundles.js

JIRA: 
Translation added for draft and updated for processes

Translations updated for draft

---

forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/ProcessDefinitionRestResource.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/TaskRestResource.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/impl/ProcessDefinitionRestResourceImpl.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/impl/TaskRestResourceImpl.java

JIRA: 
https://aottech.atlassian.net/browse/FWF-1649
added and modified APIs on bpm gateway layer

fixes + added tenantId parameter to start process instance API

---

forms-flow-web/src/components/Admin/Insightdashboard.js
forms-flow-web/src/components/Application/table.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-1652
- size per page drop-down changed to drop up for better visibility

size per page selection dropdown changed to dropup for better visibility

---

forms-flow-web/src/components/Insights/Insights.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-1647
- loading overlay active condition updated to fix loading bug

🐛 loading overlay bugfix

---

forms-flow-web/src/resourceBundles/bg/resourceBundles.js
forms-flow-web/src/resourceBundles/de/resourceBundles.js
forms-flow-web/src/resourceBundles/en/resourceBundles.js
forms-flow-web/src/resourceBundles/formio_resourceBundles.js
forms-flow-web/src/resourceBundles/fr/resourceBundles.js
forms-flow-web/src/resourceBundles/pt/resourceBundles.js
forms-flow-web/src/resourceBundles/zh/resourceBundles.js

* Translations updated for draft
JIRA: 
Added more translations for drafts.

Translations updated 

---

DEPENDENCIES.md

JIRA: 
https://aottech.atlassian.net/browse/FWF-1654
Updated dependencies document with latest version chnages

DEPENDENCIES.md

---

deployment/docker/docker-compose.yml

change in order of build

---

forms-flow-web/src/resourceBundles/bg/resourceBundles.js
forms-flow-web/src/resourceBundles/de/resourceBundles.js
forms-flow-web/src/resourceBundles/en/resourceBundles.js
forms-flow-web/src/resourceBundles/formio_resourceBundles.js
forms-flow-web/src/resourceBundles/fr/resourceBundles.js
forms-flow-web/src/resourceBundles/pt/resourceBundles.js
forms-flow-web/src/resourceBundles/zh/resourceBundles.js

JIRA: 
* Added new translations for view.js

Translation updated

---

forms-flow-api/src/formsflow_api/resources/form_process_mapper.py

JIRA: https://aottech.atlassian.net/browse/FWF-1645
Added null checking for `taskVariable` property

🐛 Null check for `taskvariable`

---

deployment/docker/sample.env

JIRA: 
remove comment of bpm secret key

remove comment of bpm secret

---

.github/workflows/forms-flow-data-analysis-api-cd.yml

Fixing build-args on CD

---

.github/workflows/forms-flow-bpm-cd.yml
forms-flow-analytics/docker-compose.yml
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/service/impl/AdminRestServiceImpl.java

Fixing issue with authorization

---

forms-flow-web/Dockerfile

JIRA: https://aottech.atlassian.net/browse/FWF-1618
Updated nginx version so that the underlying packages got updated. 
Before :  Total 225 issues (70 high priority)
Updated :  Total 85 issues  (1 high priority)

Updated the nginx version to fix the docker vulnerabilities

---

forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/service/impl/AdminRestServiceImpl.java

JIRA: 
added authorization resource to reviewer role

Fixing authorization issue for reviewer role

---

forms-flow-bpm/src/main/java/org/camunda/bpm/extension/commons/utils/VariableConstants.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/listeners/FormSubmissionListener.java
forms-flow-bpm/src/test/java/org/camunda/bpm/extension/hooks/listeners/FormSubmissionListenerTest.java

JIRA: 
https://aottech.atlassian.net/browse/FWF-1663
Added webFormUrl in FormSubmissionListener

🐛 Added webFormUrl in FormSubmissionListener

---

forms-flow-web/src/_tests_/test-components/test-serviceflow/list/sort/TaskSort.test.js
forms-flow-web/src/_tests_/test-components/test-serviceflow/list/sort/constants.js
forms-flow-web/src/_tests_/test-helpers/helper.test.js

JIRA: 
added the testcases for the helper.js file and TaskSort component.

Updated testcases of helper.js and tasksort.js

---

forms-flow-web/src/components/Dashboard/Dashboard.js

JIRA: 
extra line in dashboard menu is removed

extra line removed in dashboard menu

---

forms-flow-web/src/components/Form/Create.js
forms-flow-web/src/components/Form/Item/Edit.js
forms-flow-web/src/components/Form/Steps/WorkFlow.js

JIRA: 
Issue Type: BUG/ FEATURE https://aottech.atlassian.net/browse/FWF-1553
1. will disable the save button when it clicked once

fixed multiple save action

---

forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/service/impl/AdminRestServiceImpl.java

Adding DMN authorizations to tenant

---

forms-flow-api/requirements.txt
forms-flow-api/requirements/dev.txt
forms-flow-documents/requirements.txt
forms-flow-documents/requirements/prod.txt

formsflow_api requirement path updated to develop branch

➕ dependency path updated to develop branch

---

forms-flow-web/src/_tests_/test-components/test-form/test-item/view.test.js
forms-flow-web/src/components/Form/Item/View.js

form active check added to draft create

adding form status check to draft create

---

forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/DecisionDefinitionRestResource.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/impl/DecisionDefinitionRestResourceImpl.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/impl/FormsFlowV1RestServiceImpl.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/impl/ProcessDefinitionRestResourceImpl.java
forms-flow-web/src/apiManager/endpoints/index.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-1668
* decision definition APIs are added

added decision definition APIs

---

forms-flow-documents/requirements/prod.txt

Revert module dependency github repo

---

forms-flow-web/src/components/Modeller/Editors/BpmnEditor/index.js
forms-flow-web/src/components/Modeller/Editors/DmnEditor/index.js

JIRA: [FWF-1669](https://aottech.atlassian.net/browse/FWF-1669)
Added validation for exporting workflows for both BPMN and DMN

Added validation for exporting workflows

---

forms-flow-web/src/apiManager/services/processServices.js
forms-flow-web/src/components/Form/Stepper.js

JIRA: 
workflow issue in multitenancy resolved

Fwf 1670 updated

---

forms-flow-web/src/components/PrivateRoute.jsx

JIRA: https://aottech.atlassian.net/browse/FWF-1629

🐛 clear tenant session when new tenant endpoint is selected 

---

forms-flow-web/package-lock.json

Reverts AOT-Technologies/forms-flow-ai#831

Revert "Bump moment-timezone from 0.5.34 to 0.5.37 in /forms-flow-web"

---

forms-flow-bpm/src/main/java/org/camunda/bpm/extension/commons/io/socket/message/TaskEventMessage.java
forms-flow-bpm/src/test/java/org/camunda/bpm/extension/commons/io/event/CamundaEventListenerTest.java

JIRA: 
Included tenantId in Task Event

Included tenantId in Task Event

---

forms-flow-web/package-lock.json
forms-flow-web/package.json
forms-flow-web/src/components/Form/Steps/WorkFlow.js
forms-flow-web/src/components/Modeller/index.js

JIRA: 
Issue Type: BUG/ FEATURE : https://aottech.atlassian.net/browse/FWF-1633
changed package

fixed dropdown search

---

forms-flow-web/src/components/Draft/Edit.js
forms-flow-web/src/components/Draft/table.js

1. Draft edit updated to open on the same window.
2. Added width ratio for draft columns.
3. Polling notification set to show only after polling has started.

🐛 Drafts UI corrections

---

deployment/docker/docker-compose.yml

`MULTI_TENANCY_ENABLED` added for docker deployment yml

🐛 multitenancy config added for webapi deployment

---

forms-flow-web/package-lock.json
forms-flow-web/package.json

moment vulnerability fixed

---

forms-flow-web/src/components/Dashboard/Dashboard.js

JIRA: 
matrics loading is changed and set same as insights

matrics loading changed

---

README.md
forms-flow-api/README.md
forms-flow-documents/README.md
forms-flow-forms/README.md
forms-flow-web/README.md

JIRA: 
* Updated badge versions

Updated readme with badge changes

---

forms-flow-web/src/components/Form/List.js

JIRA: 
pagination and search bugs in bpm and designer forms is fixed.

Pagination bug fix

---

forms-flow-web/src/components/Dashboard/Dashboard.js

metrics loading bug fix

---

deployment/server/client-server-deployment/Dockerfile
deployment/server/client-server-deployment/README.md
deployment/server/client-server-deployment/docker-compose.yaml
deployment/server/client-server-deployment/nginx.conf
deployment/server/client-server-deployment/runme.sh

JIRA: 
Nginx with valid SSL configuration added in the deployment/server folder

client side deployment doc and configuration updated

---

forms-flow-web/src/components/Draft/Edit.js

JIRA:  
Issue Type: BUG/ FEATURE - BUG

 Show Conditionally Form Save Message only for Anonymous users

---

forms-flow-web/src/components/Form/Steps/PreviewStepper.js
forms-flow-web/src/resourceBundles/formio_resourceBundles.js

JIRA: 
Bug fixed on previewStepper

Internationalization

---

deployment/docker/README.md
forms-flow-api/sample.env

JIRA: 
* docker readme updated with env details.
* sample.env updated in forms-flow-api

readme update

---

forms-flow-api/README.md
forms-flow-web/README.md

JIRA: 
Readme updated with env updation details.

Readme updated

---

forms-flow-bpm/sample.env

Updated Default values in sample.env

---

deployment/docker/docker-compose.yml
forms-flow-api/Dockerfile
forms-flow-api/wait-for-service.sh

ISSUE: https://github.com/AOT-Technologies/forms-flow-ai/issues/815 
- Added script to check if the database is ready to accept connections in docker full deployment
Manual test
Now this script is only added for `webapi` only if other services face the same issue this can be implemented across every service

🚀 Wait for database to accept TCP connections before running migrations

---

forms-flow-web/src/components/Modeller/Editors/BpmnEditor/index.js
forms-flow-web/src/components/Modeller/Editors/DmnEditor/index.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-1692
The checkbox will be checked if the  workflow  is deployed as public. else it will remain unchecked and the user can check for deploying publicaly

Workflow Can now be identified with checkbox

---

forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/listeners/FormSubmissionListener.java

JIRA: 
https://aottech.atlassian.net/browse/FWF-1688
* updated FormSubmissionListener class

webFormUrl Issue fix

---

forms-flow-web/src/components/Form/Stepper.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-1696

updated translation in stepper page

---

forms-flow-web/src/styles.scss

JIRA: 
added styling for wizard component

wizard alignent fix

---

forms-flow-web/src/components/Draft/Edit.js
forms-flow-web/src/components/Form/Item/View.js

JIRA: https://aottech.atlassian.net/browse/FWF-1712
notification content change for drafts

✏️ Notification message update

---

forms-flow-web/src/components/ServiceFlow/details/ServiceTaskDetails.js

JIRA: 
loading bug fix for service bc fixed

loading bug fix

---

forms-flow-web/package.json

JIRA: 
version changed to 5.0.1

version added

---

forms-flow-web/src/components/Form/List.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-1694
Sort was not working on the first click. issue solved

Sort changes

---

forms-flow-api/src/formsflow_api/services/application.py
forms-flow-api/src/formsflow_api/services/external/base_bpm.py
forms-flow-api/src/formsflow_api/services/external/bpm.py

JIRA: 
In multitenant environment, task created by Anonymous submission with common workflow is visible to all tenants fix.

Multitenant - Anonymous submission with common workflow fix

---

forms-flow-web/src/components/Dashboard/Dashboard.js
forms-flow-web/src/components/Form/List.js
forms-flow-web/src/components/ServiceFlow/details/ServiceTaskDetails.js
forms-flow-web/src/constants/applicationComponent.js

JIRA: 
Issue Type: BUG/ FEATURE : 
https://aottech.atlassian.net/browse/FWF-1716
https://aottech.atlassian.net/browse/FWF-1717

Fixed: 🐛 Wizard form & form search text & Formio caching 

---

deployment/docker/docker-compose.yml
forms-flow-forms/docker-compose.yml

version changes

---

forms-flow-web/src/containers/TaskHead.js

JIRA: 
added a space after the task just befor the count

Added a space between the task and task count

---

forms-flow-api-utils/src/formsflow_api_utils/__init__.py
forms-flow-api/src/formsflow_api/__init__.py
forms-flow-documents/src/formsflow_documents/__init__.py

version bumped to 5.0.1

---

forms-flow-web/public/config/config.sample.js
forms-flow-web/src/constants/constants.js

JIRA: 
Removed JWT_SECRET KEY from the front end

code clean up

---

forms-flow-web/src/components/Draft/index.js
forms-flow-web/src/components/Form/Item/View.js

JIRA: https://aottech.atlassian.net/browse/FWF-1674
- Application <-> Drafts transition glitch fix
- Draft create only after validating the resource

🐛 Resource validation for creating draft.

---

deployment/docker/README.md
forms-flow-bpm/README.md

JIRA: 
https://aottech.atlassian.net/browse/FWF-1689
* updated README.md

Documentation update-Release/5.0.1

---

forms-flow-web/src/_tests_/test-components/test-serviceflow/index.test.js
forms-flow-web/src/services/SocketIOService.js

JIRA: 
updated socket service based on multitenancy

updated socket service

---

forms-flow-api-utils/src/formsflow_api_utils/services/external/formio.py
forms-flow-api/requirements.txt
forms-flow-api/requirements/dev.txt
forms-flow-api/requirements/prod.txt

JIRA: 
application create changed to backend the issue with empty data is solved

Application create updation

---

forms-flow-api/requirements.txt
forms-flow-api/requirements/dev.txt
forms-flow-api/requirements/prod.txt

JIRA: 
requirement.txt, prod.txt, dev.txt branch changed to released branch

branch pointed to release branch

---

forms-flow-web/src/components/Form/Item/Edit.js
forms-flow-web/src/components/Form/constants/formListConstants.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-1744
**Added task variable is removed on changing the title of a form - fix**
Added task variable to form mapper creation API payload

task-variable-fix 🐛 

---

forms-flow-web/src/components/Modeler/Modeler.scss
forms-flow-web/src/components/Modeler/index.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-1729
process dropdown ui fix

Process tab Dropdown ui fix

---

forms-flow-bpm/pom.xml
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/commons/io/event/CamundaEventListener.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/commons/io/socket/RedisConfig.java
forms-flow-bpm/src/main/resources/application.yaml

JIRA: 
* code cleanup forms-flow-bpm

code-cleanup and commented redis dependencies 

---

.github/workflows/forms-flow-bpm-cd.yml
forms-flow-api/api-spec/forms-flow-python-api-spec.yaml
forms-flow-api/src/formsflow_api/resources/application.py

Update to API Spec 

---

deployment/docker/docker-compose.yml
forms-flow-forms/docker-compose.yml

Image tag of forms changes to 5.0.1

---

deployment/docker/README.md
forms-flow-bpm/README.md

JIRA: 
* Readme updated : Removed redis env from README.md

Updated README.md

---

forms-flow-web/src/components/Application/List.js
forms-flow-web/src/components/Application/table.js
forms-flow-web/src/components/Draft/List.js
forms-flow-web/src/components/Draft/table.js
forms-flow-web/src/helper/regExp/validApplicationId.js
forms-flow-web/src/helper/regExp/validResourceId.js

JIRA: https://aottech.atlassian.net/browse/FWF-1029
Added validation notification to applications and drafts
The validation is done using regex to match any non-numerical pattern.
Adding toast to show the validation error is debatable, adding validation messages inside the table causes a layout shift, that's the rationale behind using toast. To keep things minimal I prefer not to show any explicit messages but the red bordering alone will convey the meaning

🐛  Added applicationId, draftId validation error notifications

---

forms-flow-web/src/components/ServiceFlow/list/ServiceTaskList.js

JIRA:  https://aottech.atlassian.net/browse/FWF-1479
1. fixes : task name overflow fixed

🐛  fixed task name overflow

---

forms-flow-web/src/components/Loading/SavingLoading.js

fixed draft saved color to greeen

---

forms-flow-web/src/components/Form/List.js

JIRA: https://aottech.atlassian.net/browse/FWF-235
Issue Type: BUG/ FEATURE 
1. added select tag in form page to select the form type

🍃 updated form query with form type

---

deployment/docker/docker-compose.yml
deployment/docker/sample.env
forms-flow-bpm/docker-compose.yml
forms-flow-bpm/pom.xml
forms-flow-bpm/sample.env
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/commons/io/event/CamundaEventListener.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/commons/io/event/TaskEventTopicListener.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/commons/io/socket/RedisConfig.java
forms-flow-bpm/src/main/resources/application.yaml

JIRA: 
https://aottech.atlassian.net/browse/FWF-1770
* added + fixed redis connection failure issues

added redis config + fixes

---

forms-flow-web/src/components/ServiceFlow/details/TaskHeader.js
forms-flow-web/src/containers/TaskHead.js

JIRA:  My task count is not updating on claim/unclaim

🐛 Task count change on claim and unclaim

---

forms-flow-bpm/src/test/java/org/camunda/bpm/extension/hooks/delegates/FormTextAnalysisDelegateTest.java
forms-flow-bpm/src/test/java/org/camunda/bpm/extension/hooks/listeners/ApplicationAuditListenerTest.java
forms-flow-bpm/src/test/java/org/camunda/bpm/extension/hooks/listeners/ApplicationStateListenerTest.java

JIRA: 
* https://aottech.atlassian.net/browse/FWF-1368
* https://aottech.atlassian.net/browse/FWF-1275
*  updated ApplicationAuditListenerTest and ApplicationStateListenerTest
*  added testcases for FormTextAnalysisDelegateTest

added bpm test cases

---

forms-flow-api/requirements.txt
forms-flow-api/requirements/dev.txt
forms-flow-api/requirements/prod.txt

JIRA: 
The requirements file was modified to reference the develop branch.

Change in requirements file point to develop branch

---

forms-flow-web/src/components/Form/Item/Submission/Item/Edit.js

JIRA: https://aottech.atlassian.net/browse/FWF-1775
1. prevent clearing submission data on form submitting

🐛 fixed form clear onSubmit and added else case in reviewer submit

---

forms-flow-api/tests/unit/api/test_authorization.py

JIRA: 
https://aottech.atlassian.net/browse/FWF-1658
Testcases for moving authorizations to python API

Testcases - Move authorizations to python API 

---

forms-flow-idm/realm-exports/Client based auth.json
forms-flow-idm/realm-exports/Group based auth.json

Include roles in userinfo, remove unused mapper

---

forms-flow-web/src/index.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-1812

Custom formio render issue fix

---

forms-flow-web/src/components/Form/List.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-1777
https://aottech.atlassian.net/browse/FWF-1752
The form page was shoing infinit loading wnil navigating back to form page after a single sort. And the serch bar was leading to infinit loading while closing the search keyword without searching.

sort and search infinit loading issues

---

.github/workflows/code-ql.yml
.github/workflows/forms-flow-api-ci.yml
.github/workflows/forms-flow-bpm-ci.yml
.github/workflows/forms-flow-data-analysis-api-ci.yml
.github/workflows/forms-flow-documents-ci.yml
.github/workflows/forms-flow-web-ci.yml

Changes to CI pipelines to use CodeQL and renaming steps

---

forms-flow-web/src/components/Form/List.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-1810
initial rerendering  removed

 Search result not retaining bug fixed

---

forms-flow-web/src/components/ServiceFlow/ServiceFlow.scss
forms-flow-web/src/components/ServiceFlow/list/ServiceTaskList.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-1809
Overflow issue in tasklist fixed

Tasklist overflow issue fixed

---

forms-flow-web/src/styles.scss

JIRA: https://aottech.atlassian.net/browse/FWF-1824

🐛  Upgrade form component height 

---

forms-flow-api/src/formsflow_api/models/application.py
forms-flow-api/src/formsflow_api/resources/draft.py
forms-flow-api/src/formsflow_api/services/draft.py
forms-flow-api/tests/unit/api/test_draft.py

JIRA: 
https://aottech.atlassian.net/browse/FWF-1823
WebAPI endpoint to delete the active draft specific to the user.
Deletes draft and application corresponding to the draft.

WebAPI: delete draft endpoint

---

forms-flow-web/src/components/Form/Item/View.js
forms-flow-web/src/components/ServiceFlow/ServiceFlow.scss
forms-flow-web/src/components/ServiceFlow/list/ServiceTaskList.js
forms-flow-web/src/styles.scss

JIRA: https://aottech.atlassian.net/browse/FWF-1853
https://aottech.atlassian.net/browse/FWF-1853

updated pagination and form view height and z index of refresh button on signature 

---

forms-flow-bpm/pom.xml

JIRA: 
https://aottech.atlassian.net/browse/FWF-1822
Updated Spring Boot & Spring Framework to fix CVE-2022-22965.
Updated jackson to fix CVE-2022-42003, CVE-2022-42004.
After jackson package update

Vulnerability fix - bpm

---

forms-flow-web/src/styles.scss

JIRA: 
https://aottech.atlassian.net/browse/FWF-1780
Select component display issue fixed for form,resource,wizard,draft

Select component display issue fixed 

---

forms-flow-web/src/apiManager/endpoints/index.js
forms-flow-web/src/apiManager/services/bpmTaskServices.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-1834
Rearranged with new endpint from python side

Changed the end point of calling the userlist Api

---

forms-flow-web/src/apiManager/services/bpmTaskServices.js
forms-flow-web/src/components/ServiceFlow/constants/userSearchFilterTypes.js

https://aottech.atlassian.net/browse/FWF-1875
JIRA: 

updated with user end point for search in service task

---

forms-flow-web/src/styles.scss

JIRA: 
https://aottech.atlassian.net/browse/FWF-1873
User should be able to see the save button - fixed

form create css fix

---

forms-flow-api-utils/src/formsflow_api_utils/utils/util.py
forms-flow-api/src/formsflow_api/resources/anonymous_application.py
forms-flow-api/src/formsflow_api/resources/application.py
forms-flow-api/src/formsflow_api/resources/application_history.py
forms-flow-api/src/formsflow_api/resources/authorization.py
forms-flow-api/src/formsflow_api/resources/dashboards.py
forms-flow-api/src/formsflow_api/resources/draft.py
forms-flow-api/src/formsflow_api/resources/filter.py
forms-flow-api/src/formsflow_api/resources/form_process_mapper.py
forms-flow-api/src/formsflow_api/resources/formio.py
forms-flow-api/src/formsflow_api/resources/groups.py
forms-flow-api/src/formsflow_api/resources/metrics.py
forms-flow-api/src/formsflow_api/resources/process.py
forms-flow-api/src/formsflow_api/resources/user.py
forms-flow-api/tests/utilities/base_test.py

Updated all API resources to have detailed API specs. The existing API spec doesn't provide details such as query parameters, request payload, response body, response status, and also the details of authorized user role/group for the specific API.
JIRA: https://aottech.atlassian.net/browse/FWF-1856
Issue Type: DOCUMENTATION
Add API spec for all resources.
Minimal refactoring to fix server crashes.
[screencapture-localhost-5000-2022-11-29-19_19_24.pdf](https://github.com/AOT-Technologies/forms-flow-ai/files/10113632/screencapture-localhost-5000-2022-11-29-19_19_24.pdf)

✏️ Add detailed documentation for formsflow-api spec.

---

forms-flow-web/src/components/Form/Stepper.js

JIRA: https://aottech.atlassian.net/browse/FWF-1857
Removed unnecessary props on the edit component to fix the rerendering of edit component

removed unnecessary props from edit component

---

forms-flow-bpm/pom-docker.xml
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/keycloak/plugin/KeycloakIdentityProviderFactory.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/keycloak/plugin/KeycloakIdentityProviderSession.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/keycloak/sso/KeycloakAuthenticationProvider.java

https://aottech.atlassian.net/browse/FWF-1886

Changes for Keycloak 15+ compatibility with BPM layer

---

forms-flow-web/src/components/Form/Item/Edit.js

JIRA: 
fixed updated data not showing in list and view-edit window

form update fix

---

forms-flow-web/src/components/Draft/Edit.js
forms-flow-web/src/components/Draft/List.js
forms-flow-web/src/components/Draft/ViewDraft.js
forms-flow-web/src/components/Draft/index.js
forms-flow-web/src/components/Form/Item/View.js

JIRA: https://aottech.atlassian.net/browse/FWF-1895
- Prevent draft update calls for form submit.
- Prevent draft update call with stale ids.
- Remove extra papper from draft edit page.

🐛 Fix draft feature UI bugs

---

forms-flow-api/tests/unit/models/test_application.py
forms-flow-api/tests/unit/models/test_form_process_mapper.py
forms-flow-api/tests/unit/models/test_formprocessmapper.py
forms-flow-api/tests/utilities/base_test.py

JIRA: 
Form versioning Test case fixes

Test case fixes

---

forms-flow-api/requirements.txt
forms-flow-api/requirements/dev.txt
forms-flow-api/requirements/prod.txt

JIRA: 
Change branch in requirements file to point to form-versioning

Change branch in requirements file to form-versioning

---

forms-flow-web/package-lock.json
forms-flow-web/package.json
forms-flow-web/src/components/ServiceFlow/details/TaskHeader.js
forms-flow-web/src/components/ServiceFlow/list/search/TaskFilterComponent.js
forms-flow-web/src/components/ServiceFlow/list/sort/TaskSortSelectedList.js

https://aottech.atlassian.net/browse/FWF-1921
JIRA: 

updated vulnerability

---

forms-flow-web/package-lock.json
forms-flow-web/package.json
forms-flow-web/src/components/ServiceFlow/details/TaskHeader.js
forms-flow-web/src/components/ServiceFlow/list/search/TaskFilterComponent.js
forms-flow-web/src/components/ServiceFlow/list/sort/TaskSortSelectedList.js

JIRA: 
Latest develop to form versioning

Latest develop to form versioning

---

forms-flow-web/src/components/Draft/Edit.js

JIRA: https://aottech.atlassian.net/browse/FWF-1895
Added `SUBMIT` exitType for component unmount, which will prevent the component to update the draft during unmount.

🐛 Fix prevent draft update after draft discard

---

forms-flow-api/src/formsflow_api/resources/form_process_mapper.py

JIRA: 
Added _formType, parentFormId_ to "/form" POST endpoint request payload.

Updates in api-doc 

---

deployment/Service-Name-Installation/sample.env

Sample.env updated

---

forms-flow-bpm/pom.xml

JIRA: 
https://aottech.atlassian.net/browse/FWF-1920
* Fixed forms-flow-bpm security vulnerability

java vulnerability fix

---

forms-flow-api/src/formsflow_api/services/form_history_logs.py
forms-flow-web/src/components/Form/Item/Edit.js
forms-flow-web/src/components/Form/Item/Preview.js
forms-flow-web/src/components/Form/List.js
forms-flow-web/src/components/Form/Stepper.js
forms-flow-web/src/styles.scss

1. fixed: create history on upload form when the upload data changed
2. fixed: create history on form edit when the form type change or display changes

 fixed UI and UX / form history part & create clone on form upload if data changed

---

deployment/docker/docker-compose.yml
forms-flow-api-utils/src/formsflow_api_utils/utils/auth.py
forms-flow-api/docker-compose.yml
forms-flow-api/src/formsflow_api/config.py
forms-flow-api/src/formsflow_api/resources/__init__.py
forms-flow-api/src/formsflow_api/resources/application.py
forms-flow-api/src/formsflow_api/resources/form_embed.py

Add resource for embed forms

---

forms-flow-api-utils/src/formsflow_api_utils/services/external/formio.py
forms-flow-api-utils/src/formsflow_api_utils/utils/auth.py
forms-flow-api/requirements.txt
forms-flow-api/requirements/dev.txt
forms-flow-api/requirements/prod.txt
forms-flow-api/src/formsflow_api/resources/form_embed.py
forms-flow-api/src/formsflow_api/services/__init__.py
forms-flow-api/src/formsflow_api/services/form_embed.py

Form embeding

---

forms-flow-api/src/formsflow_api/resources/application.py
forms-flow-api/src/formsflow_api/resources/form_embed.py

Deprecate `/token` endpoint
Deprecate `/application/external/create`
Add internal, external endpoints for fetching
and submitting embedd forms
JIRA: 

Add internal endpoints for embed

---

forms-flow-api/src/formsflow_api/resources/__init__.py
forms-flow-api/src/formsflow_api/resources/filter.py
forms-flow-api/src/formsflow_api/resources/roles.py
forms-flow-api/src/formsflow_api/schemas/__init__.py
forms-flow-api/src/formsflow_api/schemas/roles.py
forms-flow-api/src/formsflow_api/services/external/keycloak.py
forms-flow-api/src/formsflow_api/services/factory/keycloak_admin.py
forms-flow-api/src/formsflow_api/services/factory/keycloak_client_service.py
forms-flow-api/src/formsflow_api/services/factory/keycloak_group_service.py
forms-flow-api/tests/unit/api/test_roles.py

JIRA: 
https://aottech.atlassian.net/browse/FWF-1861
Web api endpoints to list, create, update, & delete roles/groups to support the admin module to manage (add/edit/remove) roles used in the application.
Group based API response
Role based API response

Webapi endpoints to support roles/groups CRUD

---

deployment/docker/docker-compose.yml
deployment/docker/sample.env
forms-flow-analytics/api-spec/forms-flow-analytics-api-spec.yaml
forms-flow-api-utils/src/formsflow_api_utils/services/external/formio.py
forms-flow-api-utils/src/formsflow_api_utils/utils/auth.py
forms-flow-api/docker-compose.yml
forms-flow-api/requirements.txt
forms-flow-api/requirements/dev.txt
forms-flow-api/requirements/prod.txt
forms-flow-api/sample.env
forms-flow-api/src/formsflow_api/config.py
forms-flow-api/src/formsflow_api/resources/__init__.py
forms-flow-api/src/formsflow_api/resources/application.py
forms-flow-api/src/formsflow_api/resources/form_embed.py
forms-flow-api/src/formsflow_api/services/__init__.py
forms-flow-api/src/formsflow_api/services/form_embed.py
forms-flow-api/tests/docker/docker-compose.yml
forms-flow-api/tests/unit/api/test_form_embed.py
forms-flow-api/tests/utilities/base_test.py
forms-flow-forms/api-spec/forms-flow-forms-api-spec.yaml

JIRA: https://aottech.atlassian.net/browse/FWF-1839
Add external GET and POST APIs for form fetch and
submission with custom authentication
Add internal GET and POST APIs for form fetch and
submission with Keycloak authentication
Remove the `/application/external/create` endpoint
since the internal POST API is the replacement
Add the `FORM_EMBED_JWT_SECRET` env variable for
form embed custom authentication

✨ Add form embed APIs

---

forms-flow-web/src/components/Dashboard/StatusChart.js
forms-flow-web/src/components/Form/List.js

JIRA: https://aottech.atlassian.net/browse/FWF-1759
Form.io forms can now directly import ot formsflow.

Import form directly form form.io

---

forms-flow-api/requirements/dev.txt
forms-flow-api/src/formsflow_api/resources/form_process_mapper.py
forms-flow-api/src/formsflow_api/services/form_history_logs.py
forms-flow-web/src/components/Form/FileUpload/SelectFormForDownload.js
forms-flow-web/src/components/Form/Item/Preview.js

1. Did suggest changes in pr
2. Added Docs for APi

fixed : reviews in pr

---

forms-flow-web/src/components/Form/Stepper.js

1. issue was not sending parent formid now fixed it

fixed mapper put APi

---

forms-flow-web/src/components/Modeler/index.js
forms-flow-web/src/resourceBundles/bg/resourceBundles.js
forms-flow-web/src/resourceBundles/de/resourceBundles.js
forms-flow-web/src/resourceBundles/en/resourceBundles.js
forms-flow-web/src/resourceBundles/formio_resourceBundles.js
forms-flow-web/src/resourceBundles/fr/resourceBundles.js
forms-flow-web/src/resourceBundles/pt/resourceBundles.js
forms-flow-web/src/resourceBundles/zh/resourceBundles.js
forms-flow-web/src/styles.scss

JIRA: 
https://aottech.atlassian.net/browse/FWF-1844
* Fixed translation issues with workflow upload and preview
* Placeholder translated

Updated internationalization on processes tab

---

forms-flow-web/src/styles.scss

JIRA: 
https://aottech.atlassian.net/browse/FWF-1844
* Workflow choose button css issue fixed

Workflow choose button css issue fixed

---

forms-flow-web/src/components/Form/Stepper.js

1. fixed create a new mapper by changing the workflow

🐛 fixed bug on create a new mapper 

---

forms-flow-web/src/components/Form/Item/Edit.js

1. path, name fix in save as new version

✅ save as new version : form name and path fix

---

forms-flow-web/src/components/Form/List.js

JIRA: https://aottech.atlassian.net/browse/FWF-1973

🐛 Page limit fix while form type change

---

deployment/docker/README.md
forms-flow-bpm/README.md

JIRA: 
* updated documentation

updated readme - formsflow-bpm changes

---

CHANGELOG.md
forms-flow-api/migrations/versions/1a55b7674144_form_history.py

JIRA: 
Update on the migration filename.
Add the migration file link in change log.
**Before change**
**After change**

Update on the migration filename and change log.

---

forms-flow-web/src/apiManager/services/applicationServices.js
forms-flow-web/src/apiManager/services/draftService.js
forms-flow-web/src/components/Dashboard/Dashboard.js

JIRA: https://aottech.atlassian.net/browse/FWF-1974

Fixed CodeQL vulnerabilities

---

forms-flow-web/src/containers/NavBar.jsx

JIRA: https://aottech.atlassian.net/browse/FWF-1964
For anonymous forms, the only way to
identify the tenant is possible through the
form data with the current implementation.
To redirect to the correct tenant
we will use the form as the data source
for the tenant key.

🐛 : Login button redirects to 404

---

forms-flow-data-analysis-api/model_training/README.md
forms-flow-data-analysis-api/model_training/requirements.txt

JIRA: 
PyTorch  vulnerability fix
Update versions for NumPy, Transformers, scikit-learn, datasets, torch
**Before change**
**After change**

Vulnerability fix and version updates in Sentiment Analysis Model Training

---

forms-flow-web/src/components/Form/Item/Edit.js
forms-flow-web/src/components/Form/Item/Preview.js
forms-flow-web/src/resourceBundles/bg/resourceBundles.js
forms-flow-web/src/resourceBundles/de/resourceBundles.js
forms-flow-web/src/resourceBundles/en/resourceBundles.js
forms-flow-web/src/resourceBundles/fr/resourceBundles.js
forms-flow-web/src/resourceBundles/pt/resourceBundles.js
forms-flow-web/src/resourceBundles/zh/resourceBundles.js

loading added for saving as a new version
changed duplicate form success message
added internationalization for the success message

💫 Loading implemented

---

forms-flow-web/src/apiManager/services/processServices.js
forms-flow-web/src/components/Form/Item/Edit.js

1. fixed history calling api with undefined
2. fixed delete form process mapper with undefined
3. fixed form mapper version NaN while creating
JIRA: https://aottech.atlassian.net/browse/FWF-1979

🐛 fixed form history undefined

---

forms-flow-web/src/components/Form/Item/View.js

JIRA: https://aottech.atlassian.net/browse/FWF-1977
Remove toast notification for anonymous forms
during draft submission since anonymous drafts
are only meant for auditing.

🐛 : Remove draft notification for anonymous form

---

forms-flow-bpm/src/main/resources/META-INF/resources/webjars/camunda/app/tasklist/default/scripts/user-custom-scripts.js

JIRA: 
Fix potential XSS vulnerability in the '$.fn.resizable' plugin.
Tested in a branch by executing codeQL scanning before and after adding the fix.
After change

Fix unsafe jQuery plugin

---

CHANGELOG.md

formio health point added in changelog

change log updated

---

deployment/docker/sample.env

JIRA: 
Added cookie secure flag to sample env file

Added cookie secure flag to sample env

---

forms-flow-web/src/apiManager/services/formatterService.js
forms-flow-web/src/components/Form/Steps/PreviewStepper.js

fixed copy text in unSecureContext of browser

🐛 fixed copy anonymous URL

---

forms-flow-web/src/components/Dashboard/Dashboard.js

1. fixed pagination limit change issue

🐛 fixed pagination issue in dashboard page

---

forms-flow-web/src/components/Dashboard/Dashboard.js

1. fixed bug: changing the active page to 1 while changing the date range

🐛 fixed active page in dashboard

---

deployment/docker/docker-compose.yml
forms-flow-api/docker-compose.yml

JIRA: 
Removed the space left behind the jwt secret of form embeding

form-embed jwt secret changed

---

CHANGELOG.md
forms-flow-bpm/README.md

JIRA: 
Update changelog to include SESSION_COOKIE_SECURE env variable. 
Add SESSION_COOKIE_SECURE to bpm readme.

Update changelog and bpm readme

---

CHANGELOG.md
forms-flow-api/requirements.txt
forms-flow-api/requirements/prod.txt
forms-flow-api/tests/docker/docker-compose.yml
forms-flow-documents/requirements.txt
forms-flow-documents/requirements/prod.txt
forms-flow-documents/tests/docker/docker-compose.yml

1. change log updated
2. dependencies changed from develop to master

Dependencies changed

---

deployment/Service-Name-Installation/docker-compose.yml
deployment/Service-Name-Installation/sample.env

JIRA: 
Issue Type: BUG/FEATURE
docker-compose.yml file updated with some changes in the env variable of BPM service 
sample.env file updated with additional varibale for keycloak (for bpm server )
Locally tested in the linux environment and Task as well as History created in the forms-flow-web .

env variables updated and docker-compose.yml file updated 

---

forms-flow-web/src/components/Form/Steps/PreviewStepper.js

JIRA: https://aottech.atlassian.net/browse/FWF-1728
Added the protocol with copied url.

copy anonymous form URL with protocol

---

forms-flow-web/src/components/Form/FileUpload/fileUploadModal.js
forms-flow-web/src/components/Form/List.js

JIRA: https://aottech.atlassian.net/browse/FWF-1969
Multiple success messages were being displaied while uploading multiple forms together

Removed multiple success messages on uploading multiple forms. 

---

forms-flow-web/src/components/Form/List.js

JIRA:  https://aottech.atlassian.net/browse/FWF-1982
Login to app2 and search for a form.
Select All from the drop down.
Close the searched result and  if the number of previous search result was not being cleard. 
if it was 1 in search, then the number of forms after closing the search was also the same. 
fix. changed the limit to defaul(5) in the onClear fucntion.
#not a ui issue.

App2 - Pagination issue after searching for a form

---

forms-flow-web/src/components/Form/Item/Edit.js
forms-flow-web/src/components/Form/Item/FormHistoryModal.js

JIRA: https://aottech.atlassian.net/browse/FWF-2012
https://aottech.atlassian.net/browse/FWF-2013

updated version tags

---

deployment/docker/docker-compose.yml
deployment/docker/sample.env
forms-flow-forms/docker-compose.yml
forms-flow-forms/sample.env

1. formio image update
2. renamed client UI env variable

Formio image update

---

forms-flow-web/src/components/Form/FileUpload/fileUploadModal.js
forms-flow-web/src/components/Form/List.js

JIRA: 
Was being failed on uploadin forms with no formtype and the toast message was being displayed insted showing in modal
Changed the color of progress bar from green to blue on complete succes.

Removed 404 toast on file upload failure.

---

forms-flow-web/src/components/Form/List.js

JIRA: https://aottech.atlassian.net/browse/FWF-2029
Form upload button  was not working on uploading the same form multiple times.
Fixed clearing the cash as calling an event function not recognizing any change on uploading same file.

Repeated upload of same file fails issue

---

forms-flow-web/src/styles.scss

JIRA: 
https://aottech.atlassian.net/browse/FWF-1882
* Fixed css issue of draft edit on wizard

css issue fix on wizard draft

---

forms-flow-web/src/_tests_/test-helpers/helper.test.js
forms-flow-web/src/apiManager/services/formFormatterService.js
forms-flow-web/src/components/Form/Create.js
forms-flow-web/src/components/Form/Item/Preview.js
forms-flow-web/src/components/Form/List.js
forms-flow-web/src/helper/helper.js

JIRA: https://aottech.atlassian.net/browse/FWF-2019
1. when testing with tenant id containing a slash example: "mid-tenant"  it will add tenant id again and again while saving the form. 
2.

🐛 Form path and name fixed in Multitenancy 

---

forms-flow-web/src/components/Form/List.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-2030

unauthorized issue fixed

---

forms-flow-web/src/helper/formHistory.js

1. issue was decrement the version count when the tag is new_version : true
2. now fixed when the tag new_version true then only it will decrement

bug-fixed on version tags

---

forms-flow-api/src/formsflow_api/models/application.py
forms-flow-api/src/formsflow_api/models/form_process_mapper.py
forms-flow-api/src/formsflow_api/resources/roles.py
forms-flow-api/tests/unit/models/test_application.py

Add `DELETE` and `PUT` methods to cors

Bug: Enable CORS for PUT and DELETE  role APIs

---

forms-flow-api/src/formsflow_api/models/application.py
forms-flow-api/src/formsflow_api/resources/metrics.py
forms-flow-api/src/formsflow_api/schemas/__init__.py
forms-flow-api/src/formsflow_api/schemas/aggregated_application.py
forms-flow-api/src/formsflow_api/services/application.py
forms-flow-api/tests/unit/api/test_metrics.py
forms-flow-web/src/_tests_/test-components/test-dashboard/ApplicationCounter.test.js
forms-flow-web/src/_tests_/test-components/test-dashboard/Constants.js
forms-flow-web/src/_tests_/test-components/test-dashboard/dashboard.test.js
forms-flow-web/src/apiManager/services/metricsServices.js
forms-flow-web/src/components/Dashboard/ApplicationCounter.js
forms-flow-web/src/components/Dashboard/CardFormCounter.js
forms-flow-web/src/components/Dashboard/Dashboard.js
forms-flow-web/src/components/Dashboard/StatusChart.js

https://aottech.atlassian.net/browse/FWF-2000

❇️ Metrics with form version 

---

forms-flow-web/src/components/Form/Item/FormHistoryModal.js
forms-flow-web/src/resourceBundles/bg/resourceBundles.js
forms-flow-web/src/resourceBundles/de/resourceBundles.js
forms-flow-web/src/resourceBundles/en/resourceBundles.js
forms-flow-web/src/resourceBundles/formio_resourceBundles.js
forms-flow-web/src/resourceBundles/fr/resourceBundles.js
forms-flow-web/src/resourceBundles/pt/resourceBundles.js
forms-flow-web/src/resourceBundles/zh/resourceBundles.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-1996
1.change the name of edit button to Revert

💄 updated cosmetic change for form version history

---

forms-flow-idm/keycloak/docker-compose.yml

Fixing issue with keycloak db volume mapping

---

forms-flow-analytics/docs/sample_queries.md

JIRA: https://aottech.atlassian.net/browse/FWF-1998
1. analytics sample query update

sample query update

---

forms-flow-web/src/components/Draft/Edit.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-2045
* css issue with draft edit fixed

draft edit css issue fixed

---

forms-flow-web/src/apiManager/services/metricsServices.js
forms-flow-web/src/components/Dashboard/Dashboard.js
forms-flow-web/src/components/Dashboard/StatusChart.js
forms-flow-web/src/helper/helper.js

1. infinity loading when first refresh
2. fixed replace function using with null value
3. added formversion checking because sometimes it will null so we are adding a version in fornt-end side
4. modified sorting: the form versions will be not sorted from backend
5. added overlay loading into pie chart
-------------------------------------------------------------------------------------------------------------------

🐛 fixed metrics dashboard bugs

---

forms-flow-web/src/components/Form/List.js
forms-flow-web/src/helper/regExp/formSearchValidation.js
forms-flow-web/src/styles.scss

JIRA: https://aottech.atlassian.net/browse/FWF-1972
Added a new form validator to return true or false on valdation. 
Created a new validation component.

Form validator to avoid regex

---

forms-flow-web/src/styles.scss

JIRA: 
https://aottech.atlassian.net/browse/FWF-2067
* Height issue in select component fixed.

select component height issue fixed

---

forms-flow-web/src/components/Draft/Edit.js

JIRA: https://aottech.atlassian.net/browse/FWF-1742 

🐛 fixed unpublished forms display in draft

---

forms-flow-api/src/formsflow_api/services/form_embed.py

Adding default keys to the embed form

---

.gitignore
forms-flow-api/src/formsflow_api/resources/user.py
forms-flow-api/src/formsflow_api/schemas/__init__.py
forms-flow-api/src/formsflow_api/schemas/user.py
forms-flow-api/src/formsflow_api/services/external/keycloak.py
forms-flow-api/src/formsflow_api/services/factory/keycloak_admin.py
forms-flow-api/src/formsflow_api/services/factory/keycloak_client_service.py
forms-flow-api/src/formsflow_api/services/factory/keycloak_group_service.py
forms-flow-api/src/formsflow_api/services/user.py
forms-flow-api/tests/unit/api/test_user.py

JIRA: https://aottech.atlassian.net/browse/FWF-2063
support user search
support pagination
include role attributes with
user role/group data

Modify user list API

---

forms-flow-api/src/formsflow_api/resources/roles.py
forms-flow-api/tests/unit/api/test_roles.py

JIRA: 
https://aottech.atlassian.net/browse/FWF-2043
Change in the authorization of admin roles APIs to be accessed by users of admin role.

Authorization change in Admin roles API

---

forms-flow-web/src/apiManager/services/processServices.js
forms-flow-web/src/components/Dashboard/StatusChart.js
forms-flow-web/src/components/Draft/Edit.js

1. sorting form versions in metrics
2. fixed: when form deleted then no draft will be saved
3. fixed: if form deleted then no data will show in draft edit

🐛 Draft and metrics fix

---

forms-flow-idm/keycloak/themes/formsflow/login/login.ftl
forms-flow-idm/keycloak/themes/formsflow/login/resources/css/login.css

JIRA: 
https://aottech.atlassian.net/browse/FWF-1933
Updated UI changes for login page

Social providers css updated

---

forms-flow-api/requirements.txt
forms-flow-api/requirements/prod.txt

Updating repo link to point to main repo

---

README.md

Update Readme to reflect new documentaion

---

forms-flow-api/src/formsflow_api/resources/user.py
forms-flow-api/src/formsflow_api/services/external/keycloak.py
forms-flow-api/src/formsflow_api/services/factory/keycloak_client_service.py
forms-flow-api/src/formsflow_api/services/factory/keycloak_group_service.py
forms-flow-api/tests/unit/api/test_user.py

JIRA: https://aottech.atlassian.net/browse/FWF-2063
API offset is set to be calculated from
the page number and the limit.

🐛  Correction for wrong offset

---

.github/workflows/forms-flow-root-config-cd.yml

JIRA: 
Add a sample workflow file to support 
`5.2.0-alpha` branch.

Add root config workflow

---

.github/workflows/forms-flow-root-config-cd.yml

workflow bugfix

---

.github/workflows/forms-flow-api-ci.yml
forms-flow-api/requirements.txt
forms-flow-api/requirements/prod.txt
forms-flow-api/src/formsflow_api/services/__init__.py
forms-flow-api/src/formsflow_api/services/rule_engine.py
forms-flow-api/tests/unit/services/test_rule_engine.py

Adding a simple lightweight rule engine service

---

.github/workflows/forms-flow-root-config-cd.yml

Add build args to GHA

---

forms-flow-web/nginx.conf

JIRA: 
https://aottech.atlassian.net/browse/FWF-2069
Added compression file to web side

🐛 gzip compression for web side

---

forms-flow-api/src/formsflow_api/resources/form_embed.py
forms-flow-api/src/formsflow_api/services/form_embed.py
forms-flow-api/tests/docker/docker-compose.yml
forms-flow-api/tests/unit/api/test_form_embed.py
forms-flow-api/tests/utilities/base_test.py
forms-flow-forms/api-spec/forms-flow-forms-api-spec.yaml

* Unpublishfix
JIRA: 
unpublished forms prevented in form embedding

Unpublish fix

---

forms-flow-api/tests/docker/docker-compose.yml

JIRA: 
Pointing branch changed to develop

pointing branch changed to develop

---

forms-flow-web/src/components/Form/Item/Edit.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-2027
* Fixed ios translation issue of form-edit

Fixed translation bug for form-edit

---

forms-flow-web/src/components/Form/Item/Edit.js
forms-flow-web/src/resourceBundles/formio_resourceBundles.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-2027
* Wizard translation typo fixed

Wizard translation typo fixed

---

forms-flow-web-root-config/src/index.ejs

JIRA: 
Update content security to flag data URLs as safe

Update content security

---

forms-flow-web/src/components/Form/Create.js

JIRA: 
* dropdown issue in form-create with translation on iOS fixed

dropdown issue with translation on iOS fixed

---

forms-flow-web/src/components/Form/List.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-1316
* highlight formname while delete

highlighted formname while delete

---

forms-flow-api/src/formsflow_api/models/draft.py
forms-flow-api/src/formsflow_api/services/form_process_mapper.py

JIRA: https://aottech.atlassian.net/browse/FWF-2079
1. when form delete then will delete the draft too

draft delete when form delete

---

forms-flow-web/src/components/Form/Item/Submission/Item/View.js

JIRA: 
Issue Type:  https://aottech.atlassian.net/browse/FWF-1635

submit btn removed

---

forms-flow-web/src/components/Form/Item/Edit.js
forms-flow-web/src/resourceBundles/bg/resourceBundles.js
forms-flow-web/src/resourceBundles/de/resourceBundles.js
forms-flow-web/src/resourceBundles/en/resourceBundles.js
forms-flow-web/src/resourceBundles/formio_resourceBundles.js
forms-flow-web/src/resourceBundles/fr/resourceBundles.js
forms-flow-web/src/resourceBundles/pt/resourceBundles.js
forms-flow-web/src/resourceBundles/zh/resourceBundles.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-2027
* Added internationalization for validation message on special characters, typo fixed.
* Refixed iOS translation issue on form-edit.

Internationalization update

---

forms-flow-web/src/components/Draft/List.js
forms-flow-web/src/components/Form/List.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-2098
Highlighted draft-name and draft-id while deleting draft

Fwf 2098/draftname highlight

---

forms-flow-api/src/formsflow_api/models/authorization.py

JIRA: 
https://aottech.atlassian.net/browse/FWF-1859

Get  api update for user_name

---

forms-flow-api/src/formsflow_api/models/application.py

JIRA: https://aottech.atlassian.net/browse/FWF-2032
1. Fixed: when the form is going to delete, take the application count and if the count is> 0 then it will show a message. here if the application's status is draft we don't want to show the message

 🐛 fixed Draft status application's count

---

forms-flow-api/src/formsflow_api/models/form_process_mapper.py
forms-flow-api/src/formsflow_api/resources/form_process_mapper.py

1. create put api for form bundle mapper data update

bundle mapper data update API created

---

forms-flow-web/src/styles.scss

JIRA: https://aottech.atlassian.net/browse/FWF-2099

wizard-page style removed

---

forms-flow-api/src/formsflow_api/models/form_bundling.py
forms-flow-api/src/formsflow_api/resources/form_bundling.py
forms-flow-api/src/formsflow_api/schemas/form_bundling.py
forms-flow-api/src/formsflow_api/schemas/form_process_mapper.py
forms-flow-api/src/formsflow_api/services/form_bundling.py

JIRA: 
API endpoint to get bundle detail by id

API endpoint to get bundle detail by id

---

forms-flow-api/tests/unit/api/test_form_bundling.py

JIRA: 
Test case added for Bundle get by id

Form bundling - Test case added for Bundle get by id

---

forms-flow-api/src/formsflow_api/resources/user.py
forms-flow-api/src/formsflow_api/services/external/keycloak.py
forms-flow-api/src/formsflow_api/services/factory/keycloak_admin.py
forms-flow-api/src/formsflow_api/services/factory/keycloak_client_service.py
forms-flow-api/src/formsflow_api/services/factory/keycloak_group_service.py
forms-flow-api/tests/unit/api/test_user.py
forms-flow-web/src/apiManager/services/bpmTaskServices.js

Updated API spec to return count by
passing count as true in query params.
JIRA: https://aottech.atlassian.net/browse/FWF-2100
`/user` API spec update

User list API update to return count

---

forms-flow-web/src/components/Bundle/steps/PreviewAndConfirm.js

stepper comment fix

---

forms-flow-web/src/apiManager/services/metricsServices.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-2087
Encoded the SpecialCharacter for the better search in Dashboard Metrics

Encoded the SpecialCharacter for the better search in Dashboard Metrics

---

forms-flow-api/src/formsflow_api/resources/form_bundling.py
forms-flow-api/src/formsflow_api/services/form_bundling.py
forms-flow-api/tests/unit/api/test_form_bundling.py

JIRA: 
- Combined bundle get by id & forms under bundle into the single endpoint.
- This endpoint returns all forms(active & inactive) under bundle with corresponding rules, form order, etc.
- Checks the given bundle id is not deleted for the designer & the active bundle for other users.

Combined bundle get by id & forms under bundle into single endpoint.

---

forms-flow-web/src/components/Bundle/Stepper.js
forms-flow-web/src/components/Bundle/bundleDesign/BundleCreateAndEdit.js
forms-flow-web/src/components/Bundle/bundleDesign/FormListModal.js
forms-flow-web/src/components/Bundle/bundleDesign/SelectedForms.js
forms-flow-web/src/components/Bundle/steps/PreviewAndConfirm.js
forms-flow-web/src/components/Bundle/steps/PreviewBundle.js

updated bundle design ui

---

forms-flow-api/src/formsflow_api/resources/metrics.py

metrics url bug fix

---

forms-flow-web/src/components/Draft/Edit.js
forms-flow-web/src/components/Draft/List.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-2104

Getting error message on clicking Confirm button while deleting drafts fixed

---

forms-flow-web/src/components/Form/Item/Edit.js

bug fix for form edit

---

forms-flow-web/src/components/Form/Item/Edit.js

initially when the day or date and time component changed new history is created that issue is fixed
JIRA: 
https://aottech.atlassian.net/browse/FWF-1952

date and time component comparison fix

---

forms-flow-web/src/components/Bundle/steps/PreviewAndConfirm.js
forms-flow-web/src/components/Form/List.js
forms-flow-web/src/components/Form/constants/BundleTable.js

💄 cosmetic changes

---

forms-flow-web/src/components/BaseRouting.jsx

JIRA: https://aottech.atlassian.net/browse/FWF-2080

🐛 : Routing bugfix

---

forms-flow-web/src/components/Bundle/bundleDesign/BundleCreateAndEdit.js
forms-flow-web/src/components/Bundle/bundleDesign/SelectedForms.js
forms-flow-web/src/components/Bundle/steps/PreviewBundle.js

added cosmetic changes

---

forms-flow-web/src/components/Bundle/bundleDesign/BundleCreateAndEdit.js
forms-flow-web/src/components/Bundle/bundleDesign/RuleCreateModal.js

fixed form creation error in bundling

---

forms-flow-api/src/formsflow_api/services/form_bundling.py

form order sort fixed

---

forms-flow-web/src/components/Bundle/bundleDesign/BundleCreateAndEdit.js

1. when we select form and then click cancel so need to go to the original state
2. formio validation for update bundle

fixed validation

---

forms-flow-web/src/components/Bundle/bundleDesign/BundleCreateAndEdit.js
forms-flow-web/src/components/Bundle/bundleDesign/SelectedForms.js

cosmetic changes

---

forms-flow-api/src/formsflow_api/models/form_bundling.py
forms-flow-api/src/formsflow_api/resources/form_process_mapper.py
forms-flow-api/src/formsflow_api/resources/user.py
forms-flow-api/src/formsflow_api/schemas/form_bundling.py
forms-flow-api/src/formsflow_api/services/form_bundling.py
forms-flow-api/src/formsflow_api/services/form_process_mapper.py
forms-flow-web/src/apiManager/services/processServices.js
forms-flow-web/src/components/Bundle/bundleDesign/BundleCreateAndEdit.js
forms-flow-web/src/components/Bundle/bundleDesign/SelectedForms.js
forms-flow-web/src/components/Form/Item/Edit.js
forms-flow-web/src/components/Form/List.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-2127
- If the form included in the bundle is deleted,  form entries from the bundle table are deleted.
- Update in get bundle forms by Id to maintain form order after form deletion

Remove deleted form from bundle

---

forms-flow-web/craco.config.js
forms-flow-web/scripts/index.js
forms-flow-web/src/apiManager/services/userservices.js
forms-flow-web/src/components/BaseRouting.jsx
forms-flow-web/src/components/PrivateRoute.jsx

JIRA: https://aottech.atlassian.net/browse/FWF-2080

Internationalization support

---

CHANGELOG.md
README.md
forms-flow-web/forms-flow-util/package-lock.json
forms-flow-web/forms-flow-util/package.json
forms-flow-web/package-lock.json
forms-flow-web/package.json

JIRA: 
fixed majority of vulnerability in utils package also in web component
loader-util package is a breaking change that requires react-scripts v5.0.1 that cause major issues to our current build so skipping that

fixed vulnerabiity of tar

---

forms-flow-web/src/components/Modeler/Editors/BpmnEditor/index.js
forms-flow-web/src/components/Modeler/Editors/DmnEditor/index.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-1718
Removed some fuctions that kill and initialize new bpmn or dmn consoles after the deployment

 Displays Diagram after creating a new BPMN or DMN in Process.

---

forms-flow-web/src/components/Form/Item/View.js

JIRA: 
Issue Type: BUG/ FEATURE 
https://aottech.atlassian.net/browse/FWF-2107
Added success toaster message in draft creation where there is no data change.

toaster message added

---

forms-flow-web/src/components/Bundle/bundleDesign/BundleCreateAndEdit.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-2134
NUMBER-5
Make Save & Preview button and Save Bundle button  disabled , If there is no forms in bundle while creating and editing a bundle

Save Button disabled, if no forms exist in bundle

---

forms-flow-api/tests/docker/docker-compose.yml

JIRA: 
Change the reference of the fork to point toward the upstream repo.

Change the reference of the fork to point toward the upstream.

---

forms-flow-api/src/formsflow_api/services/factory/keycloak_client_service.py

roles API spec bugfix for role based env

---

forms-flow-api/src/formsflow_api/services/rule_engine.py

JIRA: 
Changes in execute rule engine endpoint
1. Update on find forms by parent id to include unpublished forms
3. Maintain form order in response

Changes in execute rule engine endpoint

---

forms-flow-web/src/modules/bundleReducer.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-2134
7th issue
modal sorting issue in bundling

Bundle table sort

---

forms-flow-web/src/components/Bundle/bundleDesign/FormListModal.js
forms-flow-web/src/components/Form/constants/BundleTable.js
forms-flow-web/src/components/Form/constants/FormTable.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-2134
Fixed Number 6 in FWF-2134
Fixed Search with Enter key and reset list , if no text in search input in form page ,form bundle page and  add form modal

Fixed search issues in form page ,form bundle page and  add form modal 

---

forms-flow-web/src/components/Bundle/bundleDesign/BundleCreateAndEdit.js

…ng and updating bundle
JIRA: 
https://aottech.atlassian.net/browse/FWF-2134
NUMBER-2
created toast when created and updated bundle and make validation in bundle description

Bundle name , description validation and created toast when successfully created and updated bundle

---

forms-flow-api/src/formsflow_api/resources/form_bundling.py

JIRA: 
Added docs for bundle APIs

Added docs for bundle APIs

---

forms-flow-web/src/components/Bundle/item/BundleSubmit.js

1. bundled form validation when form submission happened. will check all forms again while submitting the bundle

Bundle client side validation implemented

---

forms-flow-web/src/components/Bundle/item/BundleSubmit.js
forms-flow-web/src/components/Bundle/item/index.js
forms-flow-web/src/components/Form/List.js

1. fixed stepper label color if it is not valid
2. changed form fetching API from bundle to rule execution
3. changed redirect URL /bundle to /form when client submit a form

fixed validation stepper 

---

forms-flow-api/src/formsflow_api/models/application.py
forms-flow-api/src/formsflow_api/models/draft.py
forms-flow-api/src/formsflow_api/resources/application.py
forms-flow-api/src/formsflow_api/resources/draft.py
forms-flow-api/src/formsflow_api/schemas/application.py
forms-flow-api/src/formsflow_api/schemas/draft.py
forms-flow-api/src/formsflow_api/services/application.py

JIRA: 
1. form type added in application and draft responses

Form type added in response

---

forms-flow-web/src/components/Bundle/item/BundleSubmit.js

application create bug fixed in bundle

---

forms-flow-api/src/formsflow_api/resources/application.py
forms-flow-api/src/formsflow_api/services/application.py
forms-flow-api/src/formsflow_api/services/external/bpm.py
forms-flow-api/tests/docker/docker-compose.yml
forms-flow-api/tests/unit/api/test_application.py
forms-flow-bpm/api-spec/forms-flow-bpm-api-spec.yaml

JIRA: 
https://aottech.atlassian.net/browse/FWF-2109
BPM message endpoint call from webapi on resubmit
Patch the process variables on re-submission

Web API: Application resubmit endpoint

---

forms-flow-web/src/apiManager/endpoints/index.js
forms-flow-web/src/apiManager/services/applicationServices.js
forms-flow-web/src/components/Form/Item/Submission/Item/Edit.js
forms-flow-web/src/constants/applicationConstants.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-2175
front  end changes for task resubmission

updated resubmission endpoint

---

forms-flow-web/src/components/Form/constants/FormTable.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-2181
FormBundling - Form listing Issue Client side solved

FormBundling - Form listing Issue Client side solved

---

forms-flow-api/tests/docker/docker-compose.yml

JIRA: 
Change reference from feature branch to develop in webapi test docker file

Webapi: Change reference from feature branch to develop

---

forms-flow-web/src/components/Bundle/bundleDesign/FormListModal.js
forms-flow-web/src/components/Form/constants/BundleTable.js
forms-flow-web/src/components/Form/constants/FormTable.js
forms-flow-web/src/styles.scss

JIRA: 
https://aottech.atlassian.net/browse/FWF-2159
NUMBER_3
Updated Sort button in  Bundle table , form table and in Bundle creation/edit-- adding forms modal  , Add tooltip on sort button

sort button updated in Bundle table , form table and in bundle creation page 

---

forms-flow-web/src/components/Dashboard/StatusChart.js
forms-flow-web/src/resourceBundles/bg/resourceBundles.js
forms-flow-web/src/resourceBundles/de/resourceBundles.js
forms-flow-web/src/resourceBundles/en/resourceBundles.js
forms-flow-web/src/resourceBundles/formio_resourceBundles.js
forms-flow-web/src/resourceBundles/fr/resourceBundles.js
forms-flow-web/src/resourceBundles/pt/resourceBundles.js
forms-flow-web/src/resourceBundles/zh/resourceBundles.js

JIRA: 
* Updated translation of status chart dropdown

Status chart translation update

---

forms-flow-bpm/src/main/java/org/camunda/bpm/extension/commons/utils/VariableConstants.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/listeners/BPMFormDataPipelineListener.java

JIRA: 
https://aottech.atlassian.net/browse/FWF-2180

added skipsanitize for bundled applications

---

forms-flow-api/src/formsflow_api/schemas/application.py
forms-flow-api/src/formsflow_api/services/application.py
forms-flow-api/src/formsflow_api/services/draft.py

JIRA: 
https://aottech.atlassian.net/browse/FWF-2161
On the bundle submission group all task variables of forms inside the bundle
Add them to process instance variables

Bundle task variables

---

forms-flow-web/src/components/Bundle/bundleDesign/FormListModal.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-2159
fixed position of the sort button changes while sorting and  break large form name

 fixed position of the sort button changes while sorting and breaks large form name

---

forms-flow-web/craco.config.js

JIRA: https://aottech.atlassian.net/browse/FWF-2226
Issue Type: BUG/

Optimize compile time

---

forms-flow-web/package-lock.json
forms-flow-web/src/components/Form/Item/Edit.js

1. package-lock file updated
2. duplicate code removed

Package-lock updated of web and duplicate code removed

---

forms-flow-web/src/components/Form/Item/View.js

…r a while in draft side
JIRA: 
https://aottech.atlassian.net/browse/FWF-2178
Solved issue, Getting multiple toast after leaving the screen idle for a while in draft side

Solved issue : Getting multiple toast 

---

forms-flow-bpm/src/main/java/org/camunda/bpm/extension/commons/utils/RestAPIBuilderConfigProperties.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/commons/utils/RestAPIBuilderUtil.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/listeners/ApplicationAuditListener.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/keycloak/rest/KeycloakAuthenticationFilter.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/keycloak/rest/RestApiSecurityConfig.java
forms-flow-bpm/src/test/java/org/camunda/bpm/extension/hooks/listeners/ApplicationAuditListenerTest.java

JIRA: 
https://aottech.atlassian.net/browse/FWF-2133
* [Fix: userID extracted from application variables](https://github.com/AOT-Technologies/forms-flow-ai/commit/ea820c3fcd342e96895816f2f7ef4fce7f3ce3f1) :

Fix: userID extracted from application variables

---

forms-flow-web/src/resourceBundles/bg/resourceBundles.js
forms-flow-web/src/resourceBundles/en/resourceBundles.js
forms-flow-web/src/resourceBundles/formio_resourceBundles.js
forms-flow-web/src/resourceBundles/pt/resourceBundles.js
forms-flow-web/src/resourceBundles/zh/resourceBundles.js

JIRA: 
Duplication in translation file is removed

duplication in translation key is removed

---

forms-flow-web/src/components/Application/Details/ApplicationDetails.js
forms-flow-web/src/components/Application/ViewApplication.js
forms-flow-web/src/components/Draft/Edit.js
forms-flow-web/src/components/Draft/List.js
forms-flow-web/src/components/Form/Item/Edit.js
forms-flow-web/src/components/Form/Item/Preview.js
forms-flow-web/src/components/Form/Item/Submission/Item/View.js
forms-flow-web/src/components/Form/Item/View.js
forms-flow-web/src/components/Form/List.js
forms-flow-web/src/components/Form/Steps/PreviewStepper.js
forms-flow-web/src/helper/helper.js

JIRA: 
Issue Type: https://aottech.atlassian.net/browse/FWF-2208
1.Form title fixed

formtitle length fixed

---

forms-flow-web-root-config/src/index.ejs
forms-flow-web/package-lock.json
forms-flow-web/package.json

1. fixed date issue
2. internationalization

upgraded formio version 

---

forms-flow-web/package-lock.json

JIRA: 
Inorder to fix the date/time component the react-formio package is updated

Package updated for react-formio to 5.0.0-rc.2

---

forms-flow-web/src/components/Application/Details/ApplicationDetails.js
forms-flow-web/src/components/Application/ViewApplication.js
forms-flow-web/src/components/Application/table.js
forms-flow-web/src/components/Dashboard/StatusChart.js
forms-flow-web/src/components/Draft/Details/DraftDetails.js
forms-flow-web/src/components/Draft/table.js
forms-flow-web/src/components/Form/Item/Edit.js
forms-flow-web/src/components/Form/Item/View.js
forms-flow-web/src/components/Form/List.js
forms-flow-web/src/components/Form/Steps/PreviewStepper.js

JIRA: https://aottech.atlassian.net/browse/FWF-2208

formtitlefix

---

forms-flow-web/src/components/Form/Item/Submission/Item/Edit.js
forms-flow-web/src/components/Form/Item/Submission/Item/View.js
forms-flow-web/src/components/Form/Item/Submission/Item/index.js
forms-flow-web/src/modules/customSubmissionReducer.js
forms-flow-web/src/modules/formReducer.js
forms-flow-web/src/modules/index.js

1. Moved custom submission reducer to a new file
2. fixed application id on custom submission data

FIX: Resubmit of form to custom URL

---

.github/workflows/forms-flow-web-cd.yml
forms-flow-web/scripts/index.js

1. Added check if the branch is develop then push the build to dev path

updated cd for formsflow-web

---

forms-flow-api/Dockerfile
forms-flow-bpm/Dockerfile
forms-flow-web-root-config/Dockerfile

JIRA: https://aottech.atlassian.net/browse/FWF-2283
FEATURE
1.  Added label in Dockerfile
2.  Label : "Name":"formsflow"
3.  Label can be used in removing containers and images of formsflow only
Locally tested with the images with label and removed the container as well as images using the label name, got worked

added label in Dockerfile

---

forms-flow-analytics/docker-compose.yml

Update docker-compose.yml with 10.1.5 image

---

forms-flow-web/src/components/ServiceFlow/list/sort/CreateNewFilter.js
forms-flow-web/src/constants/taskConstants.js

JIRA: 
fixed ui bugs in create filter and the order of the payload changed based on different conditions

create filter bug fix and payload change

---

forms-flow-web/src/components/ServiceFlow/list/sort/NoFilterSelected.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-2300
fixed the error

fixed the error

---

forms-flow-web/src/components/Form/List.scss
forms-flow-web/src/components/Insights/Insights.js
forms-flow-web/src/components/Modeler/Modeler.scss

JIRA:
https://aottech.atlassian.net/browse/FWF-2140
Micro-front-end-Ui Issue fixes for Mobile

Microfrontend UI issues fix

---

forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/listeners/task/FormConnectorListener.java
forms-flow-bpm/src/test/java/org/camunda/bpm/extension/hooks/listeners/task/FormConnectorListenerTest.java

JIRA: 
https://aottech.atlassian.net/browse/FWF-2304
formUrl is set as a local variable.
So that parallel tasks can access separate formUrl

Update in FormConnectorListener

---

.github/workflows/forms-flow-web-cd.yml
deployment/docker/docker-compose.yml
deployment/docker/sample.env
forms-flow-web-root-config/docker-compose.yml
forms-flow-web-root-config/sample.env

changed defualt value with version

---

forms-flow-web/src/components/Application/table.js
forms-flow-web/src/components/Dashboard/StatusChart.js
forms-flow-web/src/components/Draft/List.js
forms-flow-web/src/components/Form/Item/Edit.js
forms-flow-web/src/components/Form/Item/FormHistoryModal.js
forms-flow-web/src/components/Form/Item/Submission/Item/Edit.js
forms-flow-web/src/components/Form/Item/Submission/Item/View.js

JIRA: 
Issue Type: https://aottech.atlassian.net/browse/FWF-2332

Fahad aot patch 1

---

.github/workflows/forms-flow-root-config-cd.yml
.github/workflows/forms-flow-web-cd.yml
deployment/docker/docker-compose.yml
deployment/docker/sample.env
forms-flow-web-root-config/docker-compose.yml
forms-flow-web-root-config/public/config/config.sample.js
forms-flow-web-root-config/sample.env

default value updated in docker-compose file of formsflow-web

---

forms-flow-web/src/components/PrivateRoute.jsx

JIRA: https://aottech.atlassian.net/browse/FWF-2261

Unauthorize issue fix when login to application 

---

forms-flow-web-root-config/sample.env
forms-flow-web/Dockerfile
forms-flow-web/craco.config.js
forms-flow-web/docker-compose.yaml
forms-flow-web/nginx.conf
forms-flow-web/src/components/PrivateRoute.jsx

JIRA: https://aottech.atlassian.net/browse/FWF-2365

Docker file added to formsflow-web 

---

forms-flow-web-root-config/package-lock.json
forms-flow-web-root-config/package.json
forms-flow-web/package-lock.json
forms-flow-web/package.json

JIRA: 
https://aottech.atlassian.net/browse/FWF-2333

vulnerity-fix for web and root-config

---

forms-flow-api-utils/src/formsflow_api_utils/utils/pdf.py
forms-flow-documents/requirements.txt

JIRA: 
https://aottech.atlassian.net/browse/FWF-2360
**TypeError: __init__() got multiple values for argument 'options' on pdf download.**
**After fixing**

Pdf download fix

---

forms-flow-data-analysis-api/src/api/resources/sentiment_analysis.py
forms-flow-data-analysis-api/src/api/services/transformers.py
forms-flow-documents/requirements.txt
forms-flow-documents/requirements/prod.txt

Updating dependencies

---

forms-flow-bpm/src/main/java/org/camunda/bpm/extension/commons/connector/support/FormAccessHandler.java

JIRA: 
https://aottech.atlassian.net/browse/FWF-2326
Issue
On upload of file size more than 2MB,  Bpm throws "DataBufferLimitException: Exceeded limit on max bytes to buffer : 2097152 " error when reading/patching data from formio.
Change done
Used the bodyToFlux method to receive the response as a Flux<DataBuffer>, which allows you to process the response in a streaming manner.

Fix max size exceeds issue on file upload

---

forms-flow-web/src/components/Form/List.js

JIRA: https://aottech.atlassian.net/browse/FWF-2311
Issue  FEATURE
Handles uploading multiple forms from formio

Uploading forms from formio

---

forms-flow-bpm/Dockerfile
forms-flow-bpm/pom.xml

Update BPM dependencies

---

forms-flow-web/src/components/PrivateRoute.jsx

JIRA: https://aottech.atlassian.net/browse/FWF-2370

fixed redirect to 404

---

.github/workflows/forms-flow-root-config-cd.yml
deployment/docker/docker-compose.yml
deployment/docker/sample.env
forms-flow-web-root-config/docker-compose.yml
forms-flow-web-root-config/sample.env

JIRA: https://aottech.atlassian.net/browse/FWF-2373

added version to s3 url

---

forms-flow-web-root-config/src/formsflow-root-config.js
forms-flow-web-root-config/src/serviceWorkerSetup.js
forms-flow-web-root-config/src/worker.js

JIRA: 
fixed service worker registeration

service-worker_fix

---

deployment/docker/docker-compose.yml
forms-flow-web-root-config/docker-compose.yml
forms-flow-web-root-config/src/index.ejs

JIRA:  https://aottech.atlassian.net/browse/FWF-2364
Fix for http ip running with node env as production

Fix for http ip running with node env as production

---

.github/workflows/forms-flow-web-cd.yml
forms-flow-web-root-config/Dockerfile
forms-flow-web/Dockerfile

JIRA: 
https://aottech.atlassian.net/browse/FWF-2333
tested locally working fine

docker file updated

---

forms-flow-web/src/components/PublicRoute.jsx

added public event in public router.jsx

---

.github/workflows/forms-flow-api-cd.yml
.github/workflows/forms-flow-bpm-cd.yml
.github/workflows/forms-flow-data-analysis-api-cd.yml
.github/workflows/forms-flow-documents-cd.yml
.github/workflows/forms-flow-root-config-cd.yml
deployment/docker/docker-compose.yml
deployment/docker/sample.env
forms-flow-bpm/Dockerfile-ARM64
forms-flow-documents/Dockerfile-ARM64
forms-flow-web-root-config/docker-compose.yml
forms-flow-web-root-config/sample.env

Adding platform to built image
JIRA: 

Pointing S3 urls to cloudfront and multi-arch support for docker images

---

forms-flow-web-root-config/src/index.ejs

Opening frame source

---

forms-flow-web-root-config/Dockerfile
forms-flow-web/Dockerfile

JIRA: 
https://aottech.atlassian.net/browse/FWF-2333

Updated Ngnix version

---

forms-flow-web/src/components/Form/Item/index.js

JIRA: 
401 issue in form submission for reviewer is fixed now form auth verify is only checking for client and designer reviewer can submit all forms

401 issue in form submission for reviewer fixed

---

forms-flow-api/migrations/versions/e1ccede6ab26_add_existing_forms_to_designer_authorization.py

JIRA: 
Added a check before inserting existing forms into the authorization table to avoid duplicate entries.

Update in moving existing forms to designer authorization

---

deployment/docker/docker-compose.yml
forms-flow-forms/docker-compose.yml

upgraded formio version

---

forms-flow-web-root-config/src/index.ejs

JIRA: https://github.com/AOT-Technologies/forms-flow-ai/pull/1512
Added http and https in image source 
To allow uploading logo images, enabled http and https in indes.ejs

Logo upload

---

forms-flow-api/src/migration_scripts/camunda_authorization_migration.py
forms-flow-web/src/components/Form/Item/index.js

JIRA: https://aottech.atlassian.net/browse/FWF-2399

Fixed auth for reviewer and updated migration script with tenant

---

forms-flow-web/src/resourceBundles/bg/resourceBundles.js
forms-flow-web/src/resourceBundles/de/resourceBundles.js
forms-flow-web/src/resourceBundles/en/resourceBundles.js
forms-flow-web/src/resourceBundles/formio_resourceBundles.js
forms-flow-web/src/resourceBundles/fr/resourceBundles.js
forms-flow-web/src/resourceBundles/pt/resourceBundles.js
forms-flow-web/src/resourceBundles/zh/resourceBundles.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-2381
Updated internationalisation in Designer permission tooltip

updation in RBAC Internationalisation

---

forms-flow-web/package-lock.json
forms-flow-web/package.json

package.json version change formsflow-web

---

.github/workflows/forms-flow-root-config-cd.yml
.github/workflows/forms-flow-web-cd.yml
.github/workflows/forms-flow-web-ci.yml

remove 5.2.0 branch form workflows

---

forms-flow-web/src/assets/styles/layouts.scss
forms-flow-web/src/components/Form/List.js

JIRA: https://aottech.atlassian.net/browse/FWF-2432

🎨 removed margin top from main container

---

deployment/docker/docker-compose.yml
deployment/docker/sample.env
forms-flow-web-root-config/docker-compose.yml
forms-flow-web-root-config/sample.env

changed MFA cdn version to 5.2.1-alpha

---

forms-flow-web/src/assets/styles/layouts.scss
forms-flow-web/src/components/Footer/footer.scss

JIRA: https://aottech.atlassian.net/browse/FWF-2258
changed the z-index of the footer component.
Also changed the container height to auto to adjust the height to show the pagination components properly on scrolling down.

Task loading overlay overriding the footer issue

---

forms-flow-web/craco.config.js
forms-flow-web/package-lock.json
forms-flow-web/package.json

chaged craco-plugin-single-spa application form git to npm

---

deployment/docker/sample.env
forms-flow-web-root-config/public/config/config.sample.js
forms-flow-web-root-config/sample.env

env default url added for custom resource bundle

---

forms-flow-data-analysis-api/Dockerfile
forms-flow-documents/Dockerfile

Updated Dockerfile
1. Added label to Dockerfile

updated Dockerfile

---

.github/workflows/forms-flow-api-cd.yml
.github/workflows/forms-flow-bpm-cd.yml
.github/workflows/forms-flow-data-analysis-api-cd.yml
.github/workflows/forms-flow-documents-cd.yml
.github/workflows/forms-flow-root-config-cd.yml

Workflow changes to deploy to DEV environment

---

.github/workflows/forms-flow-api-cd.yml
.github/workflows/forms-flow-bpm-cd.yml
.github/workflows/forms-flow-data-analysis-api-cd.yml
.github/workflows/forms-flow-documents-cd.yml
.github/workflows/forms-flow-root-config-cd.yml

Patched kubectl run command in workflow to dev

---

.github/workflows/forms-flow-api-cd.yml

Update forms-flow-api-cd.yml with image name

---

forms-flow-web/src/components/PrivateRoute.jsx

https://aottech.atlassian.net/browse/FWF-1978

updated tenant login

---

forms-flow-web/package-lock.json
forms-flow-web/package.json

Fixed json5 issue in formsflow-web  build 

---

.github/workflows/qa-deployment.yml

JIRA: 
- Added CD action to deploy to QA environment
- Asks resources under `formsflow-qa-deployment` team to approve the deployment before execution.
**Sample email for approval**

QA deployment action with approvers

---

.github/workflows/qa-deployment.yml

Setting version in CD deployment action

---

.github/workflows/forms-flow-api-cd.yml
.github/workflows/forms-flow-bpm-cd.yml
.github/workflows/forms-flow-documents-cd.yml
.github/workflows/forms-flow-root-config-cd.yml
.github/workflows/qa-deployment.yml

Adding rollout to enforce rollout in CD

---

forms-flow-web/src/components/Application/historyTable.js
forms-flow-web/src/components/Application/table.js
forms-flow-web/src/components/Draft/table.js
forms-flow-web/src/components/Form/Create.js
forms-flow-web/src/components/Form/Stepper.js
forms-flow-web/src/components/Form/Steps/PreviewStepper.js
forms-flow-web/src/components/Form/Steps/WorkFlow.js
forms-flow-web/src/components/Form/constants/table.js
forms-flow-web/src/resourceBundles/formio_resourceBundles.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-2438
* Added internationalization
* Updated enhancement

Enhancement and internationalization changes

---

forms-flow-api/src/formsflow_api/models/form_process_mapper.py
forms-flow-api/src/formsflow_api/resources/form_process_mapper.py
forms-flow-api/src/formsflow_api/schemas/form_process_mapper.py
forms-flow-api/src/formsflow_api/services/form_process_mapper.py
forms-flow-api/tests/unit/services/test_form_process_mapper.py

JIRA: https://aottech.atlassian.net/browse/FWF-2489

Added isActive parameter in listing api

---

forms-flow-web/src/components/Application/table.js
forms-flow-web/src/components/Form/Item/Submission/Item/Edit.js
forms-flow-web/src/constants/applicationConstants.js

JIRA: https://aottech.atlassian.net/browse/FWF-2455
Now isResubmit key also  checked to show EDIT button

Update application status handling for resubmit 

---

deployment/docker/sample.env
forms-flow-web-root-config/public/config/config.sample.js
forms-flow-web-root-config/sample.env

JIRA:  https://aottech.atlassian.net/browse/FWF-2184
env default url added for custom theming

env default url added for custom theming

---

forms-flow-web/src/components/Form/Steps/PreviewStepper.js
forms-flow-web/src/resourceBundles/formio_resourceBundles.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-2492
* Updated UI labels for RBAC changes

Added UI changes for RBAC

---

forms-flow-api/src/formsflow_api/resources/form_process_mapper.py

JIRA: 
https://aottech.atlassian.net/browse/FWF-2414
Instead of relying on camunda-authorization to list forms for Reviewers, changes have been made to adopt a role-based access approach.
The code for capturing the reviewer form list using camunda-authorization has been removed. Instead, the same logic used for listing forms for clients based on role-based access can now be utilized for Reviewers as well.

Reviewer formlist based on Role based access

---

forms-flow-web/src/_tests_/test-components/test-form/list.test.js
forms-flow-web/src/assets/styles/themes.scss
forms-flow-web/src/components/Application/Application.scss
forms-flow-web/src/components/Footer/footer.scss
forms-flow-web/src/components/Form/FormOperations/FormOperations.js
forms-flow-web/src/components/Form/List.js
forms-flow-web/src/components/Form/List.scss
forms-flow-web/src/components/Form/constants/table.js

JIRA: https://aottech.atlassian.net/browse/FWF-2424
Enhancement
Button padding and colour
Table alignment
Pagination alignment
sort, search and clear button's border colour
Download form button changes(The button will be enlarged only if the form is selected).
Testcase changes for list.test file
Delete button changes.

UI-Enhancement -Table and button alignments.

---

forms-flow-web/src/components/Form/Item/Submission/Item/Edit.js

updated Default Value For Custom Submission

---

forms-flow-api/src/formsflow_api/models/form_process_mapper.py
forms-flow-api/src/formsflow_api/resources/authorization.py
forms-flow-api/src/formsflow_api/services/authorization.py
forms-flow-api/tests/unit/api/test_form_process_mapper.py
forms-flow-web/src/components/Form/Item/index.js
forms-flow-web/src/components/Form/Steps/PreviewStepper.js
forms-flow-web/src/helper/helper.js

JIRA: 
1. APPLICATION type error fix
2. Form not published message blinking while form submit 
3. Permission check added in backend for designer access

RBAC FIXES 

---

.github/workflows/forms-flow-bpm-cd.yml

url changes

---

.github/workflows/forms-flow-bpm-cd.yml

Git-changes for HTML report

---

.github/workflows/forms-flow-bpm-cd.yml

sleep time changes for zap scan integration

---

forms-flow-web/src/components/Application/table.js
forms-flow-web/src/components/Form/Item/Submission/Item/Edit.js

JIRA:  https://aottech.atlassian.net/browse/FWF-2515
Changed conditions for redirection

Application resubmit issue fixed

---

forms-flow-bpm/forms-flow-bpm-camunda/src/main/java/org/camunda/bpm/extension/commons/config/ServiceFinder.java
forms-flow-bpm/forms-flow-bpm-camunda/src/main/java/org/camunda/bpm/extension/hooks/rest/TaskFilterRestResource.java
forms-flow-bpm/forms-flow-bpm-camunda/src/main/java/org/camunda/bpm/extension/hooks/rest/dto/FilterQueryDto.java
forms-flow-bpm/forms-flow-bpm-camunda/src/main/java/org/camunda/bpm/extension/hooks/rest/dto/TaskQueryDto.java
forms-flow-bpm/forms-flow-bpm-camunda/src/main/java/org/camunda/bpm/extension/hooks/rest/impl/FilterRestResourceImpl.java
forms-flow-bpm/forms-flow-bpm-camunda/src/main/java/org/camunda/bpm/extension/hooks/rest/impl/FormsFlowV1RestServiceImpl.java
forms-flow-bpm/forms-flow-bpm-camunda/src/main/java/org/camunda/bpm/extension/hooks/rest/impl/TaskFilterRestResourceImpl.java
forms-flow-bpm/forms-flow-bpm-camunda/src/main/java/org/camunda/bpm/extension/hooks/rest/service/TaskFilterRestService.java
forms-flow-bpm/forms-flow-bpm-camunda/src/main/java/org/camunda/bpm/extension/hooks/rest/service/impl/TaskFilterRestServiceImpl.java
forms-flow-bpm/forms-flow-bpm-camunda/src/main/resources/application.yaml
forms-flow-bpm/forms-flow-bpm-camunda/src/test/java/org/camunda/bpm/extension/hooks/rest/service/impl/TaskFilterRestServiceImplTest.java
forms-flow-bpm/forms-flow-bpm-utils/pom.xml

JIRA: 
https://aottech.atlassian.net/browse/FWF-2310
* Added dynamic task filter implementation logic in forms-flow-bpm
* Count endpoint added for task filters
* Endpoint added to get the count of all filters
* Postman

added dynamic task filters implementation

---

.github/workflows/forms-flow-api-cd.yml
.github/workflows/forms-flow-bpm-cd.yml
.github/workflows/forms-flow-data-analysis-api-cd.yml
.github/workflows/forms-flow-documents-cd.yml
.github/workflows/forms-flow-root-config-cd.yml

added snyk scan

---

forms-flow-web/src/components/Form/Item/Submission/Item/index.js

JIRA:  https://aottech.atlassian.net/browse/FWF-2519
Added the the edit permission for the client with conditions 
The client can resubmit the form in dynamic application status.

Application resubmit leads to 404 in client side issue fixed

---

forms-flow-web/src/helper/helper.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-2518
* Removed unwanted access denied issue while form submit

Fwf 2518/access denied fix

---

.github/workflows/forms-flow-api-cd.yml
.github/workflows/forms-flow-bpm-cd.yml
.github/workflows/forms-flow-data-analysis-api-cd.yml
.github/workflows/forms-flow-documents-cd.yml
.github/workflows/forms-flow-root-config-cd.yml

updated permission

---

forms-flow-web-root-config/src/index.ejs

JIRA: https://aottech.atlassian.net/browse/FWF-2525

Fixed bpmn css fix

---

forms-flow-web/src/components/Application/table.js

JIRA: https://aottech.atlassian.net/browse/FWF-2508
Check No: 2
previous: 
TBD: Internationalization changes.

Application id to ID

---

forms-flow-web-root-config/src/index.ejs

changed version url of bpmn css in ejs file

---

CHANGELOG.md
deployment/docker/README.md
deployment/docker/sample.env
deployment/server/deployment/README.md
forms-flow-forms/README.md
forms-flow-forms/sample.env
forms-flow-web-root-config/sample.env

JIRA: 
*  Updated readme file
*  Updated changelog
*  Added comments for env variables

Updated README.md, CHANGELOG.md

---

forms-flow-api/src/formsflow_api/models/form_process_mapper.py

JIRA: 
modified field included in the form list endpoint for reviewers & clients.

modified field included in formlist endpoint

---

deployment/docker/README.md

Removed FORMIO_CLIENT_UI env from deployment/docker/readme

---

forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/service/impl/AdminRestServiceImpl.java

JIRA: 
https://aottech.atlassian.net/browse/FWF-2532
Change in form authorization endpoint using service token to list authorization based on process definition
Old response which list based on authorizations
The new response which list based on process definition

Change in form authorization endpoint 

---

forms-flow-bpm/forms-flow-bpm-camunda/src/main/java/org/camunda/bpm/extension/hooks/rest/TaskFilterRestResource.java
forms-flow-bpm/forms-flow-bpm-camunda/src/main/java/org/camunda/bpm/extension/hooks/rest/dto/TaskQueryDto.java
forms-flow-bpm/forms-flow-bpm-camunda/src/main/java/org/camunda/bpm/extension/hooks/rest/impl/TaskFilterRestResourceImpl.java
forms-flow-bpm/forms-flow-bpm-camunda/src/main/java/org/camunda/bpm/extension/hooks/rest/service/TaskFilterRestService.java
forms-flow-bpm/forms-flow-bpm-camunda/src/main/java/org/camunda/bpm/extension/hooks/rest/service/impl/TaskFilterRestServiceImpl.java
forms-flow-bpm/forms-flow-bpm-camunda/src/test/java/org/camunda/bpm/extension/hooks/rest/service/impl/TaskFilterRestServiceImplTest.java

JIRA: 
https://aottech.atlassian.net/browse/FWF-2310
modified filter count endpoint to get the count of  task by executing filter query list
Postman

[FWF-2310] modified filter count endpoint

---

forms-flow-web/src/components/Form/List.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-2425
sort style changed for unique pattern

updated sort style

---

forms-flow-api/src/formsflow_api/schemas/filter.py

JIRA: 
Allow none included in filter schema.

Changes in filter schema

---

forms-flow-api/src/formsflow_api/models/authorization.py
forms-flow-api/src/formsflow_api/resources/authorization.py
forms-flow-api/src/formsflow_api/resources/form_process_mapper.py
forms-flow-api/src/formsflow_api/services/application.py
forms-flow-api/src/formsflow_api/services/authorization.py
forms-flow-api/src/formsflow_api/services/form_process_mapper.py
forms-flow-web/src/components/Form/Item/index.js
forms-flow-web/src/components/Form/List.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-2415
- Fix on: Previously, when a user possessed both the roles of reviewer and designer and initiated form creation, they could submit the form even in cases where they lacked the necessary submission permissions due to being the form's creator.
- Code cleanup
- File upload fix

Rbac updates

---

forms-flow-web/src/components/Modeler/Editors/BpmnEditor/index.js
forms-flow-web/src/components/Modeler/Editors/DmnEditor/index.js

JIRA: 
* Added translation for Export & Deploy buttons in BPMN, DMN.

Updated translation

---

forms-flow-documents/src/formsflow_documents/static/js/from_io_render.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-2535
Duplication of token passing to custom-submission endpoint

removed headders

---

forms-flow-web/src/components/Modeler/Editors/DmnEditor/index.js
forms-flow-web/src/components/Modeler/constants/bpmnModelerConstants.js
forms-flow-web/src/resourceBundles/formio_resourceBundles.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-2437

added text translation for dmn

---

forms-flow-web/src/components/Modeler/constants/bpmnModelerConstants.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-2503
* Updated enhancement typo fixed.
* Added corresponding resourceBundles changes here https://github.com/AOT-Technologies/forms-flow-ai-micro-front-ends/pull/59

Enhacement typo fix

---

forms-flow-api-utils/src/formsflow_api_utils/utils/constants.py

added template keys into utils

---

forms-flow-api/migration.sh
forms-flow-api/src/migration_scripts/bpm.py
forms-flow-api/src/migration_scripts/camunda_authorization_migration.py
forms-flow-api/src/migration_scripts/camunda_filter_migration.py
forms-flow-api/src/migration_scripts/invoke_scripts.py

JIRA: 
https://aottech.atlassian.net/browse/FWF-2224
- Migration script for moving existing camunda task filters to the webapi filter table.
Camunda filters
Filters have been transferred to the webapi filter table.

Migration script for task filters

---

forms-flow-web/src/components/Form/FileUpload/fileUploadModal.js
forms-flow-web/src/components/Form/Item/Edit.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-2463
* Added new internationalization changes 
*  resourceBundles' changes: https://github.com/AOT-Technologies/forms-flow-ai-micro-front-ends/pull/61/files

Added internationalization changes

---

forms-flow-web/src/components/Form/Create.js
forms-flow-web/src/components/Form/Item/Edit.js
forms-flow-web/src/custom-components/VideoEmbedding/videoEmbed.js
forms-flow-web/src/custom-components/custom button/customButton.js
forms-flow-web/src/custom-components/progress-bar/progress.js
forms-flow-web/src/custom-components/toggle-button/toggleButton.js

added group

---

forms-flow-web/src/assets/styles/themes.scss
forms-flow-web/src/components/Form/Create.js
forms-flow-web/src/components/Form/Item/Edit.js
forms-flow-web/src/components/Form/List.scss
forms-flow-web/src/components/Form/Steps/PreviewStepper.js
forms-flow-web/src/components/Form/Steps/steps.scss

#CSS-Cleanup
JIRA: https://aottech.atlassian.net/browse/FWF-2637
https://aottech.atlassian.net/browse/FWF-2645
https://aottech.atlassian.net/browse/FWF-2638
#Screen shots: 
Edit page:
Create page:
PreviewStepper

Create, Edit, previewStepper page's  M-UI to  React Bootstrap

---

forms-flow-web/src/components/Form/Steps/TaskvariableCreate.js

JIRA: https://aottech.atlassian.net/browse/FWF-2644

Task Variable Create M-UI to React-Bootstrap UI

---

forms-flow-api/src/formsflow_api/services/application.py

JIRA: 
https://aottech.atlassian.net/browse/FWF-2655
- Previously, the DataGrid was stored as an object on resubmit which has a base 64 encoded value on the task variable. Now serialized the object into a string representation and then submitted as a string value to `/message `endpoint.
- Moved fetching task variable to separate function.
**Previously DataGrid was stored as an object.**
**Serialized the object into a string representation and submitted it as a string value.**

Fix -   Data Grid stored as a task variable was not being updated properly upon resubmission.

---

forms-flow-web/src/components/Modeler/Editors/Editor.scss
forms-flow-web/src/components/Modeler/Modeler.scss
forms-flow-web/src/components/Modeler/index.js

JIRA:  https://aottech.atlassian.net/browse/FWF-2665
Changed card and grid components to React bootstrap components
#TO DO: change the colors to variables.

Modeler page M-UI to React bootstrap UI

---

forms-flow-web/src/assets/styles/themes.scss
forms-flow-web/src/components/Form/Stepper.js
forms-flow-web/src/components/Form/stepper.scss

JIRA: https://aottech.atlassian.net/browse/FWF-2639
Removed material UI Stepper and created custom, responsive and interactive stepper UI for form create and edit pages
#Note
Created this new stepper as there is no equaling component in React Bootstrap for the Material UI stepper component.

New Stepper with css

---

forms-flow-web/src/components/ServiceFlow/list/search/TaskIgnoreCaseComponent.js

JIRA: https://aottech.atlassian.net/browse/FWF-2643
Material UI Check box to React bootstrap UI Checkbox

Task Ignore Case Component M-UI to Bootstrap UI

---

forms-flow-web/src/components/Form/Steps/ViewAndEditTaskvariable.js

JIRA: 
Issue Type: https://aottech.atlassian.net/browse/FWF-2641
View and edit Task variables M-UI to Bootstrap UI

View and edit Task variables M-UI to Bootstrap UI

---

forms-flow-web/src/components/Application/Application.scss
forms-flow-web/src/components/Application/table.js
forms-flow-web/src/components/Form/constants/table.js

JIRA: https://aottech.atlassian.net/browse/FWF-2508
earlier :
Changes:

Pagination dropdown button changes.

---

forms-flow-web/src/components/Draft/Edit.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-2450
update the data only when fetching data initially

updated put call initial

---

forms-flow-bpm/forms-flow-bpm-camunda/src/main/java/org/camunda/bpm/extension/hooks/rest/dto/TaskFilterResponse.java
forms-flow-bpm/forms-flow-bpm-camunda/src/main/java/org/camunda/bpm/extension/hooks/rest/dto/TaskQueryDto.java
forms-flow-bpm/forms-flow-bpm-camunda/src/main/java/org/camunda/bpm/extension/hooks/rest/dto/TaskVariableDto.java
forms-flow-bpm/forms-flow-bpm-camunda/src/main/java/org/camunda/bpm/extension/hooks/rest/service/impl/TaskFilterRestServiceImpl.java

JIRA: 
https://aottech.atlassian.net/browse/FWF-2580
* Feilds taskVisibleAttributes , variables, count  are added in the response.
* pagination added
* Added custom Hal tasklist response implementation
* Candidate groups field is not included in the response changes

bpm changes to support custom hal tasklist with additional fields

---

forms-flow-web/src/components/Form/Steps/WorkFlow.js
forms-flow-web/src/components/Form/Steps/steps.scss

JIRA: 
Issue Type: https://aottech.atlassian.net/browse/FWF-2642
steps-workflow MUI to bootstrap

Steps-workflow MUI to bootstrap

---

docs/sequence-diagrams/client-flow.md
docs/sequence-diagrams/designer-flow.md
docs/sequence-diagrams/reviewer-flow.md

Sequence diagram for basic flows
JIRA: https://aottech.atlassian.net/browse/FWF-2485
Issue Type: DOC
Added sequence diagrams for basic Designer, Client and Reviewer flows
Please click on "Display Rich Diff" to see the sequence diagram

Sequence diagram for basic flows

---

forms-flow-web/src/components/Form/Steps/WorkFlow.js
forms-flow-web/src/components/Form/Steps/steps.scss

JIRA: 
Issue Type: https://aottech.atlassian.net/browse/FWF-2642
Change in Task Variable edit option

Change in Task Variable edit option(Steps-workflow MUI-bootstrap)

---

forms-flow-web/src/components/Form/Steps/PreviewStepper.js
forms-flow-web/src/components/Form/Steps/steps.scss

#jira ticket:
https://aottech.atlassian.net/browse/FWF-2638

Publish form check button

---

forms-flow-web/src/components/Form/Stepper.js
forms-flow-web/src/components/Form/stepper.scss

JIRA: https://aottech.atlassian.net/browse/FWF-2639
Stepper will update only when save/ next button is clicked.. Cant click on the stepper to move stepper state.

Stepper-updates on save.

---

forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/listeners/ApplicationStateListener.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/listeners/BPMFormDataPipelineListener.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/listeners/FormBPMDataPipelineListener.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/listeners/FormSubmissionListener.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/listeners/execution/ExternalSubmissionListener.java
forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/listeners/task/TaskDurationAttributesListener.java
forms-flow-bpm/src/main/resources/application.yaml

JIRA: 
https://aottech.atlassian.net/browse/FWF-2483
* added error log file + cleanup

[FWF-2483] Component changes for ELK support

---

forms-flow-web/src/assets/styles/layouts.scss
forms-flow-web/src/components/App.jsx
forms-flow-web/src/components/BaseRouting.jsx
forms-flow-web/src/components/Footer/Footer.js
forms-flow-web/src/components/Footer/footer.scss
forms-flow-web/src/components/PublicRoute.jsx
forms-flow-web/src/styles.scss

Footer changed and removed container class override

---

forms-flow-web-root-config/Dockerfile
forms-flow-web-root-config/package-lock.json
forms-flow-web-root-config/package.json
forms-flow-web/Dockerfile
forms-flow-web/package-lock.json
forms-flow-web/package.json

https://aottech.atlassian.net/browse/FWF-2654
webside fix

vulnerability fix

---

forms-flow-idm/keycloak/themes/formsflow/login/resources/css/login.css

JIRA: 
https://aottech.atlassian.net/browse/FWF-2682
* Fixed alignment issue of keycloak registration page
Alignment updated:

Fwf 2682/css fix

---

forms-flow-web/src/components/ServiceFlow/ServiceFlow.scss

JIRA: https://aottech.atlassian.net/browse/FWF-2700

serviceflow button's alignment

---

forms-flow-web/src/containers/Confirm.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-2702
* Cancel button alignment changed
* Button changed

Fwf 2702/delete confirmation modal change

---

forms-flow-web/src/_tests_/test-components/test-application/ApplicationHistory.test.js
forms-flow-web/src/_tests_/test-components/test-application/ViewApplication.test.js
forms-flow-web/src/_tests_/test-components/test-application/list.test.js
forms-flow-web/src/_tests_/test-components/test-application/test-details/ApplicationDetails.test.js
forms-flow-web/src/_tests_/test-components/test-application/test-details/nodata.test.js
forms-flow-web/src/_tests_/test-components/test-serviceflow/details/Taskheader.test.js
forms-flow-web/src/_tests_/test-helpers/user.test.js
forms-flow-web/src/apiManager/services/applicationServices.js
forms-flow-web/src/apiManager/services/formatterService.js
forms-flow-web/src/components/Application/ApplicationHistory.js
forms-flow-web/src/components/Application/Details/ApplicationDetails.js
forms-flow-web/src/components/Application/List.js
forms-flow-web/src/components/Application/ViewApplication.js
forms-flow-web/src/components/Application/table.js
forms-flow-web/src/components/Draft/Edit.js
forms-flow-web/src/components/Draft/List.js
forms-flow-web/src/components/Form/Item/Edit.js
forms-flow-web/src/components/Form/Item/View.js
forms-flow-web/src/components/Form/List.js
forms-flow-web/src/components/Form/Steps/PreviewStepper.js
forms-flow-web/src/components/Form/Steps/SaveNext.js
forms-flow-web/src/components/ServiceFlow/details/TaskHeader.js
forms-flow-web/src/resourceBundles/formio_resourceBundles.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-2669

submission  name updated

---

forms-flow-api/requirements.txt
forms-flow-api/requirements/prod.txt
forms-flow-documents/requirements.txt
forms-flow-documents/requirements/prod.txt

JIRA: 
The reference in the requirements file has been updated to switch from the feature branch to the 'develop' branch.

Requirements file updated to switch to develop

---

forms-flow-web-root-config/src/index.ejs
forms-flow-web/src/components/Dashboard/CardFormCounter.js
forms-flow-web/src/components/Draft/Edit.js
forms-flow-web/src/components/Form/Item/Edit.js
forms-flow-web/src/components/Form/Item/Preview.js
forms-flow-web/src/components/Form/Item/Submission/List.js
forms-flow-web/src/components/Form/Item/View.js
forms-flow-web/src/components/Form/List.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-2737

Font awsome broken icons fixed

---

forms-flow-web/src/components/Application/Application.scss
forms-flow-web/src/components/Modeler/constants/bpmnTable.js
forms-flow-web/src/components/Modeler/constants/dmnTable.js
forms-flow-web/src/styles.scss

JIRA: https://aottech.atlassian.net/browse/FWF-2701

dropdown fixed

---

forms-flow-web/src/components/Form/Item/Edit.js
forms-flow-web/src/components/Form/Item/SaveAsNewVersionConfirmationModal.js
forms-flow-web/src/components/Form/Steps/SaveNext.js

JIRA: 
https://aottech.atlassian.net/browse/FWF-2702
* Cancel button updated for three modals

Cancel button modal changes

---

forms-flow-web/src/apiManager/services/processServices.js
forms-flow-web/src/components/Form/Stepper.js
forms-flow-web/src/components/Modeler/Edit.js
forms-flow-web/src/components/Modeler/Editors/BpmnEditor/index.js
forms-flow-web/src/components/Modeler/Editors/DmnEditor/index.js
forms-flow-web/src/components/Modeler/constants/bpmnTable.js
forms-flow-web/src/components/Modeler/constants/dmnTable.js

JIRA: https://aottech.atlassian.net/browse/FWF-2742

Process digaram fetching issue fixed

---

forms-flow-web/src/apiManager/services/processServices.js
forms-flow-web/src/components/Application/ViewApplication.js
forms-flow-web/src/components/Draft/Edit.js
forms-flow-web/src/components/Draft/ViewDraft.js
forms-flow-web/src/components/Form/Item/View.js

1. give proper title to back button 
2. fixed fetch process on application's details view

Fixed fetchAllprocess list function breaking and give proper title to back button

---

forms-flow-web/src/components/Form/Steps/PreviewStepper.js

https://aottech.atlassian.net/browse/FWF-2669

updated title
