forms-flow-data-analysis-api/src/api/resources/sentiment_analysis.py, forms-flow-data-analysis-api/src/api/services/transformers.py
JIRA: 
Change in API response variable names **applicationId** instead of **application_id** / **overallSentiment** instead of **overall_sentiment**/ **formUrl** instead of form_url
=> Sentiment analysis API response variable names change

forms-flow-api/src/formsflow_api/models/application.py, forms-flow-api/src/formsflow_api/schemas/application.py
Added process_tenant to application schema and filter queries
Adding process_tenant to the application response would be helpful for the front end to identify the tenant of a particular process. Currently, the front end needs to loop through the process with the process key to identify the tenant during the application detail view, and only form/:formid returns the process tenant which is used for view/edit component
=> adding processTenant to application schema and application response

forms-flow-api/src/formsflow_api/resources/cmis_connector.py
JIRA: 
Change in the response of cmis download API. Response data is changed from string to binary format.
Response data in string format.
Response data in binary format.
=> Download API response data in binary format

forms-flow-api/requirements/dev.txt
JIRA: 
Issue Type: 
flake8-isort version fixed to 4.1.1
=> ✅ Ci flake8-isort version fix

forms-flow-api-utils/src/formsflow_api_utils/utils/util.py, forms-flow-api/src/formsflow_api/resources/formio.py
`/roles` API will update the cache at runtime if the cache is empty.
This will eliminate application runtime errors if failed to fetch role ids at container spinup
=> 🥅 Role api modifications

forms-flow-api-utils/src/formsflow_api_utils/utils/util.py, forms-flow-api/src/formsflow_api/config.py, forms-flow-api/src/formsflow_api/resources/formio.py, forms-flow-api/tests/unit/api/test_formio.py
- Formio token modified to contain only current users' role ids.
- `/role` API response will be empty for non-designers since the data is not required. (we still send the token )
- updated test cases for the same
=> 🛂 Role API modifications

forms-flow-web/src/components/Modeller/index.js
JIRA: [FWF-1678](https://aottech.atlassian.net/browse/FWF-1678)
Fixed the issue of App2/Multitenancy - Not getting workflow after choosing a workflow from local directory for the second time
User can now import a workflow from local directory a second time and the workflow will now be rendered in the canvas
Dropdown and canvas is updated with correct workflow
=> Fixed importing workflow for second time bug

forms-flow-web/src/apiManager/services/formatterService.js, forms-flow-web/src/components/Modeller/helpers/helper.js
JIRA: FWF-1646/1650
- Changed workflow labels in the dropdowns to show the Id's in parenthesis to differnentiate between workflows that share identical names. (Workflows can be deployed with identical names, but the Id's must be unique)
- Added a unique DRD Id to the default decision template (used when creating a new DMN workflow)
=> Modify workflow labels

forms-flow-web/src/components/Modeller/Editors/BpmnEditor/index.js, forms-flow-web/src/components/Modeller/Editors/DmnEditor/index.js, forms-flow-web/src/components/Modeller/index.js
JIRA: FWF-1700
The 'ID must be unique' error in the properties panel has been avoided by not allowing the user to select an item in the dropdown that has the process/decision that was just deployed.
=> Fixed the unique Id error in the properties panel from deployment

forms-flow-web/src/components/Modeller/Editors/BpmnEditor/index.js, forms-flow-web/src/components/Modeller/Editors/DmnEditor/index.js
JIRA: [FWF-1700](https://aottech.atlassian.net/browse/FWF-1700)
I believe that the false 'ID must be unique' error in the properties panel happens because the panel compares the ID of the deployed model to the previously cached one, and therefore the ID's are identical and the error is displayed. I have added a refresh method that destroys and initializes the modeler in order to clear the cache. A loading spinner has been added while the modeler is being refreshed.
=> Refresh modeler after deployment to fix false 'unique ID' error 

forms-flow-api/src/formsflow_api/services/user.py
JIRA: 
https://aottech.atlassian.net/browse/FWF-1840
When a new user is created in Keycloak without assigning any value for the first name, last name, or email, these fields are not returned in the Keycloak listing API, which causes a key error on these fields while searching.
Added a condition to check whether first name, last name, or email exists in keycloak user list  before searching.
**Before fix**
**After fix**
=> Webapi: Keycloak users list search fix

forms-flow-bpm/src/main/java/org/camunda/bpm/extension/commons/config/ServiceFinder.java, forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/FilterRestResource.java, forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/TaskFilterRestResource.java, forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/dto/TaskQueryDto.java, forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/impl/FilterRestResourceImpl.java, forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/impl/FormsFlowV1RestServiceImpl.java, forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/impl/TaskFilterRestResourceImpl.java, forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/service/FilterRestService.java, forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/service/TaskFilterRestService.java, forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/service/impl/FilterRestServiceImpl.java, forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/service/impl/TaskFilterRestServiceImpl.java, forms-flow-bpm/src/test/java/org/camunda/bpm/extension/hooks/rest/service/impl/TaskFilterRestServiceImplTest.java
JIRA: 
Issue Type:FEATURE
https://aottech.atlassian.net/browse/FWF-1781
* added dynamic filter implementation in forms-flow-bpm.
* BPM gets filter parameters from UI, and implement the logic to return the tasklist.
* New endpoint created to return the tasklist: `/task-filters`
=> [BPM Abstraction] FWF-1781 dynamic filter implementation

forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/TaskFilterRestResource.java, forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/impl/TaskFilterRestResourceImpl.java, forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/service/TaskFilterRestService.java, forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/rest/service/impl/TaskFilterRestServiceImpl.java, forms-flow-bpm/src/test/java/org/camunda/bpm/extension/hooks/rest/service/impl/TaskFilterRestServiceImplTest.java
JIRA: 
https://aottech.atlassian.net/browse/FWF-1872
* Added task filter count API to BPM layer, added testcases, New endpoint to retrieve the count will be `/task-filters/count`.
=> added task filter count API FWF-1872

forms-flow-api/requirements/dev.txt, forms-flow-data-analysis-api/requirements/dev.txt, forms-flow-documents/requirements/dev.txt
The latest flake8 has incompatibilities with the `flake8-quotes` plugin.
=> ✅ : flake8 version downgraded to 5.0.4

forms-flow-api/src/formsflow_api/models/application.py
JIRA: 
https://aottech.atlassian.net/browse/FWF-1953
Form Name doesn't appear in Metrics page on filter with Modified Date issue fix.
=>  Fix Form Name doesn't appear in Metrics page when using the Modified Date filter.

forms-flow-web/src/containers/NavBar.jsx
JIRA: https://aottech.atlassian.net/browse/FWF-1964
This is happening only in multitenant
environment due to hardcoding redirect
URL to `/`. Replacing hardcoded value
with dynamic base URL fix the issue.
=> 🐛 : login button redirects to 404

forms-flow-api/src/formsflow_api/resources/form_embed.py, forms-flow-api/src/formsflow_api/services/application.py
The bug was caused by passing the custom
authentication token for initializing
tasks instead of service account token.
The bug is fixed by passing the auth token
only for internal authentication API and
None for external API where the service
account token is used by default.
=> 🐛 : Task failure for external embed API

forms-flow-web/src/components/Form/Item/Edit.js, forms-flow-web/src/components/Form/Item/FormHistoryModal.js, forms-flow-web/src/components/Form/Item/Preview.js, forms-flow-web/src/helper/formHistory.js, forms-flow-web/src/modules/RestoreFormReducer.js
1. fixed old form version shown in form history: now  showing the version number
2. fixed duplicate form history: deleting parentFormId from form data
3. fixed typo in the edit window
=> 🐛 fixed form history version number

forms-flow-api/src/formsflow_api/models/application.py, forms-flow-api/src/formsflow_api/schemas/aggregated_application.py, forms-flow-api/src/formsflow_api/services/application.py, forms-flow-web/src/components/Dashboard/StatusChart.js, forms-flow-web/src/helper/helper.js
1. reduced expensive operation on db
2. removed sorting and checking functions on web side
3. taking row number and assign as version of the form by grouping with parent form id in sql query( so here version key is no matter if exist or not in old data)
=> metrics with form version rework

forms-flow-api/src/formsflow_api/schemas/__init__.py, forms-flow-api/src/formsflow_api/schemas/form_bundling.py, forms-flow-api/src/formsflow_api/services/form_bundling.py
JIRA: 
Instead of returning all Form Process Mapper fields in response, only the needed fields are returned in response
**Old response**
**Updated response**
=> Schema  added for bundle form detail

forms-flow-web-root-config/Dockerfile, forms-flow-web-root-config/package.json, forms-flow-web/src/featureToogle.js
`=> ERROR [forms-flow-web-root-config build-stage 9/9] RUN if [ production == "development" ]; then         npm run build-dev:webpack;     else        3.4s
------
> [forms-flow-web-root-config build-stage 9/9] RUN if [ production == "development" ]; then         npm run build-dev:webpack;     else         npm run build:webpack;     fi:
#0 1.822
#0 1.822 > @formsflow/root-config@ build:webpack /forms-flow-web-root-config/app
#0 1.822 > webpack --mode=production
#0 1.822
#0 1.827 sh: webpack: not found
#0 1.837 npm ERR! code ELIFECYCLE
#0 1.838 npm ERR! syscall spawn
#0 1.838 npm ERR! file sh
#0 1.839 npm ERR! errno ENOENT
#0 1.844 npm ERR! @formsflow/root-config@ build:webpack: webpack --mode=production
#0 1.844 npm ERR! spawn ENOENT
#0 1.845 npm ERR!
#0 1.845 npm ERR! Failed at the …
=> Dev dependencies changed and Process.env removed from web

forms-flow-api/src/formsflow_api/models/application.py, forms-flow-api/src/formsflow_api/services/application.py
JIRA: 
Below are changes done while fetching mapper details with application id
- form_type  included 
- mapper_id label removed. So that the id can be reused after being loaded in FormProcessMapperSchema.
Changes are done as a part of the ticket https://aottech.atlassian.net/browse/FWF-2428 since " fetching mapper details with application id" can be reused here to capture the mapper id & form type.
=> Changes in fetch form process mapper details with application id

forms-flow-data-analysis-api/Dockerfile, forms-flow-data-analysis-api/docker-compose.yml
JIRA: 
port number of forms-flow-data-analysis-api  is changed in docker-compose file as well as Dockerfile due to the issue with  previous port number . wrong port number given in the Dockerfile . gunicon was running in 5000 and exposed port number in Dockerfile was 5001.  
In the Dockerfile of forms-flow-data-analysis-api made a change that  exposed port is chnaged from 5001 to 5000 as our gunicon is running in 5000
In the docker-compose file host port is chnaged from 5001 to 6001 as 5001 is used by forms-flow-web-api
Changes tested  locally  and the docker image of data-analysis-api is working with port number 5000 and host port 6001
If 5000 port is having any conflict with forms-flow-web-api port , then can change the port number to 6001
=> port number of forms-flow-data-analysis-api is updated 

forms-flow-bpm/forms-flow-bpm-camunda/src/main/java/org/camunda/bpm/extension/hooks/rest/AuthorizationRestResource.java, forms-flow-bpm/forms-flow-bpm-camunda/src/main/java/org/camunda/bpm/extension/hooks/rest/impl/AuthorizationRestResourceImpl.java, forms-flow-bpm/forms-flow-bpm-camunda/src/main/java/org/camunda/bpm/extension/hooks/rest/impl/FormsFlowV1RestServiceImpl.java
JIRA: 
https://aottech.atlassian.net/browse/FWF-2546
Made the camunda authorization endpoint accessible for retrieving filter permissions as part of the filter migration script.
=> Enabled Camunda Authorization Endpoint for Filter Permissions in Migration Script

forms-flow-web/src/components/Form/Steps/PreviewStepper.js
JIRA: 
Changes. The popper closes on blur
=> Closs Popper on blur

forms-flow-api/src/formsflow_api/models/filter.py, forms-flow-api/src/formsflow_api/services/filter.py
JIRA: 
- In a multi-tenant setup, check for the 'All Tasks' filter. If it's not present for the specific tenant, create it, ensuring the tenant-specific 'All Tasks' filter remains undeleted by the admin.
- Edit/Delete permission to default 'All Tasks' filter in multi-tenant setup
=> Multi-tenant changes to All Tasks filter

forms-flow-api/src/formsflow_api/constants/__init__.py, forms-flow-api/src/formsflow_api/services/external/analytics_api.py, forms-flow-api/tests/unit/api/test_dashboards.py
JIRA: 
https://aottech.atlassian.net/browse/FWF-2794
Updated insights response with a proper message when analytics org is not created for a tenant
**Updated  response**
=> Update insights response with proper message when analytics org is not created for a tenant

forms-flow-web/src/components/Form/FileUpload/SelectFormForDownload.js, forms-flow-web/src/components/Form/constants/ClientTable.js, forms-flow-web/src/components/Form/constants/FormTable.js
JIRA: https://aottech.atlassian.net/browse/FWF-2847
1. added data test IDs in client table for form listing 
2. added data test IDs in form table which is used for designer form listing 
3. removed view form edit function for create a button component to reduce function creation
=> added data testid in Form client and designer table

forms-flow-api/src/formsflow_api/services/factory/keycloak_client_service.py
Query only tenant-associated users instead of retrieving all users from the entire realm.
JIRA: 
https://aottech.atlassian.net/browse/FWF-2921
Query only tenant-associated users instead of retrieving all users from the entire realm.
=> Query tenant users

forms-flow-web/src/components/ServiceFlow/list/search/TaskSearchBarListView.scss
Removed HC colors from TaskSearchBarList.scss to add color variables.
=> Removed HC colors from TaskSearchBarList.scss to add color variables.

forms-flow-api/src/formsflow_api/services/filter.py
JIRA: 
https://aottech.atlassian.net/browse/FWF-2989
Fixed - No default filters are showing on the task page if the 'All task' filter common to all tenants is deleted.
=> Multitenacy default filter fix to 5.3.1 release branch

forms-flow-web/src/components/ServiceFlow/list/search/TaskFilterViewComponent.js
JIRA:  https://aottech.atlassian.net/browse/FWF-2792
1.Disable show results and clear filter btn when there is no input
2.those btn alignement fixed
=> search filter issues

forms-flow-web/src/components/ServiceFlow/list/sort/TaskAttributeComponent.js
JIRA: https://aottech.atlassian.net/browse/FWF-3037
1.Fixed task variables are not showing in task attributes once it is saved without adding any of task variables
=> fixed Task Variables are not showing issue 

forms-flow-api/src/formsflow_api/services/external/keycloak.py, forms-flow-bpm/forms-flow-bpm-camunda/src/main/resources/application.yaml, forms-flow-bpm/forms-flow-bpm-camunda/src/test/resources/application.yaml
JIRA: N/A
Added a config setting that reads from `KEYCLOAK_URL_HTTP_RELATIVE_PATH` environment variable, with a default of `auth/`, to allow the document path used by keycloak to be overridden. This enables support of newer versions of keycloak that likely do not use the `auth/` document path (unless they are supporting a legacy deployment).
Manually verified through building and deploying image through our helm deployment
There are _many_ hardcoded references to `/auth/` in docker compose files and tests, but none of them will be impacted by this change since the new configuration will default to the hardcoded value. Only folks who choose to override this (currently undocumented) env var in their deployment will see the change.
=> update camunda config to support keycloak relative path

.github/workflows/forms-flow-api-cd.yml, .github/workflows/forms-flow-bpm-cd.yml, .github/workflows/forms-flow-documents-cd.yml, .github/workflows/forms-flow-root-config-cd.yml, .github/workflows/qa-deployment.yml
- S3 and AWS deployment needs to stay separate
- S3 will use the default AWS Access key 
- AWS deployment to use different pair
=> Adding AWS deployment access keys

forms-flow-web/src/components/Dashboard/StatusChart.js, forms-flow-web/src/components/ServiceFlow/list/sort/CreateNewFilter.js, forms-flow-web/src/components/ServiceFlow/list/sort/TaskAttributeComponent.js
JIRA: https://aottech.atlassian.net/browse/FWF-3048
https://aottech.atlassian.net/browse/FWF-3039
1. fixed task attribute select option retain when we cancel the modal
2. responsive issue in dashboard modal
3. re arranged select form option
=> Create new filter bug fixed

deployment/docker/docker-compose.yml, forms-flow-documents/docker-compose.yml, forms-flow-documents/requirements.txt, forms-flow-documents/src/formsflow_documents/config.py, forms-flow-documents/tests/conftest.py, forms-flow-documents/tests/unit/api/test_pdf.py, forms-flow-documents/tests/unit/services/test_pdf.py
JIRA: 
https://aottech.atlassian.net/browse/FWF-3163
Issue
Fix - Added setuptools pkg which is missed during the previous merge.
Issue
- documents API requires formio token to connect formio which is saved in redis cache which is missing in documents api
=> documents-api-fix

forms-flow-api/src/formsflow_api/services/filter.py, forms-flow-web/src/_tests_/test-components/test-application/test-details/ApplicationDetails.test.js, forms-flow-web/src/apiManager/services/formatterService.js, forms-flow-web/src/components/Application/Details/ApplicationDetails.js, forms-flow-web/src/components/ServiceFlow/list/ServiceTaskListViewDetails.js, forms-flow-web/src/components/ServiceFlow/list/sort/CreateNewFilter.js, forms-flow-web/src/components/ServiceFlow/list/sort/TaskAttributeComponent.js
JIRA: https://aottech.atlassian.net/browse/FWF-3051
* Submission Id issue fixed in filter search
=> Submission Id issue fixed in filter  search

forms-flow-bpm/forms-flow-bpm-camunda/src/main/java/org/camunda/bpm/extension/keycloak/sso/KeycloakLogoutHandler.java
JIRA: 
https://aottech.atlassian.net/browse/FWF-3153
* [Fix for camunda logout issue](https://github.com/AOT-Technologies/forms-flow-ai/commit/f18b0df170444649c94eb4e79f66782135c2870f)
* Change in KeycloakLogoutHandler.class
According to the [version 18 release note](https://www.keycloak.org/2022/04/keycloak-1800-released). Keycloak does not support logout with redirect_uri anymore. you need to include post_logout_redirect_uri and id_token_hint as parameters.
=> [FWF-3153] Fix for camunda logout issue

forms-flow-bpm/forms-flow-bpm-camunda/pom.xml, forms-flow-bpm/pom.xml
JIRA: 
https://aottech.atlassian.net/browse/FWF-3147
- Changes to the following files to upgrade the vulnerable dependencies to a fixed version:
- forms-flow-bpm/forms-flow-bpm-camunda/pom.xml
-  Upgrades
- springboot:3.1.5->3.1.10
- snakeyaml:2.0->2.2
- postgresql:42.4.3->42.7.2
- groovy:3.0.19->3.0.21
- graalvm->22.3.3->23.0.0
-  Screenshots
=> [Jira-3147] forms-flow-bpm vulnerability issue fix

forms-flow-web/src/components/Form/Steps/WorkFlow.js
JIRA: https://aottech.atlassian.net/browse/FWF-3179
https://aottech.atlassian.net/browse/FWF-318
* The warning that was displayed while selecting the entire task variables is removed and the same will show if the count of 
selected task variables is more than 10.
* The applicationId is removed from the task variable list as the it is passed as process instance variable by default from 
backend
=> Task variable Warning

forms-flow-api/src/formsflow_api/models/filter.py, forms-flow-api/src/formsflow_api/resources/form_process_mapper.py, forms-flow-api/src/formsflow_api/services/filter.py
JIRA: 
Fix: The task variable label is not getting updated in the task filter  when it's updated in the form mapper
update_filter_variables function - updates the filter variables for all active filters associated with a given form id. It maps the task variable keys to their corresponding labels, and then updates the labels in the filter variables. It also removes any filter variables that are not found in the task variables, except for the default variables "applicationId" and "formName".
=> Fix: Task variable label is not getting updated in task filter 

forms-flow-idm/keycloak/imports/formsflow-ai-realm.json, forms-flow-idm/realm-exports/Group based auth.json
JIRA: 
This change adds the realm-admin role to the service account user in the group-based environment. The realm-admin role is required to use the /auth/admin/realms/{realm}/partialImport endpoint in Keycloak, which is necessary for creating a separate Keycloak client for Workato integrations.
Without realm-admin role partialImport endpoint throws error
=> Added realm-admin role to service-account user

forms-flow-web/src/components/Form/Item/CreateTemplateConfirmModal.js, forms-flow-web/src/components/Form/Item/FormHistoryModal.js, forms-flow-web/src/components/Form/Item/SaveAsNewVersionConfirmationModal.js, forms-flow-web/src/components/ServiceFlow/list/sort/CreateNewFilter.js
- Form history modal
- Form table
- Submissio table
- Save new version modal
- Create a duplicate form modal
- Create new filter
JIRA: https://aottech.atlassian.net/browse/FWF-3333
Alignment issues resolved
=> FWF-3333:[Bugfix] Resolved alignment issue

.github/workflows/forms-flow-documents-ci.yml, forms-flow-api-utils/src/formsflow_api_utils/utils/pdf.py, forms-flow-documents/requirements.txt, forms-flow-documents/requirements/prod.txt
JIRA: 
https://aottech.atlassian.net/browse/FWF-3309
In a multitenancy setup, roles are stored in UserDetails, which are used to control the hiding and revealing of panels in the form. These roles were missed in the previous PR, so they are now being added to the Chrome Driver's local storage.
=> [Bugfix]: FWF-3309 Added roles to driver localstorage

forms-flow-web/src/components/Form/ExportAsPdf/button.jsx, forms-flow-web/src/components/Form/ExportAsPdf/downloadPdfButton.jsx, forms-flow-web/src/components/Form/List.js
1. Previously, users couldn't tell if the download was in progress because the button appeared to be unresponsive.
=> Added Loading to form download button

forms-flow-web/src/components/ServiceFlow/list/search/TaskSearchBarView.js
JIRA: https://aottech.atlassian.net/browse/FWF-3443
1.Fixed invalid search results clear issue
=> 🐛 FWF:3443 [Bugfix] Fixed invalid search results clearing issue

forms-flow-api/src/formsflow_api/models/application_history.py, forms-flow-api/src/formsflow_api/resources/application_history.py, forms-flow-api/src/formsflow_api/services/application_history.py, forms-flow-api/tests/unit/api/test_application_history.py, forms-flow-api/tests/unit/services/test_application_history.py
JIRA: 
https://aottech.atlassian.net/browse/FWF-3222
Handled the submittedBy "service-account" entry in the initial application history by replacing it with the application creator.
=> 🐛 FWF-3222: [Bugfix] Handle service-account in application history

forms-flow-api/src/formsflow_api/services/factory/keycloak_client_service.py
JIRA: 
https://aottech.atlassian.net/browse/FWF-3561
Fixed the issue where adding a registered user in a multitenant setup was failing.
=> FWF-3561: [Bugfix] Fixed multitenant Add registered user failing issue

forms-flow-bpm/forms-flow-bpm-camunda/pom.xml, forms-flow-bpm/pom.xml
JIRA: 
7.21.0 Cockpit shows warning to users to upgrade to premium. Downgrading to 7.20.0.
=> Reverting Camunda to 7.20.0 to avoid warning

forms-flow-web/src/components/Form/Item/Edit.js
[Bugfix] Version of form showing as null fixed on saving layout after making update to settings modal
JIRA: 
Before : 
After :
=> [Bugfix] Version of form showing as null fixed on saving layout after making update to settings modal

forms-flow-web/src/apiManager/services/processServices.js, forms-flow-web/src/components/CustomComponents/MultiSelect.js, forms-flow-web/src/components/Form/EditForm/FlowEdit.js, forms-flow-web/src/components/Form/EditForm/FormSettings.js
JIRA: https://aottech.atlassian.net/browse/FWF-3818
1. optimized code on CustomRadioButton
2. fixed issues 
3. added action on dropdown listing to get keyboard action and hover
=> FWF-3818 [bugifx] fixed modal issues

forms-flow-web/package-lock.json, forms-flow-web/package.json, forms-flow-web/src/apiManager/services/processServices.js, forms-flow-web/src/components/App.jsx, forms-flow-web/src/components/Form/EditForm/FlowEdit.js, forms-flow-web/src/components/Form/EditForm/FormEdit.js
JIRA: https://aottech.atlassian.net/browse/FWF-3881
1. implemented react query 
2. fixed process history bugs
=> Fixed process history bugs

forms-flow-web/src/components/Form/EditForm/FlowEdit.js, forms-flow-web/src/components/Form/EditForm/FormEdit.js
JIRA: 
https://aottech.atlassian.net/browse/FWF-3892
https://aottech.atlassian.net/browse/FWF-3897
Discard modal and History modal text fixes .
=> FWF-3892 [Bugfix] : Text changes fixes in history and discard modules

forms-flow-bpm/forms-flow-bpm-camunda/src/main/java/org/camunda/bpm/extension/hooks/rest/service/impl/AdminRestServiceImpl.java, forms-flow-bpm/forms-flow-bpm-camunda/src/main/java/org/camunda/bpm/extension/keycloak/plugin/CamundaAuthorizationInitializer.java, forms-flow-bpm/forms-flow-bpm-camunda/src/main/java/org/camunda/bpm/extension/keycloak/plugin/CamundaAuthorizationProperties.java, forms-flow-bpm/forms-flow-bpm-camunda/src/main/java/org/camunda/bpm/extension/keycloak/rest/KeycloakAuthenticationFilter.java, forms-flow-bpm/forms-flow-bpm-camunda/src/main/resources/application.yaml
JIRA: https://aottech.atlassian.net/browse/FWF-3878
- Add permission (role claim) as a group in camunda with prefix ROLE_
- Added automated authorization creation for the default authorizations
- Removed tenantKey prefix from the multi tenant group, as group would have it by default going forward
- Added default authorization for multi tenant using the roles with prefix ROLE_
=> Changes for adding dynamic authorizations

forms-flow-api/src/formsflow_api/resources/form_process_mapper.py, forms-flow-api/src/formsflow_api/schemas/form_process_mapper.py, forms-flow-api/src/formsflow_api/services/form_process_mapper.py, forms-flow-api/src/formsflow_api/services/import_support.py
JIRA: 
https://aottech.atlassian.net/browse/FWF-3984
- Added showForOnlyCreateSubmissionUsers parameter in form list API 
- When the showForOnlyCreateSubmissionUsers parameter is set to True, designer priorities are ignored, such as listing both active and inactive forms or listing forms created by the designer.
- Updated response for import validation to return current major & minor versions to sync with mapper response 
Form list for user with create_designs, view_designs, create_submissions permissions
showForOnlyCreateSubmissionUsers=true
=> FWF-3984: [Bugfix] Fix form submit list for designer with create submit permission

forms-flow-api/src/formsflow_api/services/process.py
JIRA: 
- Added a check for sub-flows from the process table without search to ensure the sub-flows list empty, before fetching sub-flows, dmns from camunda
=> FWF-3999: [Bugfix] Fix subflow, dmn loading issues on search

forms-flow-api/README.md, forms-flow-documents/README.md, forms-flow-redis/README.md
JIRA: 
https://aottech.atlassian.net/browse/FWF-3907
1. Added README for forms-flow-redis
2. Updated README for forms-flow-api and forms-flow-documents-api
=> Updated README for forms-flow-redis

forms-flow-web/src/components/Form/EditForm/FlowEdit.js, forms-flow-web/src/components/Form/EditForm/FormEdit.js, forms-flow-web/src/services/FileService.js
JIRA: https://aottech.atlassian.net/browse/FWF-3971
Updated file service to return the xml or form form the JSON based on the senario
Update the flow and form in edit page on import without refreshing the tab.
=> FWF-3971:[Feature] - Form and flow update in import

forms-flow-api/src/formsflow_api/models/authorization.py, forms-flow-api/src/formsflow_api/services/form_process_mapper.py, forms-flow-web/src/components/Form/EditForm/FormEdit.js, forms-flow-web/src/components/Form/EditForm/FormSettings.js
JIRA: https://aottech.atlassian.net/browse/FWF-3973
1. fixed authorization for application view
=> FWF-3972 [bugfix] fixed application authorization fixed for submitter only

forms-flow-api/src/formsflow_api/services/form_process_mapper.py, forms-flow-api/tests/unit/api/test_form_process_mapper.py
JIRA: 
-  Hyphen allowed in form title, path & name but not in start or end
=> FWF-4077: [Bugfix] Allow hyphen in form title, path & name

forms-flow-api/src/formsflow_api/services/factory/keycloak_group_service.py
JIRA: 
- Subgroups don't have tenantkey prefix but the path has  tenantkey prefix, so including groups with tenantkey prefix on the path on the user group listing
After fix
=> FWF-4087: [Bugfix] Fix multitenant subgroup listing

forms-flow-bpm/forms-flow-bpm-camunda/pom.xml, forms-flow-bpm/forms-flow-bpm-camunda/src/main/java/org/camunda/bpm/extension/commons/connector/support/BPMAccessHandler.java, forms-flow-bpm/forms-flow-bpm-camunda/src/main/resources/META-INF/resources/webjars/camunda/app/admin/styles/user-styles.css, forms-flow-bpm/forms-flow-bpm-camunda/src/main/resources/META-INF/resources/webjars/camunda/app/cockpit/styles/user-styles.css, forms-flow-bpm/forms-flow-bpm-camunda/src/main/resources/META-INF/resources/webjars/camunda/app/tasklist/styles/user-styles.css, forms-flow-bpm/forms-flow-bpm-camunda/src/main/resources/META-INF/resources/webjars/camunda/app/welcome/styles/user-styles.css, forms-flow-bpm/forms-flow-bpm-camunda/src/main/resources/application.yaml, forms-flow-bpm/pom.xml
JIRA: 
Issue Type: FWF-3701
- Upgraded spring boot from 3.1 to 3.3
- Upgraded camunda from 7.20 to 7.21
- Upgraded spring-websocket to 6.1
=> FWF-3701 : BPM upgrade to latest version

forms-flow-web/src/components/ServiceFlow/details/TaskHeaderListView.js
FWF-2459 [Bugfix] Task loading fix by avoiding conditions inside updateBPMNTask method so all latest data fetched on each update
JIRA: https://aottech.atlassian.net/browse/FWF-2459
- Calling updateBPMNTask() after any change in task page(claim,unclaim,datechange, etc..)
- Added a timeout of 2 seconds to get the latest data.
=> FWF-2459 [Bugfix] Task loading fix by fetching latest data on each update called after 2 seconds

forms-flow-api/src/formsflow_api/services/import_support.py
JIRA: 
- Given different name to track mapper response to exclude the mapper from the response if the mapper response is None
Before 
After change
=> FWF-3971: [Bugfix] Given different name for mapper response to exclude mapper from mapper response if mapper response is None

forms-flow-api/src/formsflow_api/constants/__init__.py, forms-flow-bpm/forms-flow-bpm-camunda/src/main/resources/application.yaml, forms-flow-bpm/migration/README.md, forms-flow-bpm/migration/scripts/7.0.0.sql, forms-flow-web/src/components/Modeler/helpers/helper.js
JIRA: 
- Adding manual migration scripts
- Liquibase integration would need more changes and all camunda changes also needs to be handled through liquibase
=> Adding documentation for DB migration

forms-flow-web/src/components/Form/EditForm/FormEdit.js, forms-flow-web/src/components/Form/EditForm/FormSettings.js
JIRA: https://aottech.atlassian.net/browse/FWF-4169
The issue occurs when we save the form with anonymous set to true. If we make any changes to the layout and save using the "Save Layout" or "Publish" button, the form access and submission access reset to their default values. However, the form remains marked as anonymous in the mapper. The problem is that the anonymous ID gets removed on the Formio side when saving the layout or publishing.
=> [🐛 ] Fixed: anonymouse form submission

forms-flow-web/src/constants/applicationComponent.js
currentUserRoles data to be fetched from groups variable from 'userDetails' localstorage instead of roles variable.
These are the roles listed in our ROLES page in app , but from technical side, the variable name is 'groups'
=> [Bugfix] currentUserRoles data to be fetched from groups variable from 'userDetails' localstorage instead of roles variable

forms-flow-web/src/components/CustomComponents/MultiSelect.js, forms-flow-web/src/components/Modals/ActionModal.js, forms-flow-web/src/components/Modals/TaskVariableModal.js
JIRA: https://aottech.atlassian.net/browse/FWF-3920
hexadecimal color code changed to css variables using fetcher utility
=> css variable added using fetcher utility(OPEN SRC)

forms-flow-web/src/components/Form/EditForm/FormEdit.js
https://aottech.atlassian.net/browse/FWF-4216
JIRA: 
=> added ui style of note to modal

forms-flow-api/src/formsflow_api/models/application.py, forms-flow-api/src/formsflow_api/models/form_process_mapper.py, forms-flow-api/src/formsflow_api/resources/form_process_mapper.py, forms-flow-api/src/formsflow_api/schemas/form_process_mapper.py, forms-flow-api/src/formsflow_api/services/form_process_mapper.py, forms-flow-api/tests/unit/api/test_form_process_mapper.py
JIRA: 
https://aottech.atlassian.net/browse/FWF-3748
Added submissions count for form list with create_submissions permission
`includeSubmissionsCount` query parameter added to form list endpoint` /form`
**Client1**
**client2**
**designer**
=> FWF-3748: [Feature] Added submissions count for form list with create_submissions permission

forms-flow-api/src/formsflow_api/resources/form_process_mapper.py, forms-flow-api/src/formsflow_api/services/form_process_mapper.py, forms-flow-api/tests/unit/api/test_form_process_mapper.py
JIRA: 
https://aottech.atlassian.net/browse/FWF-3748
A KeyError on parent_form_id occurs when a user with _create_designs and create_submissions permissions uses the includeSubmissionsCount=true parameter. This happens because parent_form_id is not included in the select query for fetching forms (find_all_forms) for designers but is included for clients. To resolve this, add a showForOnlyCreateSubmissionUsers (ignore designer -> schema name) check before fetching the count.
After fix
=> Bugfix: FWF-3748:  Fix keyerror for a user with create_designs and create_submissions on accessing formlist with includeSubmissionsCount=true 

forms-flow-api/requirements.txt, forms-flow-api/requirements/prod.txt, forms-flow-documents/README.md
JIRA: 
- webapi requirements sync to develop branch
- Updated preview links in documents readme point to develop
=> webapi requirements sync to develop branch

forms-flow-api/src/formsflow_api/constants/__init__.py, forms-flow-api/src/formsflow_api/services/form_process_mapper.py, forms-flow-api/src/formsflow_api/services/import_support.py, forms-flow-api/tests/unit/api/test_form_process_mapper.py
JIRA: 
https://aottech.atlassian.net/browse/FWF-4209
- Handle formio keyword in path validation
- Changes to validate path during new form creation when only the title is provided in the query parameter.
=> FWF-4209: [Bugfix] Handle formio keyword in path validation

forms-flow-web/src/components/PrivateRoute.jsx
=> [release/7.0.0 => master ] Bugfix showing conditionally rendered component in taskvariable modal

forms-flow-web/src/components/Form/components/FormSettings.js, forms-flow-web/src/components/Modals/SettingsModal.js
JIRA: https://aottech.atlassian.net/browse/FWF-4281
https://aottech.atlassian.net/browse/FWF-4313
1. Added dropdown multicomponent 
2. Updated settings modal to match with new design
=> feature/fwf-4313:Updated settings modal

.github/workflows/zap-scan.yml
- fix: update zaproxy/action-full-scan to v0.12.0 to fix artifact upload error
The workflow was failing with an error ("Create Artifact Container failed: The artifact name zap_scan is not valid") when using outdated zaproxy/action-full-scan@v0.8.0. Upgrading to v0.12.0 resolves the issue by handling artifact naming correctly.
=> Updated zap-scan.yml: Updated zap action version to v0.12.0

forms-flow-api-utils/src/formsflow_api_utils/utils/enums.py, forms-flow-api-utils/src/formsflow_api_utils/utils/util.py, forms-flow-api/requirements.txt, forms-flow-api/requirements/prod.txt, forms-flow-api/src/formsflow_api/resources/application.py, forms-flow-api/src/formsflow_api/schemas/application.py, forms-flow-api/src/formsflow_api/services/application.py, forms-flow-api/tests/unit/api/test_application.py
JIRA: 
https://aottech.atlassian.net/browse/FWF-4429
- **Added Sort using TYPE column**
- **In submission + draft listing, search by  alphabetical character on Id to  return an empty response instead of 400 error**
- **Send the form name in response**
=> Feature/fwf 4429 Application screen backend updates

forms-flow-api/src/formsflow_api/schemas/filter.py
JIRA: 
Update FilterSchema to use List of Dicts for variables  instead of VariableSchema to adapt to new fields in task filter UI
Once the fields are fixed we can update the variable schema & use it
=> Update FilterSchema to use List of Dicts for variables  instead of VariableSchema

forms-flow-web/craco.config.js, forms-flow-web/package.json
JIRA: 
DEPENDENCY PR:
___
Enhancement
___
- Enable source maps in CRACO SingleSpa plugin
- Activate devtool in webpack configuration
- Update build script to generate source maps
___
<tr>
<td>
<details>
<summary><strong>craco.config.js</strong><dd><code>Enable source maps in CRACO config</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
forms-flow-web/craco.config.js
<ul><li>Added <code>devtool: "source-map"</code> to SingleSpaApp plugin …
=> [Testing] Enable debug mode in web to test application in debug mode

forms-flow-api/src/formsflow_api/resources/submissions_filter.py, forms-flow-api/src/formsflow_api/schemas/submissions_filter.py, forms-flow-api/tests/unit/api/test_submissions_filter.py
JIRA: 
DEPENDENCY PR:
- Updated  VariableSchema to include 'type' field and update filter payload in tests
___
Enhancement, Tests
___
- Add `type` field to Variables API model
- Extend `VariableSchema` with required `type`
- Update unit tests to include `type` in payload
___
<tr>
<td>
<details>
<summary><strong>submissions_filter.py</strong><dd><code>Add `type` to Variables API model</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
=> Include type to analyze submission filter variables

CHANGELOG.md, forms-flow-api/src/formsflow_api/models/form_process_mapper.py, forms-flow-api/src/formsflow_api/resources/form_process_mapper.py, forms-flow-api/src/formsflow_api/schemas/form_process_mapper.py, forms-flow-api/src/formsflow_api/services/form_process_mapper.py
JIRA: 
https://aottech.atlassian.net/browse/FWF-5149
DEPENDENCY PR:
- Add new param in formlist API to list all forms(active&inactive)
- Fix Forms are not listing for user with only “Access to Analyze” permission - Added ANALYZE_SUBMISSIONS_VIEW permission to form list endpoint 
___
Enhancement
___
- Add `fetch_all_forms` method for retrieving all forms
- Enable `allForms` flag in request schema and endpoint
- Update service to use `fetch_all_forms` when `all_forms` is true
- Include `ANALYZE_SUBMISSIONS_VIEW` role permission
___
```mermaid
flowchart LR
A["Client Request"] --> B["Resource.get: list forms"]
B --> C["Schema: parse allForms"]
B --> D["Service.get_all_forms"]
D --> E{"all_forms param?"}
E -- "true" --> F["Model.fetch_all_forms"]
E -- "false" --> …
```
=> [Feature] Webapi: Add new param in formlist API to list all forms(active&inactive)

forms-flow-data-layer/src/utils/datetime_utils.py
JIRA: 
https://aottech.atlassian.net/browse/FWF-5146
DEPENDENCY PR:
- Refactor datetime conversion to return ISO string format with milliseconds and 'Z'
___
Enhancement
___
- Convert datetimes to ISO 8601 UTC strings
- Handle naive and aware datetimes robustly
- Include milliseconds and trailing 'Z'
- Preserve list handling and string joining
___
```mermaid
flowchart LR
A["datetime_utils.convert_datetimes_to_string(datetime)"] -- "detect tzinfo" --> B["naive -> set UTC tzinfo"]
A -- "aware -> astimezone(UTC)" --> C["convert to UTC"]
B -- "format ms + Z" --> D["ISO string e.g. 2025-04-08T06:30:00.000Z"]
C -- "format ms + Z" --> D
```
<table><thead><tr><th></th><th align="left">Relevant …
=> FWF-5146:  Refactor datetime conversion to return ISO string format with milliseconds and 'Z'

forms-flow-web/src/routes/Design/Forms/FormEdit.js
JIRA: [FWF-5349/unpublish-note-section](https://aottech.atlassian.net/browse/FWF-5349) ( **Issue 8** )
DEPENDENCY PR:
___
___
- Replace unpublish text with CustomInfo
- Add heading and test id for note
- Improve unpublish dialog accessibility
- Maintain existing actions and labels
___
```mermaid
flowchart LR
Dialog["Unpublish dialog config"] -- "message replaced" --> CustomInfo["CustomInfo component"]
CustomInfo -- "props: heading, content, dataTestId" --> UI["Improved note display"]
```
<tr>
<td>
<details>
<summary><strong>FormEdit.js</strong><dd><code>Swap …
=> FWF-5349 : [BugFix] Updated unpublish note section with CustomInfo component

deployment/docker/docker-compose.yml, forms-flow-analytics/docker-compose.yml, forms-flow-api/docker-compose.yml, forms-flow-bpm/docker-compose.yml, forms-flow-forms/docker-compose.yml, forms-flow-idm/keycloak/docker-compose.yml
JIRA: 
https://aottech.atlassian.net/browse/FWF-5390
DEPENDENCY PR:
___
Enhancement, Configuration changes
___
- Switch to named Docker volumes across services
- Replace host path mounts for databases
- Add volume declarations for new names
- Standardize compose files volume usage
___
```mermaid
flowchart LR
FS["File-system path mounts"] -- "replace with" --> NV["Named Docker volumes"]
NV -- "declared under" --> VD["volumes: definitions"]
Services["MongoDB/Postgres services"] -- "mount" --> NV
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
<td>
<details> …
=> FWF-5390 [upgrade] updated the volume mounting on docker files
